/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GenericPageRolePublic,
  HTTPValidationError,
  Message,
  RoleCreate,
  RoleMenuUpdate,
  RolePublic,
  RoleUpdate,
  WorkspaceMemberPublic,
  WorkspaceRolesReadRolesParams
} from '../schemas';

import { customFetch } from '../../lib/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve roles.
 * @summary Read Roles
 */
export type workspaceRolesReadRolesResponse200 = {
  data: GenericPageRolePublic
  status: 200
}

export type workspaceRolesReadRolesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type workspaceRolesReadRolesResponseSuccess = (workspaceRolesReadRolesResponse200) & {
  headers: Headers;
};
export type workspaceRolesReadRolesResponseError = (workspaceRolesReadRolesResponse422) & {
  headers: Headers;
};

export type workspaceRolesReadRolesResponse = (workspaceRolesReadRolesResponseSuccess | workspaceRolesReadRolesResponseError)

export const getWorkspaceRolesReadRolesUrl = (params?: WorkspaceRolesReadRolesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/workspace/roles/?${stringifiedParams}` : `/api/v1/workspace/roles/`
}

export const workspaceRolesReadRoles = async (params?: WorkspaceRolesReadRolesParams, options?: RequestInit): Promise<workspaceRolesReadRolesResponse> => {

  return customFetch<workspaceRolesReadRolesResponse>(getWorkspaceRolesReadRolesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getWorkspaceRolesReadRolesQueryKey = (params?: WorkspaceRolesReadRolesParams,) => {
    return [
    `/api/v1/workspace/roles/`, ...(params ? [params] : [])
    ] as const;
    }


export const getWorkspaceRolesReadRolesQueryOptions = <TData = Awaited<ReturnType<typeof workspaceRolesReadRoles>>, TError = HTTPValidationError>(params?: WorkspaceRolesReadRolesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoles>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWorkspaceRolesReadRolesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof workspaceRolesReadRoles>>> = ({ signal }) => workspaceRolesReadRoles(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WorkspaceRolesReadRolesQueryResult = NonNullable<Awaited<ReturnType<typeof workspaceRolesReadRoles>>>
export type WorkspaceRolesReadRolesQueryError = HTTPValidationError


export function useWorkspaceRolesReadRoles<TData = Awaited<ReturnType<typeof workspaceRolesReadRoles>>, TError = HTTPValidationError>(
 params: undefined |  WorkspaceRolesReadRolesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspaceRolesReadRoles>>,
          TError,
          Awaited<ReturnType<typeof workspaceRolesReadRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspaceRolesReadRoles<TData = Awaited<ReturnType<typeof workspaceRolesReadRoles>>, TError = HTTPValidationError>(
 params?: WorkspaceRolesReadRolesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspaceRolesReadRoles>>,
          TError,
          Awaited<ReturnType<typeof workspaceRolesReadRoles>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspaceRolesReadRoles<TData = Awaited<ReturnType<typeof workspaceRolesReadRoles>>, TError = HTTPValidationError>(
 params?: WorkspaceRolesReadRolesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoles>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Roles
 */

export function useWorkspaceRolesReadRoles<TData = Awaited<ReturnType<typeof workspaceRolesReadRoles>>, TError = HTTPValidationError>(
 params?: WorkspaceRolesReadRolesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoles>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWorkspaceRolesReadRolesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create new role.
 * @summary Create Role
 */
export type workspaceRolesCreateRoleResponse200 = {
  data: RolePublic
  status: 200
}

export type workspaceRolesCreateRoleResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type workspaceRolesCreateRoleResponseSuccess = (workspaceRolesCreateRoleResponse200) & {
  headers: Headers;
};
export type workspaceRolesCreateRoleResponseError = (workspaceRolesCreateRoleResponse422) & {
  headers: Headers;
};

export type workspaceRolesCreateRoleResponse = (workspaceRolesCreateRoleResponseSuccess | workspaceRolesCreateRoleResponseError)

export const getWorkspaceRolesCreateRoleUrl = () => {




  return `/api/v1/workspace/roles/`
}

export const workspaceRolesCreateRole = async (roleCreate: RoleCreate, options?: RequestInit): Promise<workspaceRolesCreateRoleResponse> => {

  return customFetch<workspaceRolesCreateRoleResponse>(getWorkspaceRolesCreateRoleUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      roleCreate,)
  }
);}




export const getWorkspaceRolesCreateRoleMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspaceRolesCreateRole>>, TError,{data: RoleCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof workspaceRolesCreateRole>>, TError,{data: RoleCreate}, TContext> => {

const mutationKey = ['workspaceRolesCreateRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof workspaceRolesCreateRole>>, {data: RoleCreate}> = (props) => {
          const {data} = props ?? {};

          return  workspaceRolesCreateRole(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WorkspaceRolesCreateRoleMutationResult = NonNullable<Awaited<ReturnType<typeof workspaceRolesCreateRole>>>
    export type WorkspaceRolesCreateRoleMutationBody = RoleCreate
    export type WorkspaceRolesCreateRoleMutationError = HTTPValidationError

    /**
 * @summary Create Role
 */
export const useWorkspaceRolesCreateRole = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspaceRolesCreateRole>>, TError,{data: RoleCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof workspaceRolesCreateRole>>,
        TError,
        {data: RoleCreate},
        TContext
      > => {
      return useMutation(getWorkspaceRolesCreateRoleMutationOptions(options), queryClient);
    }
    /**
 * Retrieve role options for dropdowns. Only active roles, unpaginated.
 * @summary Read Role Options
 */
export type workspaceRolesReadRoleOptionsResponse200 = {
  data: RolePublic[]
  status: 200
}

export type workspaceRolesReadRoleOptionsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type workspaceRolesReadRoleOptionsResponseSuccess = (workspaceRolesReadRoleOptionsResponse200) & {
  headers: Headers;
};
export type workspaceRolesReadRoleOptionsResponseError = (workspaceRolesReadRoleOptionsResponse422) & {
  headers: Headers;
};

export type workspaceRolesReadRoleOptionsResponse = (workspaceRolesReadRoleOptionsResponseSuccess | workspaceRolesReadRoleOptionsResponseError)

export const getWorkspaceRolesReadRoleOptionsUrl = () => {




  return `/api/v1/workspace/roles/options`
}

export const workspaceRolesReadRoleOptions = async ( options?: RequestInit): Promise<workspaceRolesReadRoleOptionsResponse> => {

  return customFetch<workspaceRolesReadRoleOptionsResponse>(getWorkspaceRolesReadRoleOptionsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getWorkspaceRolesReadRoleOptionsQueryKey = () => {
    return [
    `/api/v1/workspace/roles/options`
    ] as const;
    }


export const getWorkspaceRolesReadRoleOptionsQueryOptions = <TData = Awaited<ReturnType<typeof workspaceRolesReadRoleOptions>>, TError = HTTPValidationError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoleOptions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWorkspaceRolesReadRoleOptionsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof workspaceRolesReadRoleOptions>>> = ({ signal }) => workspaceRolesReadRoleOptions({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoleOptions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WorkspaceRolesReadRoleOptionsQueryResult = NonNullable<Awaited<ReturnType<typeof workspaceRolesReadRoleOptions>>>
export type WorkspaceRolesReadRoleOptionsQueryError = HTTPValidationError


export function useWorkspaceRolesReadRoleOptions<TData = Awaited<ReturnType<typeof workspaceRolesReadRoleOptions>>, TError = HTTPValidationError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoleOptions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspaceRolesReadRoleOptions>>,
          TError,
          Awaited<ReturnType<typeof workspaceRolesReadRoleOptions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspaceRolesReadRoleOptions<TData = Awaited<ReturnType<typeof workspaceRolesReadRoleOptions>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoleOptions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspaceRolesReadRoleOptions>>,
          TError,
          Awaited<ReturnType<typeof workspaceRolesReadRoleOptions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspaceRolesReadRoleOptions<TData = Awaited<ReturnType<typeof workspaceRolesReadRoleOptions>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoleOptions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Role Options
 */

export function useWorkspaceRolesReadRoleOptions<TData = Awaited<ReturnType<typeof workspaceRolesReadRoleOptions>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoleOptions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWorkspaceRolesReadRoleOptionsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update a role.
 * @summary Update Role
 */
export type workspaceRolesUpdateRoleResponse200 = {
  data: RolePublic
  status: 200
}

export type workspaceRolesUpdateRoleResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type workspaceRolesUpdateRoleResponseSuccess = (workspaceRolesUpdateRoleResponse200) & {
  headers: Headers;
};
export type workspaceRolesUpdateRoleResponseError = (workspaceRolesUpdateRoleResponse422) & {
  headers: Headers;
};

export type workspaceRolesUpdateRoleResponse = (workspaceRolesUpdateRoleResponseSuccess | workspaceRolesUpdateRoleResponseError)

export const getWorkspaceRolesUpdateRoleUrl = (roleId: string,) => {




  return `/api/v1/workspace/roles/${roleId}`
}

export const workspaceRolesUpdateRole = async (roleId: string,
    roleUpdate: RoleUpdate, options?: RequestInit): Promise<workspaceRolesUpdateRoleResponse> => {

  return customFetch<workspaceRolesUpdateRoleResponse>(getWorkspaceRolesUpdateRoleUrl(roleId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      roleUpdate,)
  }
);}




export const getWorkspaceRolesUpdateRoleMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspaceRolesUpdateRole>>, TError,{roleId: string;data: RoleUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof workspaceRolesUpdateRole>>, TError,{roleId: string;data: RoleUpdate}, TContext> => {

const mutationKey = ['workspaceRolesUpdateRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof workspaceRolesUpdateRole>>, {roleId: string;data: RoleUpdate}> = (props) => {
          const {roleId,data} = props ?? {};

          return  workspaceRolesUpdateRole(roleId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WorkspaceRolesUpdateRoleMutationResult = NonNullable<Awaited<ReturnType<typeof workspaceRolesUpdateRole>>>
    export type WorkspaceRolesUpdateRoleMutationBody = RoleUpdate
    export type WorkspaceRolesUpdateRoleMutationError = HTTPValidationError

    /**
 * @summary Update Role
 */
export const useWorkspaceRolesUpdateRole = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspaceRolesUpdateRole>>, TError,{roleId: string;data: RoleUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof workspaceRolesUpdateRole>>,
        TError,
        {roleId: string;data: RoleUpdate},
        TContext
      > => {
      return useMutation(getWorkspaceRolesUpdateRoleMutationOptions(options), queryClient);
    }
    /**
 * Delete a role.
 * @summary Delete Role
 */
export type workspaceRolesDeleteRoleResponse200 = {
  data: Message
  status: 200
}

export type workspaceRolesDeleteRoleResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type workspaceRolesDeleteRoleResponseSuccess = (workspaceRolesDeleteRoleResponse200) & {
  headers: Headers;
};
export type workspaceRolesDeleteRoleResponseError = (workspaceRolesDeleteRoleResponse422) & {
  headers: Headers;
};

export type workspaceRolesDeleteRoleResponse = (workspaceRolesDeleteRoleResponseSuccess | workspaceRolesDeleteRoleResponseError)

export const getWorkspaceRolesDeleteRoleUrl = (roleId: string,) => {




  return `/api/v1/workspace/roles/${roleId}`
}

export const workspaceRolesDeleteRole = async (roleId: string, options?: RequestInit): Promise<workspaceRolesDeleteRoleResponse> => {

  return customFetch<workspaceRolesDeleteRoleResponse>(getWorkspaceRolesDeleteRoleUrl(roleId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getWorkspaceRolesDeleteRoleMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspaceRolesDeleteRole>>, TError,{roleId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof workspaceRolesDeleteRole>>, TError,{roleId: string}, TContext> => {

const mutationKey = ['workspaceRolesDeleteRole'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof workspaceRolesDeleteRole>>, {roleId: string}> = (props) => {
          const {roleId} = props ?? {};

          return  workspaceRolesDeleteRole(roleId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WorkspaceRolesDeleteRoleMutationResult = NonNullable<Awaited<ReturnType<typeof workspaceRolesDeleteRole>>>

    export type WorkspaceRolesDeleteRoleMutationError = HTTPValidationError

    /**
 * @summary Delete Role
 */
export const useWorkspaceRolesDeleteRole = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspaceRolesDeleteRole>>, TError,{roleId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof workspaceRolesDeleteRole>>,
        TError,
        {roleId: string},
        TContext
      > => {
      return useMutation(getWorkspaceRolesDeleteRoleMutationOptions(options), queryClient);
    }
    /**
 * Assign menus to a role.
 * @summary Set Role Menus
 */
export type workspaceRolesSetRoleMenusResponse200 = {
  data: RolePublic
  status: 200
}

export type workspaceRolesSetRoleMenusResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type workspaceRolesSetRoleMenusResponseSuccess = (workspaceRolesSetRoleMenusResponse200) & {
  headers: Headers;
};
export type workspaceRolesSetRoleMenusResponseError = (workspaceRolesSetRoleMenusResponse422) & {
  headers: Headers;
};

export type workspaceRolesSetRoleMenusResponse = (workspaceRolesSetRoleMenusResponseSuccess | workspaceRolesSetRoleMenusResponseError)

export const getWorkspaceRolesSetRoleMenusUrl = (roleId: string,) => {




  return `/api/v1/workspace/roles/${roleId}/menus`
}

export const workspaceRolesSetRoleMenus = async (roleId: string,
    roleMenuUpdate: RoleMenuUpdate, options?: RequestInit): Promise<workspaceRolesSetRoleMenusResponse> => {

  return customFetch<workspaceRolesSetRoleMenusResponse>(getWorkspaceRolesSetRoleMenusUrl(roleId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      roleMenuUpdate,)
  }
);}




export const getWorkspaceRolesSetRoleMenusMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspaceRolesSetRoleMenus>>, TError,{roleId: string;data: RoleMenuUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof workspaceRolesSetRoleMenus>>, TError,{roleId: string;data: RoleMenuUpdate}, TContext> => {

const mutationKey = ['workspaceRolesSetRoleMenus'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof workspaceRolesSetRoleMenus>>, {roleId: string;data: RoleMenuUpdate}> = (props) => {
          const {roleId,data} = props ?? {};

          return  workspaceRolesSetRoleMenus(roleId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WorkspaceRolesSetRoleMenusMutationResult = NonNullable<Awaited<ReturnType<typeof workspaceRolesSetRoleMenus>>>
    export type WorkspaceRolesSetRoleMenusMutationBody = RoleMenuUpdate
    export type WorkspaceRolesSetRoleMenusMutationError = HTTPValidationError

    /**
 * @summary Set Role Menus
 */
export const useWorkspaceRolesSetRoleMenus = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspaceRolesSetRoleMenus>>, TError,{roleId: string;data: RoleMenuUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof workspaceRolesSetRoleMenus>>,
        TError,
        {roleId: string;data: RoleMenuUpdate},
        TContext
      > => {
      return useMutation(getWorkspaceRolesSetRoleMenusMutationOptions(options), queryClient);
    }
    /**
 * Get menus assigned to a role.
 * @summary Read Role Menus
 */
export type workspaceRolesReadRoleMenusResponse200 = {
  data: string[]
  status: 200
}

export type workspaceRolesReadRoleMenusResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type workspaceRolesReadRoleMenusResponseSuccess = (workspaceRolesReadRoleMenusResponse200) & {
  headers: Headers;
};
export type workspaceRolesReadRoleMenusResponseError = (workspaceRolesReadRoleMenusResponse422) & {
  headers: Headers;
};

export type workspaceRolesReadRoleMenusResponse = (workspaceRolesReadRoleMenusResponseSuccess | workspaceRolesReadRoleMenusResponseError)

export const getWorkspaceRolesReadRoleMenusUrl = (roleId: string,) => {




  return `/api/v1/workspace/roles/${roleId}/menus`
}

export const workspaceRolesReadRoleMenus = async (roleId: string, options?: RequestInit): Promise<workspaceRolesReadRoleMenusResponse> => {

  return customFetch<workspaceRolesReadRoleMenusResponse>(getWorkspaceRolesReadRoleMenusUrl(roleId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getWorkspaceRolesReadRoleMenusQueryKey = (roleId: string,) => {
    return [
    `/api/v1/workspace/roles/${roleId}/menus`
    ] as const;
    }


export const getWorkspaceRolesReadRoleMenusQueryOptions = <TData = Awaited<ReturnType<typeof workspaceRolesReadRoleMenus>>, TError = HTTPValidationError>(roleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoleMenus>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWorkspaceRolesReadRoleMenusQueryKey(roleId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof workspaceRolesReadRoleMenus>>> = ({ signal }) => workspaceRolesReadRoleMenus(roleId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(roleId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoleMenus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WorkspaceRolesReadRoleMenusQueryResult = NonNullable<Awaited<ReturnType<typeof workspaceRolesReadRoleMenus>>>
export type WorkspaceRolesReadRoleMenusQueryError = HTTPValidationError


export function useWorkspaceRolesReadRoleMenus<TData = Awaited<ReturnType<typeof workspaceRolesReadRoleMenus>>, TError = HTTPValidationError>(
 roleId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoleMenus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspaceRolesReadRoleMenus>>,
          TError,
          Awaited<ReturnType<typeof workspaceRolesReadRoleMenus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspaceRolesReadRoleMenus<TData = Awaited<ReturnType<typeof workspaceRolesReadRoleMenus>>, TError = HTTPValidationError>(
 roleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoleMenus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspaceRolesReadRoleMenus>>,
          TError,
          Awaited<ReturnType<typeof workspaceRolesReadRoleMenus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspaceRolesReadRoleMenus<TData = Awaited<ReturnType<typeof workspaceRolesReadRoleMenus>>, TError = HTTPValidationError>(
 roleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoleMenus>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Role Menus
 */

export function useWorkspaceRolesReadRoleMenus<TData = Awaited<ReturnType<typeof workspaceRolesReadRoleMenus>>, TError = HTTPValidationError>(
 roleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoleMenus>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWorkspaceRolesReadRoleMenusQueryOptions(roleId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Get workspace members currently assigned to a role.
 * @summary Read Role Members
 */
export type workspaceRolesReadRoleMembersResponse200 = {
  data: WorkspaceMemberPublic[]
  status: 200
}

export type workspaceRolesReadRoleMembersResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type workspaceRolesReadRoleMembersResponseSuccess = (workspaceRolesReadRoleMembersResponse200) & {
  headers: Headers;
};
export type workspaceRolesReadRoleMembersResponseError = (workspaceRolesReadRoleMembersResponse422) & {
  headers: Headers;
};

export type workspaceRolesReadRoleMembersResponse = (workspaceRolesReadRoleMembersResponseSuccess | workspaceRolesReadRoleMembersResponseError)

export const getWorkspaceRolesReadRoleMembersUrl = (roleId: string,) => {




  return `/api/v1/workspace/roles/${roleId}/members`
}

export const workspaceRolesReadRoleMembers = async (roleId: string, options?: RequestInit): Promise<workspaceRolesReadRoleMembersResponse> => {

  return customFetch<workspaceRolesReadRoleMembersResponse>(getWorkspaceRolesReadRoleMembersUrl(roleId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getWorkspaceRolesReadRoleMembersQueryKey = (roleId: string,) => {
    return [
    `/api/v1/workspace/roles/${roleId}/members`
    ] as const;
    }


export const getWorkspaceRolesReadRoleMembersQueryOptions = <TData = Awaited<ReturnType<typeof workspaceRolesReadRoleMembers>>, TError = HTTPValidationError>(roleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoleMembers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWorkspaceRolesReadRoleMembersQueryKey(roleId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof workspaceRolesReadRoleMembers>>> = ({ signal }) => workspaceRolesReadRoleMembers(roleId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(roleId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoleMembers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WorkspaceRolesReadRoleMembersQueryResult = NonNullable<Awaited<ReturnType<typeof workspaceRolesReadRoleMembers>>>
export type WorkspaceRolesReadRoleMembersQueryError = HTTPValidationError


export function useWorkspaceRolesReadRoleMembers<TData = Awaited<ReturnType<typeof workspaceRolesReadRoleMembers>>, TError = HTTPValidationError>(
 roleId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoleMembers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspaceRolesReadRoleMembers>>,
          TError,
          Awaited<ReturnType<typeof workspaceRolesReadRoleMembers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspaceRolesReadRoleMembers<TData = Awaited<ReturnType<typeof workspaceRolesReadRoleMembers>>, TError = HTTPValidationError>(
 roleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoleMembers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspaceRolesReadRoleMembers>>,
          TError,
          Awaited<ReturnType<typeof workspaceRolesReadRoleMembers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspaceRolesReadRoleMembers<TData = Awaited<ReturnType<typeof workspaceRolesReadRoleMembers>>, TError = HTTPValidationError>(
 roleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoleMembers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Role Members
 */

export function useWorkspaceRolesReadRoleMembers<TData = Awaited<ReturnType<typeof workspaceRolesReadRoleMembers>>, TError = HTTPValidationError>(
 roleId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceRolesReadRoleMembers>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWorkspaceRolesReadRoleMembersQueryOptions(roleId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
