/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Read Collection Tasks
 */
export const egoCollectionTasksReadCollectionTasksQuerySkipDefault = 0;
export const egoCollectionTasksReadCollectionTasksQuerySkipMin = 0;

export const egoCollectionTasksReadCollectionTasksQueryLimitDefault = 20;
export const egoCollectionTasksReadCollectionTasksQueryLimitMax = 500;

export const egoCollectionTasksReadCollectionTasksQueryQOneMax = 128;

export const egoCollectionTasksReadCollectionTasksQueryStatusOneMax = 32;



export const EgoCollectionTasksReadCollectionTasksQueryParams = zod.object({
  "skip": zod.number().min(egoCollectionTasksReadCollectionTasksQuerySkipMin).default(egoCollectionTasksReadCollectionTasksQuerySkipDefault),
  "limit": zod.number().min(1).max(egoCollectionTasksReadCollectionTasksQueryLimitMax).default(egoCollectionTasksReadCollectionTasksQueryLimitDefault),
  "q": zod.union([zod.string().max(egoCollectionTasksReadCollectionTasksQueryQOneMax),zod.null()]).optional(),
  "status": zod.union([zod.string().max(egoCollectionTasksReadCollectionTasksQueryStatusOneMax),zod.null()]).optional()
})

export const EgoCollectionTasksReadCollectionTasksHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoCollectionTasksReadCollectionTasksResponseDataItemTaskNoDefault = ``;
export const egoCollectionTasksReadCollectionTasksResponseDataItemTaskNoMax = 64;

export const egoCollectionTasksReadCollectionTasksResponseDataItemProjectNameMax = 128;

export const egoCollectionTasksReadCollectionTasksResponseDataItemNameMax = 128;

export const egoCollectionTasksReadCollectionTasksResponseDataItemSubtaskNameDefault = ``;
export const egoCollectionTasksReadCollectionTasksResponseDataItemSubtaskNameMax = 128;

export const egoCollectionTasksReadCollectionTasksResponseDataItemSceneTypeDefault = `室内`;
export const egoCollectionTasksReadCollectionTasksResponseDataItemSceneTypeMax = 64;

export const egoCollectionTasksReadCollectionTasksResponseDataItemAssignedUsernameDefault = ``;
export const egoCollectionTasksReadCollectionTasksResponseDataItemAssignedUsernameMax = 128;

export const egoCollectionTasksReadCollectionTasksResponseDataItemDeviceSerialDefault = ``;
export const egoCollectionTasksReadCollectionTasksResponseDataItemDeviceSerialMax = 128;

export const egoCollectionTasksReadCollectionTasksResponseDataItemLocationDefault = ``;
export const egoCollectionTasksReadCollectionTasksResponseDataItemLocationMax = 256;

export const egoCollectionTasksReadCollectionTasksResponseDataItemTargetObjectsDefault = ``;
export const egoCollectionTasksReadCollectionTasksResponseDataItemTargetObjectsMax = 1000;

export const egoCollectionTasksReadCollectionTasksResponseDataItemObjectCountDefault = 0;
export const egoCollectionTasksReadCollectionTasksResponseDataItemObjectCountMin = 0;

export const egoCollectionTasksReadCollectionTasksResponseDataItemDurationMinutesDefault = 30;
export const egoCollectionTasksReadCollectionTasksResponseDataItemDurationMinutesMin = 0;

export const egoCollectionTasksReadCollectionTasksResponseDataItemTargetCountDefault = 1;
export const egoCollectionTasksReadCollectionTasksResponseDataItemTargetCountMin = 0;

export const egoCollectionTasksReadCollectionTasksResponseDataItemCompletedCountDefault = 0;
export const egoCollectionTasksReadCollectionTasksResponseDataItemCompletedCountMin = 0;

export const egoCollectionTasksReadCollectionTasksResponseDataItemStatusDefault = `PENDING`;
export const egoCollectionTasksReadCollectionTasksResponseDataItemStatusMax = 32;

export const egoCollectionTasksReadCollectionTasksResponseDataItemKitNameDefault = ``;
export const egoCollectionTasksReadCollectionTasksResponseDataItemSopNameDefault = ``;
export const egoCollectionTasksReadCollectionTasksResponseDataItemSopContentDefault = ``;

export const EgoCollectionTasksReadCollectionTasksResponse = zod.object({
  "count": zod.number(),
  "data": zod.array(zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "task_no": zod.string().max(egoCollectionTasksReadCollectionTasksResponseDataItemTaskNoMax).default(egoCollectionTasksReadCollectionTasksResponseDataItemTaskNoDefault),
  "project_name": zod.string().min(1).max(egoCollectionTasksReadCollectionTasksResponseDataItemProjectNameMax),
  "name": zod.string().min(1).max(egoCollectionTasksReadCollectionTasksResponseDataItemNameMax),
  "subtask_name": zod.string().max(egoCollectionTasksReadCollectionTasksResponseDataItemSubtaskNameMax).default(egoCollectionTasksReadCollectionTasksResponseDataItemSubtaskNameDefault),
  "scene_type": zod.string().max(egoCollectionTasksReadCollectionTasksResponseDataItemSceneTypeMax).default(egoCollectionTasksReadCollectionTasksResponseDataItemSceneTypeDefault),
  "kit_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "sop_id": zod.uuid(),
  "assigned_username": zod.string().max(egoCollectionTasksReadCollectionTasksResponseDataItemAssignedUsernameMax).default(egoCollectionTasksReadCollectionTasksResponseDataItemAssignedUsernameDefault),
  "device_serial": zod.string().max(egoCollectionTasksReadCollectionTasksResponseDataItemDeviceSerialMax).default(egoCollectionTasksReadCollectionTasksResponseDataItemDeviceSerialDefault),
  "location": zod.string().max(egoCollectionTasksReadCollectionTasksResponseDataItemLocationMax).default(egoCollectionTasksReadCollectionTasksResponseDataItemLocationDefault),
  "target_objects": zod.string().max(egoCollectionTasksReadCollectionTasksResponseDataItemTargetObjectsMax).default(egoCollectionTasksReadCollectionTasksResponseDataItemTargetObjectsDefault),
  "object_count": zod.number().min(egoCollectionTasksReadCollectionTasksResponseDataItemObjectCountMin).default(egoCollectionTasksReadCollectionTasksResponseDataItemObjectCountDefault),
  "duration_minutes": zod.number().min(egoCollectionTasksReadCollectionTasksResponseDataItemDurationMinutesMin).default(egoCollectionTasksReadCollectionTasksResponseDataItemDurationMinutesDefault),
  "target_count": zod.number().min(egoCollectionTasksReadCollectionTasksResponseDataItemTargetCountMin).default(egoCollectionTasksReadCollectionTasksResponseDataItemTargetCountDefault),
  "completed_count": zod.number().min(egoCollectionTasksReadCollectionTasksResponseDataItemCompletedCountMin).default(egoCollectionTasksReadCollectionTasksResponseDataItemCompletedCountDefault),
  "published_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "status": zod.string().max(egoCollectionTasksReadCollectionTasksResponseDataItemStatusMax).default(egoCollectionTasksReadCollectionTasksResponseDataItemStatusDefault),
  "workspace_id": zod.uuid(),
  "kit_name": zod.string().default(egoCollectionTasksReadCollectionTasksResponseDataItemKitNameDefault),
  "sop_name": zod.string().default(egoCollectionTasksReadCollectionTasksResponseDataItemSopNameDefault),
  "sop_content": zod.string().default(egoCollectionTasksReadCollectionTasksResponseDataItemSopContentDefault),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
}))
})

/**
 * @summary Create Collection Task
 */
export const EgoCollectionTasksCreateCollectionTaskHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoCollectionTasksCreateCollectionTaskBodyTaskNoDefault = ``;
export const egoCollectionTasksCreateCollectionTaskBodyTaskNoMax = 64;

export const egoCollectionTasksCreateCollectionTaskBodyProjectNameMax = 128;

export const egoCollectionTasksCreateCollectionTaskBodyNameMax = 128;

export const egoCollectionTasksCreateCollectionTaskBodySubtaskNameDefault = ``;
export const egoCollectionTasksCreateCollectionTaskBodySubtaskNameMax = 128;

export const egoCollectionTasksCreateCollectionTaskBodySceneTypeDefault = `室内`;
export const egoCollectionTasksCreateCollectionTaskBodySceneTypeMax = 64;

export const egoCollectionTasksCreateCollectionTaskBodyAssignedUsernameDefault = ``;
export const egoCollectionTasksCreateCollectionTaskBodyAssignedUsernameMax = 128;

export const egoCollectionTasksCreateCollectionTaskBodyDeviceSerialDefault = ``;
export const egoCollectionTasksCreateCollectionTaskBodyDeviceSerialMax = 128;

export const egoCollectionTasksCreateCollectionTaskBodyLocationDefault = ``;
export const egoCollectionTasksCreateCollectionTaskBodyLocationMax = 256;

export const egoCollectionTasksCreateCollectionTaskBodyTargetObjectsDefault = ``;
export const egoCollectionTasksCreateCollectionTaskBodyTargetObjectsMax = 1000;

export const egoCollectionTasksCreateCollectionTaskBodyObjectCountDefault = 0;
export const egoCollectionTasksCreateCollectionTaskBodyObjectCountMin = 0;

export const egoCollectionTasksCreateCollectionTaskBodyDurationMinutesDefault = 30;
export const egoCollectionTasksCreateCollectionTaskBodyDurationMinutesMin = 0;

export const egoCollectionTasksCreateCollectionTaskBodyTargetCountDefault = 1;
export const egoCollectionTasksCreateCollectionTaskBodyTargetCountMin = 0;

export const egoCollectionTasksCreateCollectionTaskBodyCompletedCountDefault = 0;
export const egoCollectionTasksCreateCollectionTaskBodyCompletedCountMin = 0;

export const egoCollectionTasksCreateCollectionTaskBodyStatusDefault = `PENDING`;
export const egoCollectionTasksCreateCollectionTaskBodyStatusMax = 32;



export const EgoCollectionTasksCreateCollectionTaskBody = zod.object({
  "task_no": zod.string().max(egoCollectionTasksCreateCollectionTaskBodyTaskNoMax).default(egoCollectionTasksCreateCollectionTaskBodyTaskNoDefault),
  "project_name": zod.string().min(1).max(egoCollectionTasksCreateCollectionTaskBodyProjectNameMax),
  "name": zod.string().min(1).max(egoCollectionTasksCreateCollectionTaskBodyNameMax),
  "subtask_name": zod.string().max(egoCollectionTasksCreateCollectionTaskBodySubtaskNameMax).default(egoCollectionTasksCreateCollectionTaskBodySubtaskNameDefault),
  "scene_type": zod.string().max(egoCollectionTasksCreateCollectionTaskBodySceneTypeMax).default(egoCollectionTasksCreateCollectionTaskBodySceneTypeDefault),
  "kit_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "sop_id": zod.uuid(),
  "assigned_username": zod.string().max(egoCollectionTasksCreateCollectionTaskBodyAssignedUsernameMax).default(egoCollectionTasksCreateCollectionTaskBodyAssignedUsernameDefault),
  "device_serial": zod.string().max(egoCollectionTasksCreateCollectionTaskBodyDeviceSerialMax).default(egoCollectionTasksCreateCollectionTaskBodyDeviceSerialDefault),
  "location": zod.string().max(egoCollectionTasksCreateCollectionTaskBodyLocationMax).default(egoCollectionTasksCreateCollectionTaskBodyLocationDefault),
  "target_objects": zod.string().max(egoCollectionTasksCreateCollectionTaskBodyTargetObjectsMax).default(egoCollectionTasksCreateCollectionTaskBodyTargetObjectsDefault),
  "object_count": zod.number().min(egoCollectionTasksCreateCollectionTaskBodyObjectCountMin).default(egoCollectionTasksCreateCollectionTaskBodyObjectCountDefault),
  "duration_minutes": zod.number().min(egoCollectionTasksCreateCollectionTaskBodyDurationMinutesMin).default(egoCollectionTasksCreateCollectionTaskBodyDurationMinutesDefault),
  "target_count": zod.number().min(egoCollectionTasksCreateCollectionTaskBodyTargetCountMin).default(egoCollectionTasksCreateCollectionTaskBodyTargetCountDefault),
  "completed_count": zod.number().min(egoCollectionTasksCreateCollectionTaskBodyCompletedCountMin).default(egoCollectionTasksCreateCollectionTaskBodyCompletedCountDefault),
  "published_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "status": zod.string().max(egoCollectionTasksCreateCollectionTaskBodyStatusMax).default(egoCollectionTasksCreateCollectionTaskBodyStatusDefault)
})

export const egoCollectionTasksCreateCollectionTaskResponseTaskNoDefault = ``;
export const egoCollectionTasksCreateCollectionTaskResponseTaskNoMax = 64;

export const egoCollectionTasksCreateCollectionTaskResponseProjectNameMax = 128;

export const egoCollectionTasksCreateCollectionTaskResponseNameMax = 128;

export const egoCollectionTasksCreateCollectionTaskResponseSubtaskNameDefault = ``;
export const egoCollectionTasksCreateCollectionTaskResponseSubtaskNameMax = 128;

export const egoCollectionTasksCreateCollectionTaskResponseSceneTypeDefault = `室内`;
export const egoCollectionTasksCreateCollectionTaskResponseSceneTypeMax = 64;

export const egoCollectionTasksCreateCollectionTaskResponseAssignedUsernameDefault = ``;
export const egoCollectionTasksCreateCollectionTaskResponseAssignedUsernameMax = 128;

export const egoCollectionTasksCreateCollectionTaskResponseDeviceSerialDefault = ``;
export const egoCollectionTasksCreateCollectionTaskResponseDeviceSerialMax = 128;

export const egoCollectionTasksCreateCollectionTaskResponseLocationDefault = ``;
export const egoCollectionTasksCreateCollectionTaskResponseLocationMax = 256;

export const egoCollectionTasksCreateCollectionTaskResponseTargetObjectsDefault = ``;
export const egoCollectionTasksCreateCollectionTaskResponseTargetObjectsMax = 1000;

export const egoCollectionTasksCreateCollectionTaskResponseObjectCountDefault = 0;
export const egoCollectionTasksCreateCollectionTaskResponseObjectCountMin = 0;

export const egoCollectionTasksCreateCollectionTaskResponseDurationMinutesDefault = 30;
export const egoCollectionTasksCreateCollectionTaskResponseDurationMinutesMin = 0;

export const egoCollectionTasksCreateCollectionTaskResponseTargetCountDefault = 1;
export const egoCollectionTasksCreateCollectionTaskResponseTargetCountMin = 0;

export const egoCollectionTasksCreateCollectionTaskResponseCompletedCountDefault = 0;
export const egoCollectionTasksCreateCollectionTaskResponseCompletedCountMin = 0;

export const egoCollectionTasksCreateCollectionTaskResponseStatusDefault = `PENDING`;
export const egoCollectionTasksCreateCollectionTaskResponseStatusMax = 32;

export const egoCollectionTasksCreateCollectionTaskResponseKitNameDefault = ``;
export const egoCollectionTasksCreateCollectionTaskResponseSopNameDefault = ``;
export const egoCollectionTasksCreateCollectionTaskResponseSopContentDefault = ``;

export const EgoCollectionTasksCreateCollectionTaskResponse = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "task_no": zod.string().max(egoCollectionTasksCreateCollectionTaskResponseTaskNoMax).default(egoCollectionTasksCreateCollectionTaskResponseTaskNoDefault),
  "project_name": zod.string().min(1).max(egoCollectionTasksCreateCollectionTaskResponseProjectNameMax),
  "name": zod.string().min(1).max(egoCollectionTasksCreateCollectionTaskResponseNameMax),
  "subtask_name": zod.string().max(egoCollectionTasksCreateCollectionTaskResponseSubtaskNameMax).default(egoCollectionTasksCreateCollectionTaskResponseSubtaskNameDefault),
  "scene_type": zod.string().max(egoCollectionTasksCreateCollectionTaskResponseSceneTypeMax).default(egoCollectionTasksCreateCollectionTaskResponseSceneTypeDefault),
  "kit_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "sop_id": zod.uuid(),
  "assigned_username": zod.string().max(egoCollectionTasksCreateCollectionTaskResponseAssignedUsernameMax).default(egoCollectionTasksCreateCollectionTaskResponseAssignedUsernameDefault),
  "device_serial": zod.string().max(egoCollectionTasksCreateCollectionTaskResponseDeviceSerialMax).default(egoCollectionTasksCreateCollectionTaskResponseDeviceSerialDefault),
  "location": zod.string().max(egoCollectionTasksCreateCollectionTaskResponseLocationMax).default(egoCollectionTasksCreateCollectionTaskResponseLocationDefault),
  "target_objects": zod.string().max(egoCollectionTasksCreateCollectionTaskResponseTargetObjectsMax).default(egoCollectionTasksCreateCollectionTaskResponseTargetObjectsDefault),
  "object_count": zod.number().min(egoCollectionTasksCreateCollectionTaskResponseObjectCountMin).default(egoCollectionTasksCreateCollectionTaskResponseObjectCountDefault),
  "duration_minutes": zod.number().min(egoCollectionTasksCreateCollectionTaskResponseDurationMinutesMin).default(egoCollectionTasksCreateCollectionTaskResponseDurationMinutesDefault),
  "target_count": zod.number().min(egoCollectionTasksCreateCollectionTaskResponseTargetCountMin).default(egoCollectionTasksCreateCollectionTaskResponseTargetCountDefault),
  "completed_count": zod.number().min(egoCollectionTasksCreateCollectionTaskResponseCompletedCountMin).default(egoCollectionTasksCreateCollectionTaskResponseCompletedCountDefault),
  "published_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "status": zod.string().max(egoCollectionTasksCreateCollectionTaskResponseStatusMax).default(egoCollectionTasksCreateCollectionTaskResponseStatusDefault),
  "workspace_id": zod.uuid(),
  "kit_name": zod.string().default(egoCollectionTasksCreateCollectionTaskResponseKitNameDefault),
  "sop_name": zod.string().default(egoCollectionTasksCreateCollectionTaskResponseSopNameDefault),
  "sop_content": zod.string().default(egoCollectionTasksCreateCollectionTaskResponseSopContentDefault),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * @summary Read My Current Task
 */
export const EgoCollectionTasksReadMyCurrentTaskHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoCollectionTasksReadMyCurrentTaskResponseOneTaskNoDefault = ``;
export const egoCollectionTasksReadMyCurrentTaskResponseOneTaskNoMax = 64;

export const egoCollectionTasksReadMyCurrentTaskResponseOneProjectNameMax = 128;

export const egoCollectionTasksReadMyCurrentTaskResponseOneNameMax = 128;

export const egoCollectionTasksReadMyCurrentTaskResponseOneSubtaskNameDefault = ``;
export const egoCollectionTasksReadMyCurrentTaskResponseOneSubtaskNameMax = 128;

export const egoCollectionTasksReadMyCurrentTaskResponseOneSceneTypeDefault = `室内`;
export const egoCollectionTasksReadMyCurrentTaskResponseOneSceneTypeMax = 64;

export const egoCollectionTasksReadMyCurrentTaskResponseOneAssignedUsernameDefault = ``;
export const egoCollectionTasksReadMyCurrentTaskResponseOneAssignedUsernameMax = 128;

export const egoCollectionTasksReadMyCurrentTaskResponseOneDeviceSerialDefault = ``;
export const egoCollectionTasksReadMyCurrentTaskResponseOneDeviceSerialMax = 128;

export const egoCollectionTasksReadMyCurrentTaskResponseOneLocationDefault = ``;
export const egoCollectionTasksReadMyCurrentTaskResponseOneLocationMax = 256;

export const egoCollectionTasksReadMyCurrentTaskResponseOneTargetObjectsDefault = ``;
export const egoCollectionTasksReadMyCurrentTaskResponseOneTargetObjectsMax = 1000;

export const egoCollectionTasksReadMyCurrentTaskResponseOneObjectCountDefault = 0;
export const egoCollectionTasksReadMyCurrentTaskResponseOneObjectCountMin = 0;

export const egoCollectionTasksReadMyCurrentTaskResponseOneDurationMinutesDefault = 30;
export const egoCollectionTasksReadMyCurrentTaskResponseOneDurationMinutesMin = 0;

export const egoCollectionTasksReadMyCurrentTaskResponseOneTargetCountDefault = 1;
export const egoCollectionTasksReadMyCurrentTaskResponseOneTargetCountMin = 0;

export const egoCollectionTasksReadMyCurrentTaskResponseOneCompletedCountDefault = 0;
export const egoCollectionTasksReadMyCurrentTaskResponseOneCompletedCountMin = 0;

export const egoCollectionTasksReadMyCurrentTaskResponseOneStatusDefault = `PENDING`;
export const egoCollectionTasksReadMyCurrentTaskResponseOneStatusMax = 32;

export const egoCollectionTasksReadMyCurrentTaskResponseOneKitNameDefault = ``;
export const egoCollectionTasksReadMyCurrentTaskResponseOneSopNameDefault = ``;
export const egoCollectionTasksReadMyCurrentTaskResponseOneSopContentDefault = ``;

export const EgoCollectionTasksReadMyCurrentTaskResponse = zod.union([zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "task_no": zod.string().max(egoCollectionTasksReadMyCurrentTaskResponseOneTaskNoMax).default(egoCollectionTasksReadMyCurrentTaskResponseOneTaskNoDefault),
  "project_name": zod.string().min(1).max(egoCollectionTasksReadMyCurrentTaskResponseOneProjectNameMax),
  "name": zod.string().min(1).max(egoCollectionTasksReadMyCurrentTaskResponseOneNameMax),
  "subtask_name": zod.string().max(egoCollectionTasksReadMyCurrentTaskResponseOneSubtaskNameMax).default(egoCollectionTasksReadMyCurrentTaskResponseOneSubtaskNameDefault),
  "scene_type": zod.string().max(egoCollectionTasksReadMyCurrentTaskResponseOneSceneTypeMax).default(egoCollectionTasksReadMyCurrentTaskResponseOneSceneTypeDefault),
  "kit_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "sop_id": zod.uuid(),
  "assigned_username": zod.string().max(egoCollectionTasksReadMyCurrentTaskResponseOneAssignedUsernameMax).default(egoCollectionTasksReadMyCurrentTaskResponseOneAssignedUsernameDefault),
  "device_serial": zod.string().max(egoCollectionTasksReadMyCurrentTaskResponseOneDeviceSerialMax).default(egoCollectionTasksReadMyCurrentTaskResponseOneDeviceSerialDefault),
  "location": zod.string().max(egoCollectionTasksReadMyCurrentTaskResponseOneLocationMax).default(egoCollectionTasksReadMyCurrentTaskResponseOneLocationDefault),
  "target_objects": zod.string().max(egoCollectionTasksReadMyCurrentTaskResponseOneTargetObjectsMax).default(egoCollectionTasksReadMyCurrentTaskResponseOneTargetObjectsDefault),
  "object_count": zod.number().min(egoCollectionTasksReadMyCurrentTaskResponseOneObjectCountMin).default(egoCollectionTasksReadMyCurrentTaskResponseOneObjectCountDefault),
  "duration_minutes": zod.number().min(egoCollectionTasksReadMyCurrentTaskResponseOneDurationMinutesMin).default(egoCollectionTasksReadMyCurrentTaskResponseOneDurationMinutesDefault),
  "target_count": zod.number().min(egoCollectionTasksReadMyCurrentTaskResponseOneTargetCountMin).default(egoCollectionTasksReadMyCurrentTaskResponseOneTargetCountDefault),
  "completed_count": zod.number().min(egoCollectionTasksReadMyCurrentTaskResponseOneCompletedCountMin).default(egoCollectionTasksReadMyCurrentTaskResponseOneCompletedCountDefault),
  "published_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "status": zod.string().max(egoCollectionTasksReadMyCurrentTaskResponseOneStatusMax).default(egoCollectionTasksReadMyCurrentTaskResponseOneStatusDefault),
  "workspace_id": zod.uuid(),
  "kit_name": zod.string().default(egoCollectionTasksReadMyCurrentTaskResponseOneKitNameDefault),
  "sop_name": zod.string().default(egoCollectionTasksReadMyCurrentTaskResponseOneSopNameDefault),
  "sop_content": zod.string().default(egoCollectionTasksReadMyCurrentTaskResponseOneSopContentDefault),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
}),zod.null()])

/**
 * @summary Read My Available Tasks
 */
export const egoCollectionTasksReadMyAvailableTasksQueryLimitDefault = 100;
export const egoCollectionTasksReadMyAvailableTasksQueryLimitMax = 500;

export const egoCollectionTasksReadMyAvailableTasksQueryQOneMax = 128;

export const egoCollectionTasksReadMyAvailableTasksQuerySceneTypeOneMax = 64;

export const egoCollectionTasksReadMyAvailableTasksQueryTaskNoOneMax = 64;



export const EgoCollectionTasksReadMyAvailableTasksQueryParams = zod.object({
  "limit": zod.number().min(1).max(egoCollectionTasksReadMyAvailableTasksQueryLimitMax).default(egoCollectionTasksReadMyAvailableTasksQueryLimitDefault),
  "q": zod.union([zod.string().max(egoCollectionTasksReadMyAvailableTasksQueryQOneMax),zod.null()]).optional(),
  "scene_type": zod.union([zod.string().max(egoCollectionTasksReadMyAvailableTasksQuerySceneTypeOneMax),zod.null()]).optional(),
  "task_no": zod.union([zod.string().max(egoCollectionTasksReadMyAvailableTasksQueryTaskNoOneMax),zod.null()]).optional()
})

export const EgoCollectionTasksReadMyAvailableTasksHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoCollectionTasksReadMyAvailableTasksResponseTaskNoDefault = ``;
export const egoCollectionTasksReadMyAvailableTasksResponseTaskNoMax = 64;

export const egoCollectionTasksReadMyAvailableTasksResponseProjectNameMax = 128;

export const egoCollectionTasksReadMyAvailableTasksResponseNameMax = 128;

export const egoCollectionTasksReadMyAvailableTasksResponseSubtaskNameDefault = ``;
export const egoCollectionTasksReadMyAvailableTasksResponseSubtaskNameMax = 128;

export const egoCollectionTasksReadMyAvailableTasksResponseSceneTypeDefault = `室内`;
export const egoCollectionTasksReadMyAvailableTasksResponseSceneTypeMax = 64;

export const egoCollectionTasksReadMyAvailableTasksResponseAssignedUsernameDefault = ``;
export const egoCollectionTasksReadMyAvailableTasksResponseAssignedUsernameMax = 128;

export const egoCollectionTasksReadMyAvailableTasksResponseDeviceSerialDefault = ``;
export const egoCollectionTasksReadMyAvailableTasksResponseDeviceSerialMax = 128;

export const egoCollectionTasksReadMyAvailableTasksResponseLocationDefault = ``;
export const egoCollectionTasksReadMyAvailableTasksResponseLocationMax = 256;

export const egoCollectionTasksReadMyAvailableTasksResponseTargetObjectsDefault = ``;
export const egoCollectionTasksReadMyAvailableTasksResponseTargetObjectsMax = 1000;

export const egoCollectionTasksReadMyAvailableTasksResponseObjectCountDefault = 0;
export const egoCollectionTasksReadMyAvailableTasksResponseObjectCountMin = 0;

export const egoCollectionTasksReadMyAvailableTasksResponseDurationMinutesDefault = 30;
export const egoCollectionTasksReadMyAvailableTasksResponseDurationMinutesMin = 0;

export const egoCollectionTasksReadMyAvailableTasksResponseTargetCountDefault = 1;
export const egoCollectionTasksReadMyAvailableTasksResponseTargetCountMin = 0;

export const egoCollectionTasksReadMyAvailableTasksResponseCompletedCountDefault = 0;
export const egoCollectionTasksReadMyAvailableTasksResponseCompletedCountMin = 0;

export const egoCollectionTasksReadMyAvailableTasksResponseStatusDefault = `PENDING`;
export const egoCollectionTasksReadMyAvailableTasksResponseStatusMax = 32;

export const egoCollectionTasksReadMyAvailableTasksResponseKitNameDefault = ``;
export const egoCollectionTasksReadMyAvailableTasksResponseSopNameDefault = ``;
export const egoCollectionTasksReadMyAvailableTasksResponseSopContentDefault = ``;

export const EgoCollectionTasksReadMyAvailableTasksResponseItem = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "task_no": zod.string().max(egoCollectionTasksReadMyAvailableTasksResponseTaskNoMax).default(egoCollectionTasksReadMyAvailableTasksResponseTaskNoDefault),
  "project_name": zod.string().min(1).max(egoCollectionTasksReadMyAvailableTasksResponseProjectNameMax),
  "name": zod.string().min(1).max(egoCollectionTasksReadMyAvailableTasksResponseNameMax),
  "subtask_name": zod.string().max(egoCollectionTasksReadMyAvailableTasksResponseSubtaskNameMax).default(egoCollectionTasksReadMyAvailableTasksResponseSubtaskNameDefault),
  "scene_type": zod.string().max(egoCollectionTasksReadMyAvailableTasksResponseSceneTypeMax).default(egoCollectionTasksReadMyAvailableTasksResponseSceneTypeDefault),
  "kit_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "sop_id": zod.uuid(),
  "assigned_username": zod.string().max(egoCollectionTasksReadMyAvailableTasksResponseAssignedUsernameMax).default(egoCollectionTasksReadMyAvailableTasksResponseAssignedUsernameDefault),
  "device_serial": zod.string().max(egoCollectionTasksReadMyAvailableTasksResponseDeviceSerialMax).default(egoCollectionTasksReadMyAvailableTasksResponseDeviceSerialDefault),
  "location": zod.string().max(egoCollectionTasksReadMyAvailableTasksResponseLocationMax).default(egoCollectionTasksReadMyAvailableTasksResponseLocationDefault),
  "target_objects": zod.string().max(egoCollectionTasksReadMyAvailableTasksResponseTargetObjectsMax).default(egoCollectionTasksReadMyAvailableTasksResponseTargetObjectsDefault),
  "object_count": zod.number().min(egoCollectionTasksReadMyAvailableTasksResponseObjectCountMin).default(egoCollectionTasksReadMyAvailableTasksResponseObjectCountDefault),
  "duration_minutes": zod.number().min(egoCollectionTasksReadMyAvailableTasksResponseDurationMinutesMin).default(egoCollectionTasksReadMyAvailableTasksResponseDurationMinutesDefault),
  "target_count": zod.number().min(egoCollectionTasksReadMyAvailableTasksResponseTargetCountMin).default(egoCollectionTasksReadMyAvailableTasksResponseTargetCountDefault),
  "completed_count": zod.number().min(egoCollectionTasksReadMyAvailableTasksResponseCompletedCountMin).default(egoCollectionTasksReadMyAvailableTasksResponseCompletedCountDefault),
  "published_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "status": zod.string().max(egoCollectionTasksReadMyAvailableTasksResponseStatusMax).default(egoCollectionTasksReadMyAvailableTasksResponseStatusDefault),
  "workspace_id": zod.uuid(),
  "kit_name": zod.string().default(egoCollectionTasksReadMyAvailableTasksResponseKitNameDefault),
  "sop_name": zod.string().default(egoCollectionTasksReadMyAvailableTasksResponseSopNameDefault),
  "sop_content": zod.string().default(egoCollectionTasksReadMyAvailableTasksResponseSopContentDefault),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})
export const EgoCollectionTasksReadMyAvailableTasksResponse = zod.array(EgoCollectionTasksReadMyAvailableTasksResponseItem)

/**
 * @summary Update Collection Task
 */
export const EgoCollectionTasksUpdateCollectionTaskParams = zod.object({
  "resource_id": zod.uuid()
})

export const EgoCollectionTasksUpdateCollectionTaskHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoCollectionTasksUpdateCollectionTaskBodyTaskNoDefault = ``;
export const egoCollectionTasksUpdateCollectionTaskBodyTaskNoMax = 64;

export const egoCollectionTasksUpdateCollectionTaskBodyProjectNameMax = 128;

export const egoCollectionTasksUpdateCollectionTaskBodyNameMax = 128;

export const egoCollectionTasksUpdateCollectionTaskBodySubtaskNameDefault = ``;
export const egoCollectionTasksUpdateCollectionTaskBodySubtaskNameMax = 128;

export const egoCollectionTasksUpdateCollectionTaskBodySceneTypeDefault = `室内`;
export const egoCollectionTasksUpdateCollectionTaskBodySceneTypeMax = 64;

export const egoCollectionTasksUpdateCollectionTaskBodyAssignedUsernameDefault = ``;
export const egoCollectionTasksUpdateCollectionTaskBodyAssignedUsernameMax = 128;

export const egoCollectionTasksUpdateCollectionTaskBodyDeviceSerialDefault = ``;
export const egoCollectionTasksUpdateCollectionTaskBodyDeviceSerialMax = 128;

export const egoCollectionTasksUpdateCollectionTaskBodyLocationDefault = ``;
export const egoCollectionTasksUpdateCollectionTaskBodyLocationMax = 256;

export const egoCollectionTasksUpdateCollectionTaskBodyTargetObjectsDefault = ``;
export const egoCollectionTasksUpdateCollectionTaskBodyTargetObjectsMax = 1000;

export const egoCollectionTasksUpdateCollectionTaskBodyObjectCountDefault = 0;
export const egoCollectionTasksUpdateCollectionTaskBodyObjectCountMin = 0;

export const egoCollectionTasksUpdateCollectionTaskBodyDurationMinutesDefault = 30;
export const egoCollectionTasksUpdateCollectionTaskBodyDurationMinutesMin = 0;

export const egoCollectionTasksUpdateCollectionTaskBodyTargetCountDefault = 1;
export const egoCollectionTasksUpdateCollectionTaskBodyTargetCountMin = 0;

export const egoCollectionTasksUpdateCollectionTaskBodyCompletedCountDefault = 0;
export const egoCollectionTasksUpdateCollectionTaskBodyCompletedCountMin = 0;

export const egoCollectionTasksUpdateCollectionTaskBodyStatusDefault = `PENDING`;
export const egoCollectionTasksUpdateCollectionTaskBodyStatusMax = 32;



export const EgoCollectionTasksUpdateCollectionTaskBody = zod.object({
  "task_no": zod.string().max(egoCollectionTasksUpdateCollectionTaskBodyTaskNoMax).default(egoCollectionTasksUpdateCollectionTaskBodyTaskNoDefault),
  "project_name": zod.string().min(1).max(egoCollectionTasksUpdateCollectionTaskBodyProjectNameMax),
  "name": zod.string().min(1).max(egoCollectionTasksUpdateCollectionTaskBodyNameMax),
  "subtask_name": zod.string().max(egoCollectionTasksUpdateCollectionTaskBodySubtaskNameMax).default(egoCollectionTasksUpdateCollectionTaskBodySubtaskNameDefault),
  "scene_type": zod.string().max(egoCollectionTasksUpdateCollectionTaskBodySceneTypeMax).default(egoCollectionTasksUpdateCollectionTaskBodySceneTypeDefault),
  "kit_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "sop_id": zod.uuid(),
  "assigned_username": zod.string().max(egoCollectionTasksUpdateCollectionTaskBodyAssignedUsernameMax).default(egoCollectionTasksUpdateCollectionTaskBodyAssignedUsernameDefault),
  "device_serial": zod.string().max(egoCollectionTasksUpdateCollectionTaskBodyDeviceSerialMax).default(egoCollectionTasksUpdateCollectionTaskBodyDeviceSerialDefault),
  "location": zod.string().max(egoCollectionTasksUpdateCollectionTaskBodyLocationMax).default(egoCollectionTasksUpdateCollectionTaskBodyLocationDefault),
  "target_objects": zod.string().max(egoCollectionTasksUpdateCollectionTaskBodyTargetObjectsMax).default(egoCollectionTasksUpdateCollectionTaskBodyTargetObjectsDefault),
  "object_count": zod.number().min(egoCollectionTasksUpdateCollectionTaskBodyObjectCountMin).default(egoCollectionTasksUpdateCollectionTaskBodyObjectCountDefault),
  "duration_minutes": zod.number().min(egoCollectionTasksUpdateCollectionTaskBodyDurationMinutesMin).default(egoCollectionTasksUpdateCollectionTaskBodyDurationMinutesDefault),
  "target_count": zod.number().min(egoCollectionTasksUpdateCollectionTaskBodyTargetCountMin).default(egoCollectionTasksUpdateCollectionTaskBodyTargetCountDefault),
  "completed_count": zod.number().min(egoCollectionTasksUpdateCollectionTaskBodyCompletedCountMin).default(egoCollectionTasksUpdateCollectionTaskBodyCompletedCountDefault),
  "published_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "status": zod.string().max(egoCollectionTasksUpdateCollectionTaskBodyStatusMax).default(egoCollectionTasksUpdateCollectionTaskBodyStatusDefault)
})

export const egoCollectionTasksUpdateCollectionTaskResponseTaskNoDefault = ``;
export const egoCollectionTasksUpdateCollectionTaskResponseTaskNoMax = 64;

export const egoCollectionTasksUpdateCollectionTaskResponseProjectNameMax = 128;

export const egoCollectionTasksUpdateCollectionTaskResponseNameMax = 128;

export const egoCollectionTasksUpdateCollectionTaskResponseSubtaskNameDefault = ``;
export const egoCollectionTasksUpdateCollectionTaskResponseSubtaskNameMax = 128;

export const egoCollectionTasksUpdateCollectionTaskResponseSceneTypeDefault = `室内`;
export const egoCollectionTasksUpdateCollectionTaskResponseSceneTypeMax = 64;

export const egoCollectionTasksUpdateCollectionTaskResponseAssignedUsernameDefault = ``;
export const egoCollectionTasksUpdateCollectionTaskResponseAssignedUsernameMax = 128;

export const egoCollectionTasksUpdateCollectionTaskResponseDeviceSerialDefault = ``;
export const egoCollectionTasksUpdateCollectionTaskResponseDeviceSerialMax = 128;

export const egoCollectionTasksUpdateCollectionTaskResponseLocationDefault = ``;
export const egoCollectionTasksUpdateCollectionTaskResponseLocationMax = 256;

export const egoCollectionTasksUpdateCollectionTaskResponseTargetObjectsDefault = ``;
export const egoCollectionTasksUpdateCollectionTaskResponseTargetObjectsMax = 1000;

export const egoCollectionTasksUpdateCollectionTaskResponseObjectCountDefault = 0;
export const egoCollectionTasksUpdateCollectionTaskResponseObjectCountMin = 0;

export const egoCollectionTasksUpdateCollectionTaskResponseDurationMinutesDefault = 30;
export const egoCollectionTasksUpdateCollectionTaskResponseDurationMinutesMin = 0;

export const egoCollectionTasksUpdateCollectionTaskResponseTargetCountDefault = 1;
export const egoCollectionTasksUpdateCollectionTaskResponseTargetCountMin = 0;

export const egoCollectionTasksUpdateCollectionTaskResponseCompletedCountDefault = 0;
export const egoCollectionTasksUpdateCollectionTaskResponseCompletedCountMin = 0;

export const egoCollectionTasksUpdateCollectionTaskResponseStatusDefault = `PENDING`;
export const egoCollectionTasksUpdateCollectionTaskResponseStatusMax = 32;

export const egoCollectionTasksUpdateCollectionTaskResponseKitNameDefault = ``;
export const egoCollectionTasksUpdateCollectionTaskResponseSopNameDefault = ``;
export const egoCollectionTasksUpdateCollectionTaskResponseSopContentDefault = ``;

export const EgoCollectionTasksUpdateCollectionTaskResponse = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "task_no": zod.string().max(egoCollectionTasksUpdateCollectionTaskResponseTaskNoMax).default(egoCollectionTasksUpdateCollectionTaskResponseTaskNoDefault),
  "project_name": zod.string().min(1).max(egoCollectionTasksUpdateCollectionTaskResponseProjectNameMax),
  "name": zod.string().min(1).max(egoCollectionTasksUpdateCollectionTaskResponseNameMax),
  "subtask_name": zod.string().max(egoCollectionTasksUpdateCollectionTaskResponseSubtaskNameMax).default(egoCollectionTasksUpdateCollectionTaskResponseSubtaskNameDefault),
  "scene_type": zod.string().max(egoCollectionTasksUpdateCollectionTaskResponseSceneTypeMax).default(egoCollectionTasksUpdateCollectionTaskResponseSceneTypeDefault),
  "kit_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "sop_id": zod.uuid(),
  "assigned_username": zod.string().max(egoCollectionTasksUpdateCollectionTaskResponseAssignedUsernameMax).default(egoCollectionTasksUpdateCollectionTaskResponseAssignedUsernameDefault),
  "device_serial": zod.string().max(egoCollectionTasksUpdateCollectionTaskResponseDeviceSerialMax).default(egoCollectionTasksUpdateCollectionTaskResponseDeviceSerialDefault),
  "location": zod.string().max(egoCollectionTasksUpdateCollectionTaskResponseLocationMax).default(egoCollectionTasksUpdateCollectionTaskResponseLocationDefault),
  "target_objects": zod.string().max(egoCollectionTasksUpdateCollectionTaskResponseTargetObjectsMax).default(egoCollectionTasksUpdateCollectionTaskResponseTargetObjectsDefault),
  "object_count": zod.number().min(egoCollectionTasksUpdateCollectionTaskResponseObjectCountMin).default(egoCollectionTasksUpdateCollectionTaskResponseObjectCountDefault),
  "duration_minutes": zod.number().min(egoCollectionTasksUpdateCollectionTaskResponseDurationMinutesMin).default(egoCollectionTasksUpdateCollectionTaskResponseDurationMinutesDefault),
  "target_count": zod.number().min(egoCollectionTasksUpdateCollectionTaskResponseTargetCountMin).default(egoCollectionTasksUpdateCollectionTaskResponseTargetCountDefault),
  "completed_count": zod.number().min(egoCollectionTasksUpdateCollectionTaskResponseCompletedCountMin).default(egoCollectionTasksUpdateCollectionTaskResponseCompletedCountDefault),
  "published_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "status": zod.string().max(egoCollectionTasksUpdateCollectionTaskResponseStatusMax).default(egoCollectionTasksUpdateCollectionTaskResponseStatusDefault),
  "workspace_id": zod.uuid(),
  "kit_name": zod.string().default(egoCollectionTasksUpdateCollectionTaskResponseKitNameDefault),
  "sop_name": zod.string().default(egoCollectionTasksUpdateCollectionTaskResponseSopNameDefault),
  "sop_content": zod.string().default(egoCollectionTasksUpdateCollectionTaskResponseSopContentDefault),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * @summary Delete Collection Task
 */
export const EgoCollectionTasksDeleteCollectionTaskParams = zod.object({
  "resource_id": zod.uuid()
})

export const EgoCollectionTasksDeleteCollectionTaskHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const EgoCollectionTasksDeleteCollectionTaskResponse = zod.object({
  "message": zod.string()
})

/**
 * @summary Claim Task
 */
export const EgoCollectionTasksClaimTaskParams = zod.object({
  "resource_id": zod.uuid()
})

export const EgoCollectionTasksClaimTaskHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoCollectionTasksClaimTaskBodyOneLocationDefault = ``;
export const egoCollectionTasksClaimTaskBodyOneLocationMax = 256;

export const egoCollectionTasksClaimTaskBodyOneTargetObjectsDefault = ``;
export const egoCollectionTasksClaimTaskBodyOneTargetObjectsMax = 1000;

export const egoCollectionTasksClaimTaskBodyOneObjectCountDefault = 0;
export const egoCollectionTasksClaimTaskBodyOneObjectCountMin = 0;



export const EgoCollectionTasksClaimTaskBody = zod.union([zod.object({
  "location": zod.string().max(egoCollectionTasksClaimTaskBodyOneLocationMax).default(egoCollectionTasksClaimTaskBodyOneLocationDefault),
  "target_objects": zod.string().max(egoCollectionTasksClaimTaskBodyOneTargetObjectsMax).default(egoCollectionTasksClaimTaskBodyOneTargetObjectsDefault),
  "object_count": zod.number().min(egoCollectionTasksClaimTaskBodyOneObjectCountMin).default(egoCollectionTasksClaimTaskBodyOneObjectCountDefault)
}),zod.null()])

export const egoCollectionTasksClaimTaskResponseTaskNoDefault = ``;
export const egoCollectionTasksClaimTaskResponseTaskNoMax = 64;

export const egoCollectionTasksClaimTaskResponseProjectNameMax = 128;

export const egoCollectionTasksClaimTaskResponseNameMax = 128;

export const egoCollectionTasksClaimTaskResponseSubtaskNameDefault = ``;
export const egoCollectionTasksClaimTaskResponseSubtaskNameMax = 128;

export const egoCollectionTasksClaimTaskResponseSceneTypeDefault = `室内`;
export const egoCollectionTasksClaimTaskResponseSceneTypeMax = 64;

export const egoCollectionTasksClaimTaskResponseAssignedUsernameDefault = ``;
export const egoCollectionTasksClaimTaskResponseAssignedUsernameMax = 128;

export const egoCollectionTasksClaimTaskResponseDeviceSerialDefault = ``;
export const egoCollectionTasksClaimTaskResponseDeviceSerialMax = 128;

export const egoCollectionTasksClaimTaskResponseLocationDefault = ``;
export const egoCollectionTasksClaimTaskResponseLocationMax = 256;

export const egoCollectionTasksClaimTaskResponseTargetObjectsDefault = ``;
export const egoCollectionTasksClaimTaskResponseTargetObjectsMax = 1000;

export const egoCollectionTasksClaimTaskResponseObjectCountDefault = 0;
export const egoCollectionTasksClaimTaskResponseObjectCountMin = 0;

export const egoCollectionTasksClaimTaskResponseDurationMinutesDefault = 30;
export const egoCollectionTasksClaimTaskResponseDurationMinutesMin = 0;

export const egoCollectionTasksClaimTaskResponseTargetCountDefault = 1;
export const egoCollectionTasksClaimTaskResponseTargetCountMin = 0;

export const egoCollectionTasksClaimTaskResponseCompletedCountDefault = 0;
export const egoCollectionTasksClaimTaskResponseCompletedCountMin = 0;

export const egoCollectionTasksClaimTaskResponseStatusDefault = `PENDING`;
export const egoCollectionTasksClaimTaskResponseStatusMax = 32;

export const egoCollectionTasksClaimTaskResponseKitNameDefault = ``;
export const egoCollectionTasksClaimTaskResponseSopNameDefault = ``;
export const egoCollectionTasksClaimTaskResponseSopContentDefault = ``;

export const EgoCollectionTasksClaimTaskResponse = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "task_no": zod.string().max(egoCollectionTasksClaimTaskResponseTaskNoMax).default(egoCollectionTasksClaimTaskResponseTaskNoDefault),
  "project_name": zod.string().min(1).max(egoCollectionTasksClaimTaskResponseProjectNameMax),
  "name": zod.string().min(1).max(egoCollectionTasksClaimTaskResponseNameMax),
  "subtask_name": zod.string().max(egoCollectionTasksClaimTaskResponseSubtaskNameMax).default(egoCollectionTasksClaimTaskResponseSubtaskNameDefault),
  "scene_type": zod.string().max(egoCollectionTasksClaimTaskResponseSceneTypeMax).default(egoCollectionTasksClaimTaskResponseSceneTypeDefault),
  "kit_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "sop_id": zod.uuid(),
  "assigned_username": zod.string().max(egoCollectionTasksClaimTaskResponseAssignedUsernameMax).default(egoCollectionTasksClaimTaskResponseAssignedUsernameDefault),
  "device_serial": zod.string().max(egoCollectionTasksClaimTaskResponseDeviceSerialMax).default(egoCollectionTasksClaimTaskResponseDeviceSerialDefault),
  "location": zod.string().max(egoCollectionTasksClaimTaskResponseLocationMax).default(egoCollectionTasksClaimTaskResponseLocationDefault),
  "target_objects": zod.string().max(egoCollectionTasksClaimTaskResponseTargetObjectsMax).default(egoCollectionTasksClaimTaskResponseTargetObjectsDefault),
  "object_count": zod.number().min(egoCollectionTasksClaimTaskResponseObjectCountMin).default(egoCollectionTasksClaimTaskResponseObjectCountDefault),
  "duration_minutes": zod.number().min(egoCollectionTasksClaimTaskResponseDurationMinutesMin).default(egoCollectionTasksClaimTaskResponseDurationMinutesDefault),
  "target_count": zod.number().min(egoCollectionTasksClaimTaskResponseTargetCountMin).default(egoCollectionTasksClaimTaskResponseTargetCountDefault),
  "completed_count": zod.number().min(egoCollectionTasksClaimTaskResponseCompletedCountMin).default(egoCollectionTasksClaimTaskResponseCompletedCountDefault),
  "published_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "status": zod.string().max(egoCollectionTasksClaimTaskResponseStatusMax).default(egoCollectionTasksClaimTaskResponseStatusDefault),
  "workspace_id": zod.uuid(),
  "kit_name": zod.string().default(egoCollectionTasksClaimTaskResponseKitNameDefault),
  "sop_name": zod.string().default(egoCollectionTasksClaimTaskResponseSopNameDefault),
  "sop_content": zod.string().default(egoCollectionTasksClaimTaskResponseSopContentDefault),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * @summary Start Task
 */
export const EgoCollectionTasksStartTaskParams = zod.object({
  "resource_id": zod.uuid()
})

export const EgoCollectionTasksStartTaskHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoCollectionTasksStartTaskResponseTaskNoDefault = ``;
export const egoCollectionTasksStartTaskResponseTaskNoMax = 64;

export const egoCollectionTasksStartTaskResponseProjectNameMax = 128;

export const egoCollectionTasksStartTaskResponseNameMax = 128;

export const egoCollectionTasksStartTaskResponseSubtaskNameDefault = ``;
export const egoCollectionTasksStartTaskResponseSubtaskNameMax = 128;

export const egoCollectionTasksStartTaskResponseSceneTypeDefault = `室内`;
export const egoCollectionTasksStartTaskResponseSceneTypeMax = 64;

export const egoCollectionTasksStartTaskResponseAssignedUsernameDefault = ``;
export const egoCollectionTasksStartTaskResponseAssignedUsernameMax = 128;

export const egoCollectionTasksStartTaskResponseDeviceSerialDefault = ``;
export const egoCollectionTasksStartTaskResponseDeviceSerialMax = 128;

export const egoCollectionTasksStartTaskResponseLocationDefault = ``;
export const egoCollectionTasksStartTaskResponseLocationMax = 256;

export const egoCollectionTasksStartTaskResponseTargetObjectsDefault = ``;
export const egoCollectionTasksStartTaskResponseTargetObjectsMax = 1000;

export const egoCollectionTasksStartTaskResponseObjectCountDefault = 0;
export const egoCollectionTasksStartTaskResponseObjectCountMin = 0;

export const egoCollectionTasksStartTaskResponseDurationMinutesDefault = 30;
export const egoCollectionTasksStartTaskResponseDurationMinutesMin = 0;

export const egoCollectionTasksStartTaskResponseTargetCountDefault = 1;
export const egoCollectionTasksStartTaskResponseTargetCountMin = 0;

export const egoCollectionTasksStartTaskResponseCompletedCountDefault = 0;
export const egoCollectionTasksStartTaskResponseCompletedCountMin = 0;

export const egoCollectionTasksStartTaskResponseStatusDefault = `PENDING`;
export const egoCollectionTasksStartTaskResponseStatusMax = 32;

export const egoCollectionTasksStartTaskResponseKitNameDefault = ``;
export const egoCollectionTasksStartTaskResponseSopNameDefault = ``;
export const egoCollectionTasksStartTaskResponseSopContentDefault = ``;

export const EgoCollectionTasksStartTaskResponse = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "task_no": zod.string().max(egoCollectionTasksStartTaskResponseTaskNoMax).default(egoCollectionTasksStartTaskResponseTaskNoDefault),
  "project_name": zod.string().min(1).max(egoCollectionTasksStartTaskResponseProjectNameMax),
  "name": zod.string().min(1).max(egoCollectionTasksStartTaskResponseNameMax),
  "subtask_name": zod.string().max(egoCollectionTasksStartTaskResponseSubtaskNameMax).default(egoCollectionTasksStartTaskResponseSubtaskNameDefault),
  "scene_type": zod.string().max(egoCollectionTasksStartTaskResponseSceneTypeMax).default(egoCollectionTasksStartTaskResponseSceneTypeDefault),
  "kit_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "sop_id": zod.uuid(),
  "assigned_username": zod.string().max(egoCollectionTasksStartTaskResponseAssignedUsernameMax).default(egoCollectionTasksStartTaskResponseAssignedUsernameDefault),
  "device_serial": zod.string().max(egoCollectionTasksStartTaskResponseDeviceSerialMax).default(egoCollectionTasksStartTaskResponseDeviceSerialDefault),
  "location": zod.string().max(egoCollectionTasksStartTaskResponseLocationMax).default(egoCollectionTasksStartTaskResponseLocationDefault),
  "target_objects": zod.string().max(egoCollectionTasksStartTaskResponseTargetObjectsMax).default(egoCollectionTasksStartTaskResponseTargetObjectsDefault),
  "object_count": zod.number().min(egoCollectionTasksStartTaskResponseObjectCountMin).default(egoCollectionTasksStartTaskResponseObjectCountDefault),
  "duration_minutes": zod.number().min(egoCollectionTasksStartTaskResponseDurationMinutesMin).default(egoCollectionTasksStartTaskResponseDurationMinutesDefault),
  "target_count": zod.number().min(egoCollectionTasksStartTaskResponseTargetCountMin).default(egoCollectionTasksStartTaskResponseTargetCountDefault),
  "completed_count": zod.number().min(egoCollectionTasksStartTaskResponseCompletedCountMin).default(egoCollectionTasksStartTaskResponseCompletedCountDefault),
  "published_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "status": zod.string().max(egoCollectionTasksStartTaskResponseStatusMax).default(egoCollectionTasksStartTaskResponseStatusDefault),
  "workspace_id": zod.uuid(),
  "kit_name": zod.string().default(egoCollectionTasksStartTaskResponseKitNameDefault),
  "sop_name": zod.string().default(egoCollectionTasksStartTaskResponseSopNameDefault),
  "sop_content": zod.string().default(egoCollectionTasksStartTaskResponseSopContentDefault),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * @summary Pause Task
 */
export const EgoCollectionTasksPauseTaskParams = zod.object({
  "resource_id": zod.uuid()
})

export const EgoCollectionTasksPauseTaskHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoCollectionTasksPauseTaskResponseTaskNoDefault = ``;
export const egoCollectionTasksPauseTaskResponseTaskNoMax = 64;

export const egoCollectionTasksPauseTaskResponseProjectNameMax = 128;

export const egoCollectionTasksPauseTaskResponseNameMax = 128;

export const egoCollectionTasksPauseTaskResponseSubtaskNameDefault = ``;
export const egoCollectionTasksPauseTaskResponseSubtaskNameMax = 128;

export const egoCollectionTasksPauseTaskResponseSceneTypeDefault = `室内`;
export const egoCollectionTasksPauseTaskResponseSceneTypeMax = 64;

export const egoCollectionTasksPauseTaskResponseAssignedUsernameDefault = ``;
export const egoCollectionTasksPauseTaskResponseAssignedUsernameMax = 128;

export const egoCollectionTasksPauseTaskResponseDeviceSerialDefault = ``;
export const egoCollectionTasksPauseTaskResponseDeviceSerialMax = 128;

export const egoCollectionTasksPauseTaskResponseLocationDefault = ``;
export const egoCollectionTasksPauseTaskResponseLocationMax = 256;

export const egoCollectionTasksPauseTaskResponseTargetObjectsDefault = ``;
export const egoCollectionTasksPauseTaskResponseTargetObjectsMax = 1000;

export const egoCollectionTasksPauseTaskResponseObjectCountDefault = 0;
export const egoCollectionTasksPauseTaskResponseObjectCountMin = 0;

export const egoCollectionTasksPauseTaskResponseDurationMinutesDefault = 30;
export const egoCollectionTasksPauseTaskResponseDurationMinutesMin = 0;

export const egoCollectionTasksPauseTaskResponseTargetCountDefault = 1;
export const egoCollectionTasksPauseTaskResponseTargetCountMin = 0;

export const egoCollectionTasksPauseTaskResponseCompletedCountDefault = 0;
export const egoCollectionTasksPauseTaskResponseCompletedCountMin = 0;

export const egoCollectionTasksPauseTaskResponseStatusDefault = `PENDING`;
export const egoCollectionTasksPauseTaskResponseStatusMax = 32;

export const egoCollectionTasksPauseTaskResponseKitNameDefault = ``;
export const egoCollectionTasksPauseTaskResponseSopNameDefault = ``;
export const egoCollectionTasksPauseTaskResponseSopContentDefault = ``;

export const EgoCollectionTasksPauseTaskResponse = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "task_no": zod.string().max(egoCollectionTasksPauseTaskResponseTaskNoMax).default(egoCollectionTasksPauseTaskResponseTaskNoDefault),
  "project_name": zod.string().min(1).max(egoCollectionTasksPauseTaskResponseProjectNameMax),
  "name": zod.string().min(1).max(egoCollectionTasksPauseTaskResponseNameMax),
  "subtask_name": zod.string().max(egoCollectionTasksPauseTaskResponseSubtaskNameMax).default(egoCollectionTasksPauseTaskResponseSubtaskNameDefault),
  "scene_type": zod.string().max(egoCollectionTasksPauseTaskResponseSceneTypeMax).default(egoCollectionTasksPauseTaskResponseSceneTypeDefault),
  "kit_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "sop_id": zod.uuid(),
  "assigned_username": zod.string().max(egoCollectionTasksPauseTaskResponseAssignedUsernameMax).default(egoCollectionTasksPauseTaskResponseAssignedUsernameDefault),
  "device_serial": zod.string().max(egoCollectionTasksPauseTaskResponseDeviceSerialMax).default(egoCollectionTasksPauseTaskResponseDeviceSerialDefault),
  "location": zod.string().max(egoCollectionTasksPauseTaskResponseLocationMax).default(egoCollectionTasksPauseTaskResponseLocationDefault),
  "target_objects": zod.string().max(egoCollectionTasksPauseTaskResponseTargetObjectsMax).default(egoCollectionTasksPauseTaskResponseTargetObjectsDefault),
  "object_count": zod.number().min(egoCollectionTasksPauseTaskResponseObjectCountMin).default(egoCollectionTasksPauseTaskResponseObjectCountDefault),
  "duration_minutes": zod.number().min(egoCollectionTasksPauseTaskResponseDurationMinutesMin).default(egoCollectionTasksPauseTaskResponseDurationMinutesDefault),
  "target_count": zod.number().min(egoCollectionTasksPauseTaskResponseTargetCountMin).default(egoCollectionTasksPauseTaskResponseTargetCountDefault),
  "completed_count": zod.number().min(egoCollectionTasksPauseTaskResponseCompletedCountMin).default(egoCollectionTasksPauseTaskResponseCompletedCountDefault),
  "published_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "status": zod.string().max(egoCollectionTasksPauseTaskResponseStatusMax).default(egoCollectionTasksPauseTaskResponseStatusDefault),
  "workspace_id": zod.uuid(),
  "kit_name": zod.string().default(egoCollectionTasksPauseTaskResponseKitNameDefault),
  "sop_name": zod.string().default(egoCollectionTasksPauseTaskResponseSopNameDefault),
  "sop_content": zod.string().default(egoCollectionTasksPauseTaskResponseSopContentDefault),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * @summary Complete Task
 */
export const EgoCollectionTasksCompleteTaskParams = zod.object({
  "resource_id": zod.uuid()
})

export const EgoCollectionTasksCompleteTaskHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoCollectionTasksCompleteTaskResponseTaskNoDefault = ``;
export const egoCollectionTasksCompleteTaskResponseTaskNoMax = 64;

export const egoCollectionTasksCompleteTaskResponseProjectNameMax = 128;

export const egoCollectionTasksCompleteTaskResponseNameMax = 128;

export const egoCollectionTasksCompleteTaskResponseSubtaskNameDefault = ``;
export const egoCollectionTasksCompleteTaskResponseSubtaskNameMax = 128;

export const egoCollectionTasksCompleteTaskResponseSceneTypeDefault = `室内`;
export const egoCollectionTasksCompleteTaskResponseSceneTypeMax = 64;

export const egoCollectionTasksCompleteTaskResponseAssignedUsernameDefault = ``;
export const egoCollectionTasksCompleteTaskResponseAssignedUsernameMax = 128;

export const egoCollectionTasksCompleteTaskResponseDeviceSerialDefault = ``;
export const egoCollectionTasksCompleteTaskResponseDeviceSerialMax = 128;

export const egoCollectionTasksCompleteTaskResponseLocationDefault = ``;
export const egoCollectionTasksCompleteTaskResponseLocationMax = 256;

export const egoCollectionTasksCompleteTaskResponseTargetObjectsDefault = ``;
export const egoCollectionTasksCompleteTaskResponseTargetObjectsMax = 1000;

export const egoCollectionTasksCompleteTaskResponseObjectCountDefault = 0;
export const egoCollectionTasksCompleteTaskResponseObjectCountMin = 0;

export const egoCollectionTasksCompleteTaskResponseDurationMinutesDefault = 30;
export const egoCollectionTasksCompleteTaskResponseDurationMinutesMin = 0;

export const egoCollectionTasksCompleteTaskResponseTargetCountDefault = 1;
export const egoCollectionTasksCompleteTaskResponseTargetCountMin = 0;

export const egoCollectionTasksCompleteTaskResponseCompletedCountDefault = 0;
export const egoCollectionTasksCompleteTaskResponseCompletedCountMin = 0;

export const egoCollectionTasksCompleteTaskResponseStatusDefault = `PENDING`;
export const egoCollectionTasksCompleteTaskResponseStatusMax = 32;

export const egoCollectionTasksCompleteTaskResponseKitNameDefault = ``;
export const egoCollectionTasksCompleteTaskResponseSopNameDefault = ``;
export const egoCollectionTasksCompleteTaskResponseSopContentDefault = ``;

export const EgoCollectionTasksCompleteTaskResponse = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "task_no": zod.string().max(egoCollectionTasksCompleteTaskResponseTaskNoMax).default(egoCollectionTasksCompleteTaskResponseTaskNoDefault),
  "project_name": zod.string().min(1).max(egoCollectionTasksCompleteTaskResponseProjectNameMax),
  "name": zod.string().min(1).max(egoCollectionTasksCompleteTaskResponseNameMax),
  "subtask_name": zod.string().max(egoCollectionTasksCompleteTaskResponseSubtaskNameMax).default(egoCollectionTasksCompleteTaskResponseSubtaskNameDefault),
  "scene_type": zod.string().max(egoCollectionTasksCompleteTaskResponseSceneTypeMax).default(egoCollectionTasksCompleteTaskResponseSceneTypeDefault),
  "kit_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "sop_id": zod.uuid(),
  "assigned_username": zod.string().max(egoCollectionTasksCompleteTaskResponseAssignedUsernameMax).default(egoCollectionTasksCompleteTaskResponseAssignedUsernameDefault),
  "device_serial": zod.string().max(egoCollectionTasksCompleteTaskResponseDeviceSerialMax).default(egoCollectionTasksCompleteTaskResponseDeviceSerialDefault),
  "location": zod.string().max(egoCollectionTasksCompleteTaskResponseLocationMax).default(egoCollectionTasksCompleteTaskResponseLocationDefault),
  "target_objects": zod.string().max(egoCollectionTasksCompleteTaskResponseTargetObjectsMax).default(egoCollectionTasksCompleteTaskResponseTargetObjectsDefault),
  "object_count": zod.number().min(egoCollectionTasksCompleteTaskResponseObjectCountMin).default(egoCollectionTasksCompleteTaskResponseObjectCountDefault),
  "duration_minutes": zod.number().min(egoCollectionTasksCompleteTaskResponseDurationMinutesMin).default(egoCollectionTasksCompleteTaskResponseDurationMinutesDefault),
  "target_count": zod.number().min(egoCollectionTasksCompleteTaskResponseTargetCountMin).default(egoCollectionTasksCompleteTaskResponseTargetCountDefault),
  "completed_count": zod.number().min(egoCollectionTasksCompleteTaskResponseCompletedCountMin).default(egoCollectionTasksCompleteTaskResponseCompletedCountDefault),
  "published_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "status": zod.string().max(egoCollectionTasksCompleteTaskResponseStatusMax).default(egoCollectionTasksCompleteTaskResponseStatusDefault),
  "workspace_id": zod.uuid(),
  "kit_name": zod.string().default(egoCollectionTasksCompleteTaskResponseKitNameDefault),
  "sop_name": zod.string().default(egoCollectionTasksCompleteTaskResponseSopNameDefault),
  "sop_content": zod.string().default(egoCollectionTasksCompleteTaskResponseSopContentDefault),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * @summary Abandon Task
 */
export const EgoCollectionTasksAbandonTaskParams = zod.object({
  "resource_id": zod.uuid()
})

export const EgoCollectionTasksAbandonTaskHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoCollectionTasksAbandonTaskResponseTaskNoDefault = ``;
export const egoCollectionTasksAbandonTaskResponseTaskNoMax = 64;

export const egoCollectionTasksAbandonTaskResponseProjectNameMax = 128;

export const egoCollectionTasksAbandonTaskResponseNameMax = 128;

export const egoCollectionTasksAbandonTaskResponseSubtaskNameDefault = ``;
export const egoCollectionTasksAbandonTaskResponseSubtaskNameMax = 128;

export const egoCollectionTasksAbandonTaskResponseSceneTypeDefault = `室内`;
export const egoCollectionTasksAbandonTaskResponseSceneTypeMax = 64;

export const egoCollectionTasksAbandonTaskResponseAssignedUsernameDefault = ``;
export const egoCollectionTasksAbandonTaskResponseAssignedUsernameMax = 128;

export const egoCollectionTasksAbandonTaskResponseDeviceSerialDefault = ``;
export const egoCollectionTasksAbandonTaskResponseDeviceSerialMax = 128;

export const egoCollectionTasksAbandonTaskResponseLocationDefault = ``;
export const egoCollectionTasksAbandonTaskResponseLocationMax = 256;

export const egoCollectionTasksAbandonTaskResponseTargetObjectsDefault = ``;
export const egoCollectionTasksAbandonTaskResponseTargetObjectsMax = 1000;

export const egoCollectionTasksAbandonTaskResponseObjectCountDefault = 0;
export const egoCollectionTasksAbandonTaskResponseObjectCountMin = 0;

export const egoCollectionTasksAbandonTaskResponseDurationMinutesDefault = 30;
export const egoCollectionTasksAbandonTaskResponseDurationMinutesMin = 0;

export const egoCollectionTasksAbandonTaskResponseTargetCountDefault = 1;
export const egoCollectionTasksAbandonTaskResponseTargetCountMin = 0;

export const egoCollectionTasksAbandonTaskResponseCompletedCountDefault = 0;
export const egoCollectionTasksAbandonTaskResponseCompletedCountMin = 0;

export const egoCollectionTasksAbandonTaskResponseStatusDefault = `PENDING`;
export const egoCollectionTasksAbandonTaskResponseStatusMax = 32;

export const egoCollectionTasksAbandonTaskResponseKitNameDefault = ``;
export const egoCollectionTasksAbandonTaskResponseSopNameDefault = ``;
export const egoCollectionTasksAbandonTaskResponseSopContentDefault = ``;

export const EgoCollectionTasksAbandonTaskResponse = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "task_no": zod.string().max(egoCollectionTasksAbandonTaskResponseTaskNoMax).default(egoCollectionTasksAbandonTaskResponseTaskNoDefault),
  "project_name": zod.string().min(1).max(egoCollectionTasksAbandonTaskResponseProjectNameMax),
  "name": zod.string().min(1).max(egoCollectionTasksAbandonTaskResponseNameMax),
  "subtask_name": zod.string().max(egoCollectionTasksAbandonTaskResponseSubtaskNameMax).default(egoCollectionTasksAbandonTaskResponseSubtaskNameDefault),
  "scene_type": zod.string().max(egoCollectionTasksAbandonTaskResponseSceneTypeMax).default(egoCollectionTasksAbandonTaskResponseSceneTypeDefault),
  "kit_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "sop_id": zod.uuid(),
  "assigned_username": zod.string().max(egoCollectionTasksAbandonTaskResponseAssignedUsernameMax).default(egoCollectionTasksAbandonTaskResponseAssignedUsernameDefault),
  "device_serial": zod.string().max(egoCollectionTasksAbandonTaskResponseDeviceSerialMax).default(egoCollectionTasksAbandonTaskResponseDeviceSerialDefault),
  "location": zod.string().max(egoCollectionTasksAbandonTaskResponseLocationMax).default(egoCollectionTasksAbandonTaskResponseLocationDefault),
  "target_objects": zod.string().max(egoCollectionTasksAbandonTaskResponseTargetObjectsMax).default(egoCollectionTasksAbandonTaskResponseTargetObjectsDefault),
  "object_count": zod.number().min(egoCollectionTasksAbandonTaskResponseObjectCountMin).default(egoCollectionTasksAbandonTaskResponseObjectCountDefault),
  "duration_minutes": zod.number().min(egoCollectionTasksAbandonTaskResponseDurationMinutesMin).default(egoCollectionTasksAbandonTaskResponseDurationMinutesDefault),
  "target_count": zod.number().min(egoCollectionTasksAbandonTaskResponseTargetCountMin).default(egoCollectionTasksAbandonTaskResponseTargetCountDefault),
  "completed_count": zod.number().min(egoCollectionTasksAbandonTaskResponseCompletedCountMin).default(egoCollectionTasksAbandonTaskResponseCompletedCountDefault),
  "published_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "status": zod.string().max(egoCollectionTasksAbandonTaskResponseStatusMax).default(egoCollectionTasksAbandonTaskResponseStatusDefault),
  "workspace_id": zod.uuid(),
  "kit_name": zod.string().default(egoCollectionTasksAbandonTaskResponseKitNameDefault),
  "sop_name": zod.string().default(egoCollectionTasksAbandonTaskResponseSopNameDefault),
  "sop_content": zod.string().default(egoCollectionTasksAbandonTaskResponseSopContentDefault),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})
