/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CollectionTaskClaim,
  CollectionTaskCreate,
  CollectionTaskPublic,
  CollectionTaskUpdate,
  EgoCollectionTasksReadCollectionTasksParams,
  EgoCollectionTasksReadMyAvailableTasksParams,
  GenericPageCollectionTaskPublic,
  HTTPValidationError,
  Message
} from '../schemas';

import { customFetch } from '../../lib/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Read Collection Tasks
 */
export type egoCollectionTasksReadCollectionTasksResponse200 = {
  data: GenericPageCollectionTaskPublic
  status: 200
}

export type egoCollectionTasksReadCollectionTasksResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionTasksReadCollectionTasksResponseSuccess = (egoCollectionTasksReadCollectionTasksResponse200) & {
  headers: Headers;
};
export type egoCollectionTasksReadCollectionTasksResponseError = (egoCollectionTasksReadCollectionTasksResponse422) & {
  headers: Headers;
};

export type egoCollectionTasksReadCollectionTasksResponse = (egoCollectionTasksReadCollectionTasksResponseSuccess | egoCollectionTasksReadCollectionTasksResponseError)

export const getEgoCollectionTasksReadCollectionTasksUrl = (params?: EgoCollectionTasksReadCollectionTasksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/ego/collection-tasks/?${stringifiedParams}` : `/api/v1/ego/collection-tasks/`
}

export const egoCollectionTasksReadCollectionTasks = async (params?: EgoCollectionTasksReadCollectionTasksParams, options?: RequestInit): Promise<egoCollectionTasksReadCollectionTasksResponse> => {

  return customFetch<egoCollectionTasksReadCollectionTasksResponse>(getEgoCollectionTasksReadCollectionTasksUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getEgoCollectionTasksReadCollectionTasksQueryKey = (params?: EgoCollectionTasksReadCollectionTasksParams,) => {
    return [
    `/api/v1/ego/collection-tasks/`, ...(params ? [params] : [])
    ] as const;
    }


export const getEgoCollectionTasksReadCollectionTasksQueryOptions = <TData = Awaited<ReturnType<typeof egoCollectionTasksReadCollectionTasks>>, TError = HTTPValidationError>(params?: EgoCollectionTasksReadCollectionTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionTasksReadCollectionTasks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEgoCollectionTasksReadCollectionTasksQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof egoCollectionTasksReadCollectionTasks>>> = ({ signal }) => egoCollectionTasksReadCollectionTasks(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof egoCollectionTasksReadCollectionTasks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EgoCollectionTasksReadCollectionTasksQueryResult = NonNullable<Awaited<ReturnType<typeof egoCollectionTasksReadCollectionTasks>>>
export type EgoCollectionTasksReadCollectionTasksQueryError = HTTPValidationError


export function useEgoCollectionTasksReadCollectionTasks<TData = Awaited<ReturnType<typeof egoCollectionTasksReadCollectionTasks>>, TError = HTTPValidationError>(
 params: undefined |  EgoCollectionTasksReadCollectionTasksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionTasksReadCollectionTasks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof egoCollectionTasksReadCollectionTasks>>,
          TError,
          Awaited<ReturnType<typeof egoCollectionTasksReadCollectionTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEgoCollectionTasksReadCollectionTasks<TData = Awaited<ReturnType<typeof egoCollectionTasksReadCollectionTasks>>, TError = HTTPValidationError>(
 params?: EgoCollectionTasksReadCollectionTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionTasksReadCollectionTasks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof egoCollectionTasksReadCollectionTasks>>,
          TError,
          Awaited<ReturnType<typeof egoCollectionTasksReadCollectionTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEgoCollectionTasksReadCollectionTasks<TData = Awaited<ReturnType<typeof egoCollectionTasksReadCollectionTasks>>, TError = HTTPValidationError>(
 params?: EgoCollectionTasksReadCollectionTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionTasksReadCollectionTasks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Collection Tasks
 */

export function useEgoCollectionTasksReadCollectionTasks<TData = Awaited<ReturnType<typeof egoCollectionTasksReadCollectionTasks>>, TError = HTTPValidationError>(
 params?: EgoCollectionTasksReadCollectionTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionTasksReadCollectionTasks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEgoCollectionTasksReadCollectionTasksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Collection Task
 */
export type egoCollectionTasksCreateCollectionTaskResponse200 = {
  data: CollectionTaskPublic
  status: 200
}

export type egoCollectionTasksCreateCollectionTaskResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionTasksCreateCollectionTaskResponseSuccess = (egoCollectionTasksCreateCollectionTaskResponse200) & {
  headers: Headers;
};
export type egoCollectionTasksCreateCollectionTaskResponseError = (egoCollectionTasksCreateCollectionTaskResponse422) & {
  headers: Headers;
};

export type egoCollectionTasksCreateCollectionTaskResponse = (egoCollectionTasksCreateCollectionTaskResponseSuccess | egoCollectionTasksCreateCollectionTaskResponseError)

export const getEgoCollectionTasksCreateCollectionTaskUrl = () => {




  return `/api/v1/ego/collection-tasks/`
}

export const egoCollectionTasksCreateCollectionTask = async (collectionTaskCreate: CollectionTaskCreate, options?: RequestInit): Promise<egoCollectionTasksCreateCollectionTaskResponse> => {

  return customFetch<egoCollectionTasksCreateCollectionTaskResponse>(getEgoCollectionTasksCreateCollectionTaskUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      collectionTaskCreate,)
  }
);}




export const getEgoCollectionTasksCreateCollectionTaskMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksCreateCollectionTask>>, TError,{data: CollectionTaskCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksCreateCollectionTask>>, TError,{data: CollectionTaskCreate}, TContext> => {

const mutationKey = ['egoCollectionTasksCreateCollectionTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoCollectionTasksCreateCollectionTask>>, {data: CollectionTaskCreate}> = (props) => {
          const {data} = props ?? {};

          return  egoCollectionTasksCreateCollectionTask(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoCollectionTasksCreateCollectionTaskMutationResult = NonNullable<Awaited<ReturnType<typeof egoCollectionTasksCreateCollectionTask>>>
    export type EgoCollectionTasksCreateCollectionTaskMutationBody = CollectionTaskCreate
    export type EgoCollectionTasksCreateCollectionTaskMutationError = HTTPValidationError

    /**
 * @summary Create Collection Task
 */
export const useEgoCollectionTasksCreateCollectionTask = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksCreateCollectionTask>>, TError,{data: CollectionTaskCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoCollectionTasksCreateCollectionTask>>,
        TError,
        {data: CollectionTaskCreate},
        TContext
      > => {
      return useMutation(getEgoCollectionTasksCreateCollectionTaskMutationOptions(options), queryClient);
    }
    /**
 * @summary Read My Current Task
 */
export type egoCollectionTasksReadMyCurrentTaskResponse200 = {
  data: CollectionTaskPublic | null
  status: 200
}

export type egoCollectionTasksReadMyCurrentTaskResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionTasksReadMyCurrentTaskResponseSuccess = (egoCollectionTasksReadMyCurrentTaskResponse200) & {
  headers: Headers;
};
export type egoCollectionTasksReadMyCurrentTaskResponseError = (egoCollectionTasksReadMyCurrentTaskResponse422) & {
  headers: Headers;
};

export type egoCollectionTasksReadMyCurrentTaskResponse = (egoCollectionTasksReadMyCurrentTaskResponseSuccess | egoCollectionTasksReadMyCurrentTaskResponseError)

export const getEgoCollectionTasksReadMyCurrentTaskUrl = () => {




  return `/api/v1/ego/collection-tasks/mine/current`
}

export const egoCollectionTasksReadMyCurrentTask = async ( options?: RequestInit): Promise<egoCollectionTasksReadMyCurrentTaskResponse> => {

  return customFetch<egoCollectionTasksReadMyCurrentTaskResponse>(getEgoCollectionTasksReadMyCurrentTaskUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getEgoCollectionTasksReadMyCurrentTaskQueryKey = () => {
    return [
    `/api/v1/ego/collection-tasks/mine/current`
    ] as const;
    }


export const getEgoCollectionTasksReadMyCurrentTaskQueryOptions = <TData = Awaited<ReturnType<typeof egoCollectionTasksReadMyCurrentTask>>, TError = HTTPValidationError>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionTasksReadMyCurrentTask>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEgoCollectionTasksReadMyCurrentTaskQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof egoCollectionTasksReadMyCurrentTask>>> = ({ signal }) => egoCollectionTasksReadMyCurrentTask({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof egoCollectionTasksReadMyCurrentTask>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EgoCollectionTasksReadMyCurrentTaskQueryResult = NonNullable<Awaited<ReturnType<typeof egoCollectionTasksReadMyCurrentTask>>>
export type EgoCollectionTasksReadMyCurrentTaskQueryError = HTTPValidationError


export function useEgoCollectionTasksReadMyCurrentTask<TData = Awaited<ReturnType<typeof egoCollectionTasksReadMyCurrentTask>>, TError = HTTPValidationError>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionTasksReadMyCurrentTask>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof egoCollectionTasksReadMyCurrentTask>>,
          TError,
          Awaited<ReturnType<typeof egoCollectionTasksReadMyCurrentTask>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEgoCollectionTasksReadMyCurrentTask<TData = Awaited<ReturnType<typeof egoCollectionTasksReadMyCurrentTask>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionTasksReadMyCurrentTask>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof egoCollectionTasksReadMyCurrentTask>>,
          TError,
          Awaited<ReturnType<typeof egoCollectionTasksReadMyCurrentTask>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEgoCollectionTasksReadMyCurrentTask<TData = Awaited<ReturnType<typeof egoCollectionTasksReadMyCurrentTask>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionTasksReadMyCurrentTask>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read My Current Task
 */

export function useEgoCollectionTasksReadMyCurrentTask<TData = Awaited<ReturnType<typeof egoCollectionTasksReadMyCurrentTask>>, TError = HTTPValidationError>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionTasksReadMyCurrentTask>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEgoCollectionTasksReadMyCurrentTaskQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Read My Available Tasks
 */
export type egoCollectionTasksReadMyAvailableTasksResponse200 = {
  data: CollectionTaskPublic[]
  status: 200
}

export type egoCollectionTasksReadMyAvailableTasksResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionTasksReadMyAvailableTasksResponseSuccess = (egoCollectionTasksReadMyAvailableTasksResponse200) & {
  headers: Headers;
};
export type egoCollectionTasksReadMyAvailableTasksResponseError = (egoCollectionTasksReadMyAvailableTasksResponse422) & {
  headers: Headers;
};

export type egoCollectionTasksReadMyAvailableTasksResponse = (egoCollectionTasksReadMyAvailableTasksResponseSuccess | egoCollectionTasksReadMyAvailableTasksResponseError)

export const getEgoCollectionTasksReadMyAvailableTasksUrl = (params?: EgoCollectionTasksReadMyAvailableTasksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/ego/collection-tasks/mine/available?${stringifiedParams}` : `/api/v1/ego/collection-tasks/mine/available`
}

export const egoCollectionTasksReadMyAvailableTasks = async (params?: EgoCollectionTasksReadMyAvailableTasksParams, options?: RequestInit): Promise<egoCollectionTasksReadMyAvailableTasksResponse> => {

  return customFetch<egoCollectionTasksReadMyAvailableTasksResponse>(getEgoCollectionTasksReadMyAvailableTasksUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getEgoCollectionTasksReadMyAvailableTasksQueryKey = (params?: EgoCollectionTasksReadMyAvailableTasksParams,) => {
    return [
    `/api/v1/ego/collection-tasks/mine/available`, ...(params ? [params] : [])
    ] as const;
    }


export const getEgoCollectionTasksReadMyAvailableTasksQueryOptions = <TData = Awaited<ReturnType<typeof egoCollectionTasksReadMyAvailableTasks>>, TError = HTTPValidationError>(params?: EgoCollectionTasksReadMyAvailableTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionTasksReadMyAvailableTasks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEgoCollectionTasksReadMyAvailableTasksQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof egoCollectionTasksReadMyAvailableTasks>>> = ({ signal }) => egoCollectionTasksReadMyAvailableTasks(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof egoCollectionTasksReadMyAvailableTasks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EgoCollectionTasksReadMyAvailableTasksQueryResult = NonNullable<Awaited<ReturnType<typeof egoCollectionTasksReadMyAvailableTasks>>>
export type EgoCollectionTasksReadMyAvailableTasksQueryError = HTTPValidationError


export function useEgoCollectionTasksReadMyAvailableTasks<TData = Awaited<ReturnType<typeof egoCollectionTasksReadMyAvailableTasks>>, TError = HTTPValidationError>(
 params: undefined |  EgoCollectionTasksReadMyAvailableTasksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionTasksReadMyAvailableTasks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof egoCollectionTasksReadMyAvailableTasks>>,
          TError,
          Awaited<ReturnType<typeof egoCollectionTasksReadMyAvailableTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEgoCollectionTasksReadMyAvailableTasks<TData = Awaited<ReturnType<typeof egoCollectionTasksReadMyAvailableTasks>>, TError = HTTPValidationError>(
 params?: EgoCollectionTasksReadMyAvailableTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionTasksReadMyAvailableTasks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof egoCollectionTasksReadMyAvailableTasks>>,
          TError,
          Awaited<ReturnType<typeof egoCollectionTasksReadMyAvailableTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEgoCollectionTasksReadMyAvailableTasks<TData = Awaited<ReturnType<typeof egoCollectionTasksReadMyAvailableTasks>>, TError = HTTPValidationError>(
 params?: EgoCollectionTasksReadMyAvailableTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionTasksReadMyAvailableTasks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read My Available Tasks
 */

export function useEgoCollectionTasksReadMyAvailableTasks<TData = Awaited<ReturnType<typeof egoCollectionTasksReadMyAvailableTasks>>, TError = HTTPValidationError>(
 params?: EgoCollectionTasksReadMyAvailableTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionTasksReadMyAvailableTasks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEgoCollectionTasksReadMyAvailableTasksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update Collection Task
 */
export type egoCollectionTasksUpdateCollectionTaskResponse200 = {
  data: CollectionTaskPublic
  status: 200
}

export type egoCollectionTasksUpdateCollectionTaskResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionTasksUpdateCollectionTaskResponseSuccess = (egoCollectionTasksUpdateCollectionTaskResponse200) & {
  headers: Headers;
};
export type egoCollectionTasksUpdateCollectionTaskResponseError = (egoCollectionTasksUpdateCollectionTaskResponse422) & {
  headers: Headers;
};

export type egoCollectionTasksUpdateCollectionTaskResponse = (egoCollectionTasksUpdateCollectionTaskResponseSuccess | egoCollectionTasksUpdateCollectionTaskResponseError)

export const getEgoCollectionTasksUpdateCollectionTaskUrl = (resourceId: string,) => {




  return `/api/v1/ego/collection-tasks/${resourceId}`
}

export const egoCollectionTasksUpdateCollectionTask = async (resourceId: string,
    collectionTaskUpdate: CollectionTaskUpdate, options?: RequestInit): Promise<egoCollectionTasksUpdateCollectionTaskResponse> => {

  return customFetch<egoCollectionTasksUpdateCollectionTaskResponse>(getEgoCollectionTasksUpdateCollectionTaskUrl(resourceId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      collectionTaskUpdate,)
  }
);}




export const getEgoCollectionTasksUpdateCollectionTaskMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksUpdateCollectionTask>>, TError,{resourceId: string;data: CollectionTaskUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksUpdateCollectionTask>>, TError,{resourceId: string;data: CollectionTaskUpdate}, TContext> => {

const mutationKey = ['egoCollectionTasksUpdateCollectionTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoCollectionTasksUpdateCollectionTask>>, {resourceId: string;data: CollectionTaskUpdate}> = (props) => {
          const {resourceId,data} = props ?? {};

          return  egoCollectionTasksUpdateCollectionTask(resourceId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoCollectionTasksUpdateCollectionTaskMutationResult = NonNullable<Awaited<ReturnType<typeof egoCollectionTasksUpdateCollectionTask>>>
    export type EgoCollectionTasksUpdateCollectionTaskMutationBody = CollectionTaskUpdate
    export type EgoCollectionTasksUpdateCollectionTaskMutationError = HTTPValidationError

    /**
 * @summary Update Collection Task
 */
export const useEgoCollectionTasksUpdateCollectionTask = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksUpdateCollectionTask>>, TError,{resourceId: string;data: CollectionTaskUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoCollectionTasksUpdateCollectionTask>>,
        TError,
        {resourceId: string;data: CollectionTaskUpdate},
        TContext
      > => {
      return useMutation(getEgoCollectionTasksUpdateCollectionTaskMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Collection Task
 */
export type egoCollectionTasksDeleteCollectionTaskResponse200 = {
  data: Message
  status: 200
}

export type egoCollectionTasksDeleteCollectionTaskResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionTasksDeleteCollectionTaskResponseSuccess = (egoCollectionTasksDeleteCollectionTaskResponse200) & {
  headers: Headers;
};
export type egoCollectionTasksDeleteCollectionTaskResponseError = (egoCollectionTasksDeleteCollectionTaskResponse422) & {
  headers: Headers;
};

export type egoCollectionTasksDeleteCollectionTaskResponse = (egoCollectionTasksDeleteCollectionTaskResponseSuccess | egoCollectionTasksDeleteCollectionTaskResponseError)

export const getEgoCollectionTasksDeleteCollectionTaskUrl = (resourceId: string,) => {




  return `/api/v1/ego/collection-tasks/${resourceId}`
}

export const egoCollectionTasksDeleteCollectionTask = async (resourceId: string, options?: RequestInit): Promise<egoCollectionTasksDeleteCollectionTaskResponse> => {

  return customFetch<egoCollectionTasksDeleteCollectionTaskResponse>(getEgoCollectionTasksDeleteCollectionTaskUrl(resourceId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getEgoCollectionTasksDeleteCollectionTaskMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksDeleteCollectionTask>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksDeleteCollectionTask>>, TError,{resourceId: string}, TContext> => {

const mutationKey = ['egoCollectionTasksDeleteCollectionTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoCollectionTasksDeleteCollectionTask>>, {resourceId: string}> = (props) => {
          const {resourceId} = props ?? {};

          return  egoCollectionTasksDeleteCollectionTask(resourceId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoCollectionTasksDeleteCollectionTaskMutationResult = NonNullable<Awaited<ReturnType<typeof egoCollectionTasksDeleteCollectionTask>>>

    export type EgoCollectionTasksDeleteCollectionTaskMutationError = HTTPValidationError

    /**
 * @summary Delete Collection Task
 */
export const useEgoCollectionTasksDeleteCollectionTask = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksDeleteCollectionTask>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoCollectionTasksDeleteCollectionTask>>,
        TError,
        {resourceId: string},
        TContext
      > => {
      return useMutation(getEgoCollectionTasksDeleteCollectionTaskMutationOptions(options), queryClient);
    }
    /**
 * @summary Claim Task
 */
export type egoCollectionTasksClaimTaskResponse200 = {
  data: CollectionTaskPublic
  status: 200
}

export type egoCollectionTasksClaimTaskResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionTasksClaimTaskResponseSuccess = (egoCollectionTasksClaimTaskResponse200) & {
  headers: Headers;
};
export type egoCollectionTasksClaimTaskResponseError = (egoCollectionTasksClaimTaskResponse422) & {
  headers: Headers;
};

export type egoCollectionTasksClaimTaskResponse = (egoCollectionTasksClaimTaskResponseSuccess | egoCollectionTasksClaimTaskResponseError)

export const getEgoCollectionTasksClaimTaskUrl = (resourceId: string,) => {




  return `/api/v1/ego/collection-tasks/${resourceId}/claim`
}

export const egoCollectionTasksClaimTask = async (resourceId: string,
    collectionTaskClaimNull: CollectionTaskClaim | null, options?: RequestInit): Promise<egoCollectionTasksClaimTaskResponse> => {

  return customFetch<egoCollectionTasksClaimTaskResponse>(getEgoCollectionTasksClaimTaskUrl(resourceId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      collectionTaskClaimNull,)
  }
);}




export const getEgoCollectionTasksClaimTaskMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksClaimTask>>, TError,{resourceId: string;data: CollectionTaskClaim | null}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksClaimTask>>, TError,{resourceId: string;data: CollectionTaskClaim | null}, TContext> => {

const mutationKey = ['egoCollectionTasksClaimTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoCollectionTasksClaimTask>>, {resourceId: string;data: CollectionTaskClaim | null}> = (props) => {
          const {resourceId,data} = props ?? {};

          return  egoCollectionTasksClaimTask(resourceId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoCollectionTasksClaimTaskMutationResult = NonNullable<Awaited<ReturnType<typeof egoCollectionTasksClaimTask>>>
    export type EgoCollectionTasksClaimTaskMutationBody = CollectionTaskClaim | null
    export type EgoCollectionTasksClaimTaskMutationError = HTTPValidationError

    /**
 * @summary Claim Task
 */
export const useEgoCollectionTasksClaimTask = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksClaimTask>>, TError,{resourceId: string;data: CollectionTaskClaim | null}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoCollectionTasksClaimTask>>,
        TError,
        {resourceId: string;data: CollectionTaskClaim | null},
        TContext
      > => {
      return useMutation(getEgoCollectionTasksClaimTaskMutationOptions(options), queryClient);
    }
    /**
 * @summary Start Task
 */
export type egoCollectionTasksStartTaskResponse200 = {
  data: CollectionTaskPublic
  status: 200
}

export type egoCollectionTasksStartTaskResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionTasksStartTaskResponseSuccess = (egoCollectionTasksStartTaskResponse200) & {
  headers: Headers;
};
export type egoCollectionTasksStartTaskResponseError = (egoCollectionTasksStartTaskResponse422) & {
  headers: Headers;
};

export type egoCollectionTasksStartTaskResponse = (egoCollectionTasksStartTaskResponseSuccess | egoCollectionTasksStartTaskResponseError)

export const getEgoCollectionTasksStartTaskUrl = (resourceId: string,) => {




  return `/api/v1/ego/collection-tasks/${resourceId}/start`
}

export const egoCollectionTasksStartTask = async (resourceId: string, options?: RequestInit): Promise<egoCollectionTasksStartTaskResponse> => {

  return customFetch<egoCollectionTasksStartTaskResponse>(getEgoCollectionTasksStartTaskUrl(resourceId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getEgoCollectionTasksStartTaskMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksStartTask>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksStartTask>>, TError,{resourceId: string}, TContext> => {

const mutationKey = ['egoCollectionTasksStartTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoCollectionTasksStartTask>>, {resourceId: string}> = (props) => {
          const {resourceId} = props ?? {};

          return  egoCollectionTasksStartTask(resourceId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoCollectionTasksStartTaskMutationResult = NonNullable<Awaited<ReturnType<typeof egoCollectionTasksStartTask>>>

    export type EgoCollectionTasksStartTaskMutationError = HTTPValidationError

    /**
 * @summary Start Task
 */
export const useEgoCollectionTasksStartTask = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksStartTask>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoCollectionTasksStartTask>>,
        TError,
        {resourceId: string},
        TContext
      > => {
      return useMutation(getEgoCollectionTasksStartTaskMutationOptions(options), queryClient);
    }
    /**
 * @summary Pause Task
 */
export type egoCollectionTasksPauseTaskResponse200 = {
  data: CollectionTaskPublic
  status: 200
}

export type egoCollectionTasksPauseTaskResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionTasksPauseTaskResponseSuccess = (egoCollectionTasksPauseTaskResponse200) & {
  headers: Headers;
};
export type egoCollectionTasksPauseTaskResponseError = (egoCollectionTasksPauseTaskResponse422) & {
  headers: Headers;
};

export type egoCollectionTasksPauseTaskResponse = (egoCollectionTasksPauseTaskResponseSuccess | egoCollectionTasksPauseTaskResponseError)

export const getEgoCollectionTasksPauseTaskUrl = (resourceId: string,) => {




  return `/api/v1/ego/collection-tasks/${resourceId}/pause`
}

export const egoCollectionTasksPauseTask = async (resourceId: string, options?: RequestInit): Promise<egoCollectionTasksPauseTaskResponse> => {

  return customFetch<egoCollectionTasksPauseTaskResponse>(getEgoCollectionTasksPauseTaskUrl(resourceId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getEgoCollectionTasksPauseTaskMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksPauseTask>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksPauseTask>>, TError,{resourceId: string}, TContext> => {

const mutationKey = ['egoCollectionTasksPauseTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoCollectionTasksPauseTask>>, {resourceId: string}> = (props) => {
          const {resourceId} = props ?? {};

          return  egoCollectionTasksPauseTask(resourceId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoCollectionTasksPauseTaskMutationResult = NonNullable<Awaited<ReturnType<typeof egoCollectionTasksPauseTask>>>

    export type EgoCollectionTasksPauseTaskMutationError = HTTPValidationError

    /**
 * @summary Pause Task
 */
export const useEgoCollectionTasksPauseTask = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksPauseTask>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoCollectionTasksPauseTask>>,
        TError,
        {resourceId: string},
        TContext
      > => {
      return useMutation(getEgoCollectionTasksPauseTaskMutationOptions(options), queryClient);
    }
    /**
 * @summary Complete Task
 */
export type egoCollectionTasksCompleteTaskResponse200 = {
  data: CollectionTaskPublic
  status: 200
}

export type egoCollectionTasksCompleteTaskResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionTasksCompleteTaskResponseSuccess = (egoCollectionTasksCompleteTaskResponse200) & {
  headers: Headers;
};
export type egoCollectionTasksCompleteTaskResponseError = (egoCollectionTasksCompleteTaskResponse422) & {
  headers: Headers;
};

export type egoCollectionTasksCompleteTaskResponse = (egoCollectionTasksCompleteTaskResponseSuccess | egoCollectionTasksCompleteTaskResponseError)

export const getEgoCollectionTasksCompleteTaskUrl = (resourceId: string,) => {




  return `/api/v1/ego/collection-tasks/${resourceId}/complete`
}

export const egoCollectionTasksCompleteTask = async (resourceId: string, options?: RequestInit): Promise<egoCollectionTasksCompleteTaskResponse> => {

  return customFetch<egoCollectionTasksCompleteTaskResponse>(getEgoCollectionTasksCompleteTaskUrl(resourceId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getEgoCollectionTasksCompleteTaskMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksCompleteTask>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksCompleteTask>>, TError,{resourceId: string}, TContext> => {

const mutationKey = ['egoCollectionTasksCompleteTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoCollectionTasksCompleteTask>>, {resourceId: string}> = (props) => {
          const {resourceId} = props ?? {};

          return  egoCollectionTasksCompleteTask(resourceId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoCollectionTasksCompleteTaskMutationResult = NonNullable<Awaited<ReturnType<typeof egoCollectionTasksCompleteTask>>>

    export type EgoCollectionTasksCompleteTaskMutationError = HTTPValidationError

    /**
 * @summary Complete Task
 */
export const useEgoCollectionTasksCompleteTask = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksCompleteTask>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoCollectionTasksCompleteTask>>,
        TError,
        {resourceId: string},
        TContext
      > => {
      return useMutation(getEgoCollectionTasksCompleteTaskMutationOptions(options), queryClient);
    }
    /**
 * @summary Abandon Task
 */
export type egoCollectionTasksAbandonTaskResponse200 = {
  data: CollectionTaskPublic
  status: 200
}

export type egoCollectionTasksAbandonTaskResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionTasksAbandonTaskResponseSuccess = (egoCollectionTasksAbandonTaskResponse200) & {
  headers: Headers;
};
export type egoCollectionTasksAbandonTaskResponseError = (egoCollectionTasksAbandonTaskResponse422) & {
  headers: Headers;
};

export type egoCollectionTasksAbandonTaskResponse = (egoCollectionTasksAbandonTaskResponseSuccess | egoCollectionTasksAbandonTaskResponseError)

export const getEgoCollectionTasksAbandonTaskUrl = (resourceId: string,) => {




  return `/api/v1/ego/collection-tasks/${resourceId}/abandon`
}

export const egoCollectionTasksAbandonTask = async (resourceId: string, options?: RequestInit): Promise<egoCollectionTasksAbandonTaskResponse> => {

  return customFetch<egoCollectionTasksAbandonTaskResponse>(getEgoCollectionTasksAbandonTaskUrl(resourceId),
  {
    ...options,
    method: 'POST'


  }
);}




export const getEgoCollectionTasksAbandonTaskMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksAbandonTask>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksAbandonTask>>, TError,{resourceId: string}, TContext> => {

const mutationKey = ['egoCollectionTasksAbandonTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoCollectionTasksAbandonTask>>, {resourceId: string}> = (props) => {
          const {resourceId} = props ?? {};

          return  egoCollectionTasksAbandonTask(resourceId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoCollectionTasksAbandonTaskMutationResult = NonNullable<Awaited<ReturnType<typeof egoCollectionTasksAbandonTask>>>

    export type EgoCollectionTasksAbandonTaskMutationError = HTTPValidationError

    /**
 * @summary Abandon Task
 */
export const useEgoCollectionTasksAbandonTask = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionTasksAbandonTask>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoCollectionTasksAbandonTask>>,
        TError,
        {resourceId: string},
        TContext
      > => {
      return useMutation(getEgoCollectionTasksAbandonTaskMutationOptions(options), queryClient);
    }
