/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Message
} from '../schemas';

import { customFetch } from '../../lib/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Health check endpoint.
 * @summary Health Check
 */
export type utilsHealthCheckResponse200 = {
  data: boolean
  status: 200
}

export type utilsHealthCheckResponseSuccess = (utilsHealthCheckResponse200) & {
  headers: Headers;
};
;

export type utilsHealthCheckResponse = (utilsHealthCheckResponseSuccess)

export const getUtilsHealthCheckUrl = () => {




  return `/api/v1/utils/health-check/`
}

export const utilsHealthCheck = async ( options?: RequestInit): Promise<utilsHealthCheckResponse> => {

  return customFetch<utilsHealthCheckResponse>(getUtilsHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getUtilsHealthCheckQueryKey = () => {
    return [
    `/api/v1/utils/health-check/`
    ] as const;
    }


export const getUtilsHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof utilsHealthCheck>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof utilsHealthCheck>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUtilsHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof utilsHealthCheck>>> = ({ signal }) => utilsHealthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof utilsHealthCheck>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UtilsHealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof utilsHealthCheck>>>
export type UtilsHealthCheckQueryError = unknown


export function useUtilsHealthCheck<TData = Awaited<ReturnType<typeof utilsHealthCheck>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof utilsHealthCheck>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof utilsHealthCheck>>,
          TError,
          Awaited<ReturnType<typeof utilsHealthCheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUtilsHealthCheck<TData = Awaited<ReturnType<typeof utilsHealthCheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof utilsHealthCheck>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof utilsHealthCheck>>,
          TError,
          Awaited<ReturnType<typeof utilsHealthCheck>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUtilsHealthCheck<TData = Awaited<ReturnType<typeof utilsHealthCheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof utilsHealthCheck>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health Check
 */

export function useUtilsHealthCheck<TData = Awaited<ReturnType<typeof utilsHealthCheck>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof utilsHealthCheck>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUtilsHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Test that superuser auth is working.
 * @summary Test Superuser
 */
export type utilsTestSuperuserResponse201 = {
  data: Message
  status: 201
}

export type utilsTestSuperuserResponseSuccess = (utilsTestSuperuserResponse201) & {
  headers: Headers;
};
;

export type utilsTestSuperuserResponse = (utilsTestSuperuserResponseSuccess)

export const getUtilsTestSuperuserUrl = () => {




  return `/api/v1/utils/test-superuser/`
}

export const utilsTestSuperuser = async ( options?: RequestInit): Promise<utilsTestSuperuserResponse> => {

  return customFetch<utilsTestSuperuserResponse>(getUtilsTestSuperuserUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getUtilsTestSuperuserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof utilsTestSuperuser>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof utilsTestSuperuser>>, TError,void, TContext> => {

const mutationKey = ['utilsTestSuperuser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof utilsTestSuperuser>>, void> = () => {


          return  utilsTestSuperuser(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UtilsTestSuperuserMutationResult = NonNullable<Awaited<ReturnType<typeof utilsTestSuperuser>>>

    export type UtilsTestSuperuserMutationError = unknown

    /**
 * @summary Test Superuser
 */
export const useUtilsTestSuperuser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof utilsTestSuperuser>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof utilsTestSuperuser>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getUtilsTestSuperuserMutationOptions(options), queryClient);
    }
