/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Retrieve all audit/history logs for a specific entity type and ID.
This routes the query correctly through Postgres partitioning, ensuring high performance.
 * @summary Get Audit Logs
 */
export const InfraAuditsGetAuditLogsParams = zod.object({
  "entity_type": zod.string(),
  "entity_id": zod.string()
})

export const InfraAuditsGetAuditLogsResponseItem = zod.object({
  "id": zod.uuid(),
  "entity_type": zod.string(),
  "workspace_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "operator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "operator_name": zod.union([zod.string(),zod.null()]).optional(),
  "entity_id": zod.string(),
  "action": zod.string(),
  "diff_payload": zod.record(zod.string(), zod.unknown()).optional(),
  "created_at": zod.iso.datetime({})
})
export const InfraAuditsGetAuditLogsResponse = zod.array(InfraAuditsGetAuditLogsResponseItem)

/**
 * Retrieve audit logs for a specific field of an entity, including operator name.
 * @summary Get Field Audit Logs
 */
export const InfraAuditsGetFieldAuditLogsParams = zod.object({
  "entity_type": zod.string(),
  "entity_id": zod.string(),
  "field_name": zod.string()
})

export const InfraAuditsGetFieldAuditLogsResponseItem = zod.object({
  "id": zod.uuid(),
  "action": zod.string(),
  "created_at": zod.iso.datetime({}),
  "operator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "operator_name": zod.union([zod.string(),zod.null()]).optional(),
  "old_value": zod.union([zod.unknown(),zod.null()]).optional(),
  "new_value": zod.union([zod.unknown(),zod.null()]).optional()
})
export const InfraAuditsGetFieldAuditLogsResponse = zod.array(InfraAuditsGetFieldAuditLogsResponseItem)
