/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Read Physical Kits
 */
export const egoPhysicalKitsReadPhysicalKitsQuerySkipDefault = 0;
export const egoPhysicalKitsReadPhysicalKitsQuerySkipMin = 0;

export const egoPhysicalKitsReadPhysicalKitsQueryLimitDefault = 20;
export const egoPhysicalKitsReadPhysicalKitsQueryLimitMax = 500;

export const egoPhysicalKitsReadPhysicalKitsQueryQOneMax = 128;

export const egoPhysicalKitsReadPhysicalKitsQueryStatusOneMax = 32;



export const EgoPhysicalKitsReadPhysicalKitsQueryParams = zod.object({
  "skip": zod.number().min(egoPhysicalKitsReadPhysicalKitsQuerySkipMin).default(egoPhysicalKitsReadPhysicalKitsQuerySkipDefault),
  "limit": zod.number().min(1).max(egoPhysicalKitsReadPhysicalKitsQueryLimitMax).default(egoPhysicalKitsReadPhysicalKitsQueryLimitDefault),
  "q": zod.union([zod.string().max(egoPhysicalKitsReadPhysicalKitsQueryQOneMax),zod.null()]).optional(),
  "status": zod.union([zod.string().max(egoPhysicalKitsReadPhysicalKitsQueryStatusOneMax),zod.null()]).optional()
})

export const EgoPhysicalKitsReadPhysicalKitsHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoPhysicalKitsReadPhysicalKitsResponseDataItemSerialNumberMax = 128;

export const egoPhysicalKitsReadPhysicalKitsResponseDataItemNameMax = 128;

export const egoPhysicalKitsReadPhysicalKitsResponseDataItemTerminalSerialDefault = ``;
export const egoPhysicalKitsReadPhysicalKitsResponseDataItemTerminalSerialMax = 128;

export const egoPhysicalKitsReadPhysicalKitsResponseDataItemBoundUsernameDefault = ``;
export const egoPhysicalKitsReadPhysicalKitsResponseDataItemBoundUsernameMax = 128;

export const egoPhysicalKitsReadPhysicalKitsResponseDataItemStatusDefault = `READY`;
export const egoPhysicalKitsReadPhysicalKitsResponseDataItemStatusMax = 32;

export const egoPhysicalKitsReadPhysicalKitsResponseDataItemLocationDefault = ``;
export const egoPhysicalKitsReadPhysicalKitsResponseDataItemLocationMax = 256;

export const egoPhysicalKitsReadPhysicalKitsResponseDataItemRemarkDefault = ``;
export const egoPhysicalKitsReadPhysicalKitsResponseDataItemRemarkMax = 1000;

export const egoPhysicalKitsReadPhysicalKitsResponseDataItemTemplateNameDefault = ``;
export const egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemRoleMax = 64;

export const egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemLabelMax = 128;

export const egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemDeviceModelMax = 128;

export const egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemQuantityDefault = 1;
export const egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemQuantityMax = 32;

export const egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemRequiredDefault = true;
export const egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemChannelCountDefault = 0;
export const egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemChannelCountMin = 0;
export const egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemChannelCountMax = 32;

export const egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemServiceKeyDefault = ``;
export const egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemServiceKeyMax = 128;

export const egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemSortDefault = 1;
export const egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemSortMin = 0;



export const EgoPhysicalKitsReadPhysicalKitsResponse = zod.object({
  "count": zod.number(),
  "data": zod.array(zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "serial_number": zod.string().min(1).max(egoPhysicalKitsReadPhysicalKitsResponseDataItemSerialNumberMax),
  "name": zod.string().min(1).max(egoPhysicalKitsReadPhysicalKitsResponseDataItemNameMax),
  "template_id": zod.uuid(),
  "terminal_serial": zod.string().max(egoPhysicalKitsReadPhysicalKitsResponseDataItemTerminalSerialMax).default(egoPhysicalKitsReadPhysicalKitsResponseDataItemTerminalSerialDefault),
  "bound_username": zod.string().max(egoPhysicalKitsReadPhysicalKitsResponseDataItemBoundUsernameMax).default(egoPhysicalKitsReadPhysicalKitsResponseDataItemBoundUsernameDefault),
  "status": zod.string().max(egoPhysicalKitsReadPhysicalKitsResponseDataItemStatusMax).default(egoPhysicalKitsReadPhysicalKitsResponseDataItemStatusDefault),
  "location": zod.string().max(egoPhysicalKitsReadPhysicalKitsResponseDataItemLocationMax).default(egoPhysicalKitsReadPhysicalKitsResponseDataItemLocationDefault),
  "remark": zod.string().max(egoPhysicalKitsReadPhysicalKitsResponseDataItemRemarkMax).default(egoPhysicalKitsReadPhysicalKitsResponseDataItemRemarkDefault),
  "workspace_id": zod.uuid(),
  "template_name": zod.string().default(egoPhysicalKitsReadPhysicalKitsResponseDataItemTemplateNameDefault),
  "device_slots": zod.array(zod.object({
  "role": zod.string().min(1).max(egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemRoleMax),
  "label": zod.string().min(1).max(egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemLabelMax),
  "device_model": zod.string().min(1).max(egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemDeviceModelMax),
  "quantity": zod.number().min(1).max(egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemQuantityMax).default(egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemQuantityDefault),
  "required": zod.boolean().default(egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemRequiredDefault),
  "channel_count": zod.number().min(egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemChannelCountMin).max(egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemChannelCountMax).default(egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemChannelCountDefault),
  "channel_labels": zod.array(zod.string()).optional(),
  "service_key": zod.string().max(egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemServiceKeyMax).default(egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemServiceKeyDefault),
  "channel_keys": zod.array(zod.string()).optional(),
  "sort": zod.number().min(egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemSortMin).default(egoPhysicalKitsReadPhysicalKitsResponseDataItemDeviceSlotsItemSortDefault)
})).optional(),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
}))
})

/**
 * @summary Create Physical Kit
 */
export const EgoPhysicalKitsCreatePhysicalKitHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoPhysicalKitsCreatePhysicalKitBodySerialNumberMax = 128;

export const egoPhysicalKitsCreatePhysicalKitBodyNameMax = 128;

export const egoPhysicalKitsCreatePhysicalKitBodyTerminalSerialDefault = ``;
export const egoPhysicalKitsCreatePhysicalKitBodyTerminalSerialMax = 128;

export const egoPhysicalKitsCreatePhysicalKitBodyBoundUsernameDefault = ``;
export const egoPhysicalKitsCreatePhysicalKitBodyBoundUsernameMax = 128;

export const egoPhysicalKitsCreatePhysicalKitBodyStatusDefault = `READY`;
export const egoPhysicalKitsCreatePhysicalKitBodyStatusMax = 32;

export const egoPhysicalKitsCreatePhysicalKitBodyLocationDefault = ``;
export const egoPhysicalKitsCreatePhysicalKitBodyLocationMax = 256;

export const egoPhysicalKitsCreatePhysicalKitBodyRemarkDefault = ``;
export const egoPhysicalKitsCreatePhysicalKitBodyRemarkMax = 1000;



export const EgoPhysicalKitsCreatePhysicalKitBody = zod.object({
  "serial_number": zod.string().min(1).max(egoPhysicalKitsCreatePhysicalKitBodySerialNumberMax),
  "name": zod.string().min(1).max(egoPhysicalKitsCreatePhysicalKitBodyNameMax),
  "template_id": zod.uuid(),
  "terminal_serial": zod.string().max(egoPhysicalKitsCreatePhysicalKitBodyTerminalSerialMax).default(egoPhysicalKitsCreatePhysicalKitBodyTerminalSerialDefault),
  "bound_username": zod.string().max(egoPhysicalKitsCreatePhysicalKitBodyBoundUsernameMax).default(egoPhysicalKitsCreatePhysicalKitBodyBoundUsernameDefault),
  "status": zod.string().max(egoPhysicalKitsCreatePhysicalKitBodyStatusMax).default(egoPhysicalKitsCreatePhysicalKitBodyStatusDefault),
  "location": zod.string().max(egoPhysicalKitsCreatePhysicalKitBodyLocationMax).default(egoPhysicalKitsCreatePhysicalKitBodyLocationDefault),
  "remark": zod.string().max(egoPhysicalKitsCreatePhysicalKitBodyRemarkMax).default(egoPhysicalKitsCreatePhysicalKitBodyRemarkDefault)
})

export const egoPhysicalKitsCreatePhysicalKitResponseSerialNumberMax = 128;

export const egoPhysicalKitsCreatePhysicalKitResponseNameMax = 128;

export const egoPhysicalKitsCreatePhysicalKitResponseTerminalSerialDefault = ``;
export const egoPhysicalKitsCreatePhysicalKitResponseTerminalSerialMax = 128;

export const egoPhysicalKitsCreatePhysicalKitResponseBoundUsernameDefault = ``;
export const egoPhysicalKitsCreatePhysicalKitResponseBoundUsernameMax = 128;

export const egoPhysicalKitsCreatePhysicalKitResponseStatusDefault = `READY`;
export const egoPhysicalKitsCreatePhysicalKitResponseStatusMax = 32;

export const egoPhysicalKitsCreatePhysicalKitResponseLocationDefault = ``;
export const egoPhysicalKitsCreatePhysicalKitResponseLocationMax = 256;

export const egoPhysicalKitsCreatePhysicalKitResponseRemarkDefault = ``;
export const egoPhysicalKitsCreatePhysicalKitResponseRemarkMax = 1000;

export const egoPhysicalKitsCreatePhysicalKitResponseTemplateNameDefault = ``;
export const egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemRoleMax = 64;

export const egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemLabelMax = 128;

export const egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemDeviceModelMax = 128;

export const egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemQuantityDefault = 1;
export const egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemQuantityMax = 32;

export const egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemRequiredDefault = true;
export const egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemChannelCountDefault = 0;
export const egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemChannelCountMin = 0;
export const egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemChannelCountMax = 32;

export const egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemServiceKeyDefault = ``;
export const egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemServiceKeyMax = 128;

export const egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemSortDefault = 1;
export const egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemSortMin = 0;



export const EgoPhysicalKitsCreatePhysicalKitResponse = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "serial_number": zod.string().min(1).max(egoPhysicalKitsCreatePhysicalKitResponseSerialNumberMax),
  "name": zod.string().min(1).max(egoPhysicalKitsCreatePhysicalKitResponseNameMax),
  "template_id": zod.uuid(),
  "terminal_serial": zod.string().max(egoPhysicalKitsCreatePhysicalKitResponseTerminalSerialMax).default(egoPhysicalKitsCreatePhysicalKitResponseTerminalSerialDefault),
  "bound_username": zod.string().max(egoPhysicalKitsCreatePhysicalKitResponseBoundUsernameMax).default(egoPhysicalKitsCreatePhysicalKitResponseBoundUsernameDefault),
  "status": zod.string().max(egoPhysicalKitsCreatePhysicalKitResponseStatusMax).default(egoPhysicalKitsCreatePhysicalKitResponseStatusDefault),
  "location": zod.string().max(egoPhysicalKitsCreatePhysicalKitResponseLocationMax).default(egoPhysicalKitsCreatePhysicalKitResponseLocationDefault),
  "remark": zod.string().max(egoPhysicalKitsCreatePhysicalKitResponseRemarkMax).default(egoPhysicalKitsCreatePhysicalKitResponseRemarkDefault),
  "workspace_id": zod.uuid(),
  "template_name": zod.string().default(egoPhysicalKitsCreatePhysicalKitResponseTemplateNameDefault),
  "device_slots": zod.array(zod.object({
  "role": zod.string().min(1).max(egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemRoleMax),
  "label": zod.string().min(1).max(egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemLabelMax),
  "device_model": zod.string().min(1).max(egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemDeviceModelMax),
  "quantity": zod.number().min(1).max(egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemQuantityMax).default(egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemQuantityDefault),
  "required": zod.boolean().default(egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemRequiredDefault),
  "channel_count": zod.number().min(egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemChannelCountMin).max(egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemChannelCountMax).default(egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemChannelCountDefault),
  "channel_labels": zod.array(zod.string()).optional(),
  "service_key": zod.string().max(egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemServiceKeyMax).default(egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemServiceKeyDefault),
  "channel_keys": zod.array(zod.string()).optional(),
  "sort": zod.number().min(egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemSortMin).default(egoPhysicalKitsCreatePhysicalKitResponseDeviceSlotsItemSortDefault)
})).optional(),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * @summary Update Physical Kit
 */
export const EgoPhysicalKitsUpdatePhysicalKitParams = zod.object({
  "resource_id": zod.uuid()
})

export const EgoPhysicalKitsUpdatePhysicalKitHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoPhysicalKitsUpdatePhysicalKitBodySerialNumberMax = 128;

export const egoPhysicalKitsUpdatePhysicalKitBodyNameMax = 128;

export const egoPhysicalKitsUpdatePhysicalKitBodyTerminalSerialDefault = ``;
export const egoPhysicalKitsUpdatePhysicalKitBodyTerminalSerialMax = 128;

export const egoPhysicalKitsUpdatePhysicalKitBodyBoundUsernameDefault = ``;
export const egoPhysicalKitsUpdatePhysicalKitBodyBoundUsernameMax = 128;

export const egoPhysicalKitsUpdatePhysicalKitBodyStatusDefault = `READY`;
export const egoPhysicalKitsUpdatePhysicalKitBodyStatusMax = 32;

export const egoPhysicalKitsUpdatePhysicalKitBodyLocationDefault = ``;
export const egoPhysicalKitsUpdatePhysicalKitBodyLocationMax = 256;

export const egoPhysicalKitsUpdatePhysicalKitBodyRemarkDefault = ``;
export const egoPhysicalKitsUpdatePhysicalKitBodyRemarkMax = 1000;



export const EgoPhysicalKitsUpdatePhysicalKitBody = zod.object({
  "serial_number": zod.string().min(1).max(egoPhysicalKitsUpdatePhysicalKitBodySerialNumberMax),
  "name": zod.string().min(1).max(egoPhysicalKitsUpdatePhysicalKitBodyNameMax),
  "template_id": zod.uuid(),
  "terminal_serial": zod.string().max(egoPhysicalKitsUpdatePhysicalKitBodyTerminalSerialMax).default(egoPhysicalKitsUpdatePhysicalKitBodyTerminalSerialDefault),
  "bound_username": zod.string().max(egoPhysicalKitsUpdatePhysicalKitBodyBoundUsernameMax).default(egoPhysicalKitsUpdatePhysicalKitBodyBoundUsernameDefault),
  "status": zod.string().max(egoPhysicalKitsUpdatePhysicalKitBodyStatusMax).default(egoPhysicalKitsUpdatePhysicalKitBodyStatusDefault),
  "location": zod.string().max(egoPhysicalKitsUpdatePhysicalKitBodyLocationMax).default(egoPhysicalKitsUpdatePhysicalKitBodyLocationDefault),
  "remark": zod.string().max(egoPhysicalKitsUpdatePhysicalKitBodyRemarkMax).default(egoPhysicalKitsUpdatePhysicalKitBodyRemarkDefault)
})

export const egoPhysicalKitsUpdatePhysicalKitResponseSerialNumberMax = 128;

export const egoPhysicalKitsUpdatePhysicalKitResponseNameMax = 128;

export const egoPhysicalKitsUpdatePhysicalKitResponseTerminalSerialDefault = ``;
export const egoPhysicalKitsUpdatePhysicalKitResponseTerminalSerialMax = 128;

export const egoPhysicalKitsUpdatePhysicalKitResponseBoundUsernameDefault = ``;
export const egoPhysicalKitsUpdatePhysicalKitResponseBoundUsernameMax = 128;

export const egoPhysicalKitsUpdatePhysicalKitResponseStatusDefault = `READY`;
export const egoPhysicalKitsUpdatePhysicalKitResponseStatusMax = 32;

export const egoPhysicalKitsUpdatePhysicalKitResponseLocationDefault = ``;
export const egoPhysicalKitsUpdatePhysicalKitResponseLocationMax = 256;

export const egoPhysicalKitsUpdatePhysicalKitResponseRemarkDefault = ``;
export const egoPhysicalKitsUpdatePhysicalKitResponseRemarkMax = 1000;

export const egoPhysicalKitsUpdatePhysicalKitResponseTemplateNameDefault = ``;
export const egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemRoleMax = 64;

export const egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemLabelMax = 128;

export const egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemDeviceModelMax = 128;

export const egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemQuantityDefault = 1;
export const egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemQuantityMax = 32;

export const egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemRequiredDefault = true;
export const egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemChannelCountDefault = 0;
export const egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemChannelCountMin = 0;
export const egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemChannelCountMax = 32;

export const egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemServiceKeyDefault = ``;
export const egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemServiceKeyMax = 128;

export const egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemSortDefault = 1;
export const egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemSortMin = 0;



export const EgoPhysicalKitsUpdatePhysicalKitResponse = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "serial_number": zod.string().min(1).max(egoPhysicalKitsUpdatePhysicalKitResponseSerialNumberMax),
  "name": zod.string().min(1).max(egoPhysicalKitsUpdatePhysicalKitResponseNameMax),
  "template_id": zod.uuid(),
  "terminal_serial": zod.string().max(egoPhysicalKitsUpdatePhysicalKitResponseTerminalSerialMax).default(egoPhysicalKitsUpdatePhysicalKitResponseTerminalSerialDefault),
  "bound_username": zod.string().max(egoPhysicalKitsUpdatePhysicalKitResponseBoundUsernameMax).default(egoPhysicalKitsUpdatePhysicalKitResponseBoundUsernameDefault),
  "status": zod.string().max(egoPhysicalKitsUpdatePhysicalKitResponseStatusMax).default(egoPhysicalKitsUpdatePhysicalKitResponseStatusDefault),
  "location": zod.string().max(egoPhysicalKitsUpdatePhysicalKitResponseLocationMax).default(egoPhysicalKitsUpdatePhysicalKitResponseLocationDefault),
  "remark": zod.string().max(egoPhysicalKitsUpdatePhysicalKitResponseRemarkMax).default(egoPhysicalKitsUpdatePhysicalKitResponseRemarkDefault),
  "workspace_id": zod.uuid(),
  "template_name": zod.string().default(egoPhysicalKitsUpdatePhysicalKitResponseTemplateNameDefault),
  "device_slots": zod.array(zod.object({
  "role": zod.string().min(1).max(egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemRoleMax),
  "label": zod.string().min(1).max(egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemLabelMax),
  "device_model": zod.string().min(1).max(egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemDeviceModelMax),
  "quantity": zod.number().min(1).max(egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemQuantityMax).default(egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemQuantityDefault),
  "required": zod.boolean().default(egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemRequiredDefault),
  "channel_count": zod.number().min(egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemChannelCountMin).max(egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemChannelCountMax).default(egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemChannelCountDefault),
  "channel_labels": zod.array(zod.string()).optional(),
  "service_key": zod.string().max(egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemServiceKeyMax).default(egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemServiceKeyDefault),
  "channel_keys": zod.array(zod.string()).optional(),
  "sort": zod.number().min(egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemSortMin).default(egoPhysicalKitsUpdatePhysicalKitResponseDeviceSlotsItemSortDefault)
})).optional(),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * @summary Delete Physical Kit
 */
export const EgoPhysicalKitsDeletePhysicalKitParams = zod.object({
  "resource_id": zod.uuid()
})

export const EgoPhysicalKitsDeletePhysicalKitHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const EgoPhysicalKitsDeletePhysicalKitResponse = zod.object({
  "message": zod.string()
})
