/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Read Collection Records
 */
export const egoCollectionRecordsReadCollectionRecordsQuerySkipDefault = 0;
export const egoCollectionRecordsReadCollectionRecordsQuerySkipMin = 0;

export const egoCollectionRecordsReadCollectionRecordsQueryLimitDefault = 20;
export const egoCollectionRecordsReadCollectionRecordsQueryLimitMax = 500;

export const egoCollectionRecordsReadCollectionRecordsQueryQOneMax = 128;

export const egoCollectionRecordsReadCollectionRecordsQueryStatusOneMax = 32;



export const EgoCollectionRecordsReadCollectionRecordsQueryParams = zod.object({
  "skip": zod.number().min(egoCollectionRecordsReadCollectionRecordsQuerySkipMin).default(egoCollectionRecordsReadCollectionRecordsQuerySkipDefault),
  "limit": zod.number().min(1).max(egoCollectionRecordsReadCollectionRecordsQueryLimitMax).default(egoCollectionRecordsReadCollectionRecordsQueryLimitDefault),
  "q": zod.union([zod.string().max(egoCollectionRecordsReadCollectionRecordsQueryQOneMax),zod.null()]).optional(),
  "status": zod.union([zod.string().max(egoCollectionRecordsReadCollectionRecordsQueryStatusOneMax),zod.null()]).optional()
})

export const EgoCollectionRecordsReadCollectionRecordsHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoCollectionRecordsReadCollectionRecordsResponseDataItemRecordNoMax = 128;

export const egoCollectionRecordsReadCollectionRecordsResponseDataItemProjectNameDefault = ``;
export const egoCollectionRecordsReadCollectionRecordsResponseDataItemProjectNameMax = 128;

export const egoCollectionRecordsReadCollectionRecordsResponseDataItemTaskNameDefault = ``;
export const egoCollectionRecordsReadCollectionRecordsResponseDataItemTaskNameMax = 128;

export const egoCollectionRecordsReadCollectionRecordsResponseDataItemSubtaskNameDefault = ``;
export const egoCollectionRecordsReadCollectionRecordsResponseDataItemSubtaskNameMax = 128;

export const egoCollectionRecordsReadCollectionRecordsResponseDataItemKitNameDefault = ``;
export const egoCollectionRecordsReadCollectionRecordsResponseDataItemKitNameMax = 128;

export const egoCollectionRecordsReadCollectionRecordsResponseDataItemCaptureLocationDefault = ``;
export const egoCollectionRecordsReadCollectionRecordsResponseDataItemCaptureLocationMax = 256;

export const egoCollectionRecordsReadCollectionRecordsResponseDataItemDeviceSerialDefault = ``;
export const egoCollectionRecordsReadCollectionRecordsResponseDataItemDeviceSerialMax = 128;

export const egoCollectionRecordsReadCollectionRecordsResponseDataItemOperatorUsernameDefault = ``;
export const egoCollectionRecordsReadCollectionRecordsResponseDataItemOperatorUsernameMax = 128;

export const egoCollectionRecordsReadCollectionRecordsResponseDataItemFileNameDefault = ``;
export const egoCollectionRecordsReadCollectionRecordsResponseDataItemFileNameMax = 256;

export const egoCollectionRecordsReadCollectionRecordsResponseDataItemFileSizeBytesDefault = 0;
export const egoCollectionRecordsReadCollectionRecordsResponseDataItemFileSizeBytesMin = 0;

export const egoCollectionRecordsReadCollectionRecordsResponseDataItemDurationSecondsDefault = 0;
export const egoCollectionRecordsReadCollectionRecordsResponseDataItemDurationSecondsMin = 0;

export const egoCollectionRecordsReadCollectionRecordsResponseDataItemStatusDefault = `COMPLETED`;
export const egoCollectionRecordsReadCollectionRecordsResponseDataItemStatusMax = 32;

export const egoCollectionRecordsReadCollectionRecordsResponseDataItemQaStatusDefault = `PENDING`;
export const egoCollectionRecordsReadCollectionRecordsResponseDataItemQaStatusMax = 32;

export const egoCollectionRecordsReadCollectionRecordsResponseDataItemUploadStatusDefault = `LOCAL`;
export const egoCollectionRecordsReadCollectionRecordsResponseDataItemUploadStatusMax = 32;

export const egoCollectionRecordsReadCollectionRecordsResponseDataItemDataStatusDefault = `ON_DISK`;
export const egoCollectionRecordsReadCollectionRecordsResponseDataItemDataStatusMax = 32;

export const egoCollectionRecordsReadCollectionRecordsResponseDataItemRemarkDefault = ``;
export const egoCollectionRecordsReadCollectionRecordsResponseDataItemRemarkMax = 1000;



export const EgoCollectionRecordsReadCollectionRecordsResponse = zod.object({
  "count": zod.number(),
  "data": zod.array(zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "record_no": zod.string().min(1).max(egoCollectionRecordsReadCollectionRecordsResponseDataItemRecordNoMax),
  "task_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "project_name": zod.string().max(egoCollectionRecordsReadCollectionRecordsResponseDataItemProjectNameMax).default(egoCollectionRecordsReadCollectionRecordsResponseDataItemProjectNameDefault),
  "task_name": zod.string().max(egoCollectionRecordsReadCollectionRecordsResponseDataItemTaskNameMax).default(egoCollectionRecordsReadCollectionRecordsResponseDataItemTaskNameDefault),
  "subtask_name": zod.string().max(egoCollectionRecordsReadCollectionRecordsResponseDataItemSubtaskNameMax).default(egoCollectionRecordsReadCollectionRecordsResponseDataItemSubtaskNameDefault),
  "kit_name": zod.string().max(egoCollectionRecordsReadCollectionRecordsResponseDataItemKitNameMax).default(egoCollectionRecordsReadCollectionRecordsResponseDataItemKitNameDefault),
  "capture_location": zod.string().max(egoCollectionRecordsReadCollectionRecordsResponseDataItemCaptureLocationMax).default(egoCollectionRecordsReadCollectionRecordsResponseDataItemCaptureLocationDefault),
  "device_serial": zod.string().max(egoCollectionRecordsReadCollectionRecordsResponseDataItemDeviceSerialMax).default(egoCollectionRecordsReadCollectionRecordsResponseDataItemDeviceSerialDefault),
  "operator_username": zod.string().max(egoCollectionRecordsReadCollectionRecordsResponseDataItemOperatorUsernameMax).default(egoCollectionRecordsReadCollectionRecordsResponseDataItemOperatorUsernameDefault),
  "file_name": zod.string().max(egoCollectionRecordsReadCollectionRecordsResponseDataItemFileNameMax).default(egoCollectionRecordsReadCollectionRecordsResponseDataItemFileNameDefault),
  "file_size_bytes": zod.number().min(egoCollectionRecordsReadCollectionRecordsResponseDataItemFileSizeBytesMin).default(egoCollectionRecordsReadCollectionRecordsResponseDataItemFileSizeBytesDefault),
  "duration_seconds": zod.number().min(egoCollectionRecordsReadCollectionRecordsResponseDataItemDurationSecondsMin).default(egoCollectionRecordsReadCollectionRecordsResponseDataItemDurationSecondsDefault),
  "status": zod.string().max(egoCollectionRecordsReadCollectionRecordsResponseDataItemStatusMax).default(egoCollectionRecordsReadCollectionRecordsResponseDataItemStatusDefault),
  "qa_status": zod.string().max(egoCollectionRecordsReadCollectionRecordsResponseDataItemQaStatusMax).default(egoCollectionRecordsReadCollectionRecordsResponseDataItemQaStatusDefault),
  "upload_status": zod.string().max(egoCollectionRecordsReadCollectionRecordsResponseDataItemUploadStatusMax).default(egoCollectionRecordsReadCollectionRecordsResponseDataItemUploadStatusDefault),
  "data_status": zod.string().max(egoCollectionRecordsReadCollectionRecordsResponseDataItemDataStatusMax).default(egoCollectionRecordsReadCollectionRecordsResponseDataItemDataStatusDefault),
  "captured_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "remark": zod.string().max(egoCollectionRecordsReadCollectionRecordsResponseDataItemRemarkMax).default(egoCollectionRecordsReadCollectionRecordsResponseDataItemRemarkDefault),
  "workspace_id": zod.uuid(),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
}))
})

/**
 * @summary Create Collection Record
 */
export const EgoCollectionRecordsCreateCollectionRecordHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoCollectionRecordsCreateCollectionRecordBodyRecordNoMax = 128;

export const egoCollectionRecordsCreateCollectionRecordBodyProjectNameDefault = ``;
export const egoCollectionRecordsCreateCollectionRecordBodyProjectNameMax = 128;

export const egoCollectionRecordsCreateCollectionRecordBodyTaskNameDefault = ``;
export const egoCollectionRecordsCreateCollectionRecordBodyTaskNameMax = 128;

export const egoCollectionRecordsCreateCollectionRecordBodySubtaskNameDefault = ``;
export const egoCollectionRecordsCreateCollectionRecordBodySubtaskNameMax = 128;

export const egoCollectionRecordsCreateCollectionRecordBodyKitNameDefault = ``;
export const egoCollectionRecordsCreateCollectionRecordBodyKitNameMax = 128;

export const egoCollectionRecordsCreateCollectionRecordBodyCaptureLocationDefault = ``;
export const egoCollectionRecordsCreateCollectionRecordBodyCaptureLocationMax = 256;

export const egoCollectionRecordsCreateCollectionRecordBodyDeviceSerialDefault = ``;
export const egoCollectionRecordsCreateCollectionRecordBodyDeviceSerialMax = 128;

export const egoCollectionRecordsCreateCollectionRecordBodyOperatorUsernameDefault = ``;
export const egoCollectionRecordsCreateCollectionRecordBodyOperatorUsernameMax = 128;

export const egoCollectionRecordsCreateCollectionRecordBodyFileNameDefault = ``;
export const egoCollectionRecordsCreateCollectionRecordBodyFileNameMax = 256;

export const egoCollectionRecordsCreateCollectionRecordBodyFileSizeBytesDefault = 0;
export const egoCollectionRecordsCreateCollectionRecordBodyFileSizeBytesMin = 0;

export const egoCollectionRecordsCreateCollectionRecordBodyDurationSecondsDefault = 0;
export const egoCollectionRecordsCreateCollectionRecordBodyDurationSecondsMin = 0;

export const egoCollectionRecordsCreateCollectionRecordBodyStatusDefault = `COMPLETED`;
export const egoCollectionRecordsCreateCollectionRecordBodyStatusMax = 32;

export const egoCollectionRecordsCreateCollectionRecordBodyQaStatusDefault = `PENDING`;
export const egoCollectionRecordsCreateCollectionRecordBodyQaStatusMax = 32;

export const egoCollectionRecordsCreateCollectionRecordBodyUploadStatusDefault = `LOCAL`;
export const egoCollectionRecordsCreateCollectionRecordBodyUploadStatusMax = 32;

export const egoCollectionRecordsCreateCollectionRecordBodyDataStatusDefault = `ON_DISK`;
export const egoCollectionRecordsCreateCollectionRecordBodyDataStatusMax = 32;

export const egoCollectionRecordsCreateCollectionRecordBodyRemarkDefault = ``;
export const egoCollectionRecordsCreateCollectionRecordBodyRemarkMax = 1000;



export const EgoCollectionRecordsCreateCollectionRecordBody = zod.object({
  "record_no": zod.string().min(1).max(egoCollectionRecordsCreateCollectionRecordBodyRecordNoMax),
  "task_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "project_name": zod.string().max(egoCollectionRecordsCreateCollectionRecordBodyProjectNameMax).default(egoCollectionRecordsCreateCollectionRecordBodyProjectNameDefault),
  "task_name": zod.string().max(egoCollectionRecordsCreateCollectionRecordBodyTaskNameMax).default(egoCollectionRecordsCreateCollectionRecordBodyTaskNameDefault),
  "subtask_name": zod.string().max(egoCollectionRecordsCreateCollectionRecordBodySubtaskNameMax).default(egoCollectionRecordsCreateCollectionRecordBodySubtaskNameDefault),
  "kit_name": zod.string().max(egoCollectionRecordsCreateCollectionRecordBodyKitNameMax).default(egoCollectionRecordsCreateCollectionRecordBodyKitNameDefault),
  "capture_location": zod.string().max(egoCollectionRecordsCreateCollectionRecordBodyCaptureLocationMax).default(egoCollectionRecordsCreateCollectionRecordBodyCaptureLocationDefault),
  "device_serial": zod.string().max(egoCollectionRecordsCreateCollectionRecordBodyDeviceSerialMax).default(egoCollectionRecordsCreateCollectionRecordBodyDeviceSerialDefault),
  "operator_username": zod.string().max(egoCollectionRecordsCreateCollectionRecordBodyOperatorUsernameMax).default(egoCollectionRecordsCreateCollectionRecordBodyOperatorUsernameDefault),
  "file_name": zod.string().max(egoCollectionRecordsCreateCollectionRecordBodyFileNameMax).default(egoCollectionRecordsCreateCollectionRecordBodyFileNameDefault),
  "file_size_bytes": zod.number().min(egoCollectionRecordsCreateCollectionRecordBodyFileSizeBytesMin).default(egoCollectionRecordsCreateCollectionRecordBodyFileSizeBytesDefault),
  "duration_seconds": zod.number().min(egoCollectionRecordsCreateCollectionRecordBodyDurationSecondsMin).default(egoCollectionRecordsCreateCollectionRecordBodyDurationSecondsDefault),
  "status": zod.string().max(egoCollectionRecordsCreateCollectionRecordBodyStatusMax).default(egoCollectionRecordsCreateCollectionRecordBodyStatusDefault),
  "qa_status": zod.string().max(egoCollectionRecordsCreateCollectionRecordBodyQaStatusMax).default(egoCollectionRecordsCreateCollectionRecordBodyQaStatusDefault),
  "upload_status": zod.string().max(egoCollectionRecordsCreateCollectionRecordBodyUploadStatusMax).default(egoCollectionRecordsCreateCollectionRecordBodyUploadStatusDefault),
  "data_status": zod.string().max(egoCollectionRecordsCreateCollectionRecordBodyDataStatusMax).default(egoCollectionRecordsCreateCollectionRecordBodyDataStatusDefault),
  "captured_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "remark": zod.string().max(egoCollectionRecordsCreateCollectionRecordBodyRemarkMax).default(egoCollectionRecordsCreateCollectionRecordBodyRemarkDefault)
})

export const egoCollectionRecordsCreateCollectionRecordResponseRecordNoMax = 128;

export const egoCollectionRecordsCreateCollectionRecordResponseProjectNameDefault = ``;
export const egoCollectionRecordsCreateCollectionRecordResponseProjectNameMax = 128;

export const egoCollectionRecordsCreateCollectionRecordResponseTaskNameDefault = ``;
export const egoCollectionRecordsCreateCollectionRecordResponseTaskNameMax = 128;

export const egoCollectionRecordsCreateCollectionRecordResponseSubtaskNameDefault = ``;
export const egoCollectionRecordsCreateCollectionRecordResponseSubtaskNameMax = 128;

export const egoCollectionRecordsCreateCollectionRecordResponseKitNameDefault = ``;
export const egoCollectionRecordsCreateCollectionRecordResponseKitNameMax = 128;

export const egoCollectionRecordsCreateCollectionRecordResponseCaptureLocationDefault = ``;
export const egoCollectionRecordsCreateCollectionRecordResponseCaptureLocationMax = 256;

export const egoCollectionRecordsCreateCollectionRecordResponseDeviceSerialDefault = ``;
export const egoCollectionRecordsCreateCollectionRecordResponseDeviceSerialMax = 128;

export const egoCollectionRecordsCreateCollectionRecordResponseOperatorUsernameDefault = ``;
export const egoCollectionRecordsCreateCollectionRecordResponseOperatorUsernameMax = 128;

export const egoCollectionRecordsCreateCollectionRecordResponseFileNameDefault = ``;
export const egoCollectionRecordsCreateCollectionRecordResponseFileNameMax = 256;

export const egoCollectionRecordsCreateCollectionRecordResponseFileSizeBytesDefault = 0;
export const egoCollectionRecordsCreateCollectionRecordResponseFileSizeBytesMin = 0;

export const egoCollectionRecordsCreateCollectionRecordResponseDurationSecondsDefault = 0;
export const egoCollectionRecordsCreateCollectionRecordResponseDurationSecondsMin = 0;

export const egoCollectionRecordsCreateCollectionRecordResponseStatusDefault = `COMPLETED`;
export const egoCollectionRecordsCreateCollectionRecordResponseStatusMax = 32;

export const egoCollectionRecordsCreateCollectionRecordResponseQaStatusDefault = `PENDING`;
export const egoCollectionRecordsCreateCollectionRecordResponseQaStatusMax = 32;

export const egoCollectionRecordsCreateCollectionRecordResponseUploadStatusDefault = `LOCAL`;
export const egoCollectionRecordsCreateCollectionRecordResponseUploadStatusMax = 32;

export const egoCollectionRecordsCreateCollectionRecordResponseDataStatusDefault = `ON_DISK`;
export const egoCollectionRecordsCreateCollectionRecordResponseDataStatusMax = 32;

export const egoCollectionRecordsCreateCollectionRecordResponseRemarkDefault = ``;
export const egoCollectionRecordsCreateCollectionRecordResponseRemarkMax = 1000;



export const EgoCollectionRecordsCreateCollectionRecordResponse = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "record_no": zod.string().min(1).max(egoCollectionRecordsCreateCollectionRecordResponseRecordNoMax),
  "task_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "project_name": zod.string().max(egoCollectionRecordsCreateCollectionRecordResponseProjectNameMax).default(egoCollectionRecordsCreateCollectionRecordResponseProjectNameDefault),
  "task_name": zod.string().max(egoCollectionRecordsCreateCollectionRecordResponseTaskNameMax).default(egoCollectionRecordsCreateCollectionRecordResponseTaskNameDefault),
  "subtask_name": zod.string().max(egoCollectionRecordsCreateCollectionRecordResponseSubtaskNameMax).default(egoCollectionRecordsCreateCollectionRecordResponseSubtaskNameDefault),
  "kit_name": zod.string().max(egoCollectionRecordsCreateCollectionRecordResponseKitNameMax).default(egoCollectionRecordsCreateCollectionRecordResponseKitNameDefault),
  "capture_location": zod.string().max(egoCollectionRecordsCreateCollectionRecordResponseCaptureLocationMax).default(egoCollectionRecordsCreateCollectionRecordResponseCaptureLocationDefault),
  "device_serial": zod.string().max(egoCollectionRecordsCreateCollectionRecordResponseDeviceSerialMax).default(egoCollectionRecordsCreateCollectionRecordResponseDeviceSerialDefault),
  "operator_username": zod.string().max(egoCollectionRecordsCreateCollectionRecordResponseOperatorUsernameMax).default(egoCollectionRecordsCreateCollectionRecordResponseOperatorUsernameDefault),
  "file_name": zod.string().max(egoCollectionRecordsCreateCollectionRecordResponseFileNameMax).default(egoCollectionRecordsCreateCollectionRecordResponseFileNameDefault),
  "file_size_bytes": zod.number().min(egoCollectionRecordsCreateCollectionRecordResponseFileSizeBytesMin).default(egoCollectionRecordsCreateCollectionRecordResponseFileSizeBytesDefault),
  "duration_seconds": zod.number().min(egoCollectionRecordsCreateCollectionRecordResponseDurationSecondsMin).default(egoCollectionRecordsCreateCollectionRecordResponseDurationSecondsDefault),
  "status": zod.string().max(egoCollectionRecordsCreateCollectionRecordResponseStatusMax).default(egoCollectionRecordsCreateCollectionRecordResponseStatusDefault),
  "qa_status": zod.string().max(egoCollectionRecordsCreateCollectionRecordResponseQaStatusMax).default(egoCollectionRecordsCreateCollectionRecordResponseQaStatusDefault),
  "upload_status": zod.string().max(egoCollectionRecordsCreateCollectionRecordResponseUploadStatusMax).default(egoCollectionRecordsCreateCollectionRecordResponseUploadStatusDefault),
  "data_status": zod.string().max(egoCollectionRecordsCreateCollectionRecordResponseDataStatusMax).default(egoCollectionRecordsCreateCollectionRecordResponseDataStatusDefault),
  "captured_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "remark": zod.string().max(egoCollectionRecordsCreateCollectionRecordResponseRemarkMax).default(egoCollectionRecordsCreateCollectionRecordResponseRemarkDefault),
  "workspace_id": zod.uuid(),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * @summary Read My Collection Records
 */
export const egoCollectionRecordsReadMyCollectionRecordsQueryLimitDefault = 500;
export const egoCollectionRecordsReadMyCollectionRecordsQueryLimitMax = 1000;



export const EgoCollectionRecordsReadMyCollectionRecordsQueryParams = zod.object({
  "limit": zod.number().min(1).max(egoCollectionRecordsReadMyCollectionRecordsQueryLimitMax).default(egoCollectionRecordsReadMyCollectionRecordsQueryLimitDefault)
})

export const EgoCollectionRecordsReadMyCollectionRecordsHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoCollectionRecordsReadMyCollectionRecordsResponseRecordNoMax = 128;

export const egoCollectionRecordsReadMyCollectionRecordsResponseProjectNameDefault = ``;
export const egoCollectionRecordsReadMyCollectionRecordsResponseProjectNameMax = 128;

export const egoCollectionRecordsReadMyCollectionRecordsResponseTaskNameDefault = ``;
export const egoCollectionRecordsReadMyCollectionRecordsResponseTaskNameMax = 128;

export const egoCollectionRecordsReadMyCollectionRecordsResponseSubtaskNameDefault = ``;
export const egoCollectionRecordsReadMyCollectionRecordsResponseSubtaskNameMax = 128;

export const egoCollectionRecordsReadMyCollectionRecordsResponseKitNameDefault = ``;
export const egoCollectionRecordsReadMyCollectionRecordsResponseKitNameMax = 128;

export const egoCollectionRecordsReadMyCollectionRecordsResponseCaptureLocationDefault = ``;
export const egoCollectionRecordsReadMyCollectionRecordsResponseCaptureLocationMax = 256;

export const egoCollectionRecordsReadMyCollectionRecordsResponseDeviceSerialDefault = ``;
export const egoCollectionRecordsReadMyCollectionRecordsResponseDeviceSerialMax = 128;

export const egoCollectionRecordsReadMyCollectionRecordsResponseOperatorUsernameDefault = ``;
export const egoCollectionRecordsReadMyCollectionRecordsResponseOperatorUsernameMax = 128;

export const egoCollectionRecordsReadMyCollectionRecordsResponseFileNameDefault = ``;
export const egoCollectionRecordsReadMyCollectionRecordsResponseFileNameMax = 256;

export const egoCollectionRecordsReadMyCollectionRecordsResponseFileSizeBytesDefault = 0;
export const egoCollectionRecordsReadMyCollectionRecordsResponseFileSizeBytesMin = 0;

export const egoCollectionRecordsReadMyCollectionRecordsResponseDurationSecondsDefault = 0;
export const egoCollectionRecordsReadMyCollectionRecordsResponseDurationSecondsMin = 0;

export const egoCollectionRecordsReadMyCollectionRecordsResponseStatusDefault = `COMPLETED`;
export const egoCollectionRecordsReadMyCollectionRecordsResponseStatusMax = 32;

export const egoCollectionRecordsReadMyCollectionRecordsResponseQaStatusDefault = `PENDING`;
export const egoCollectionRecordsReadMyCollectionRecordsResponseQaStatusMax = 32;

export const egoCollectionRecordsReadMyCollectionRecordsResponseUploadStatusDefault = `LOCAL`;
export const egoCollectionRecordsReadMyCollectionRecordsResponseUploadStatusMax = 32;

export const egoCollectionRecordsReadMyCollectionRecordsResponseDataStatusDefault = `ON_DISK`;
export const egoCollectionRecordsReadMyCollectionRecordsResponseDataStatusMax = 32;

export const egoCollectionRecordsReadMyCollectionRecordsResponseRemarkDefault = ``;
export const egoCollectionRecordsReadMyCollectionRecordsResponseRemarkMax = 1000;



export const EgoCollectionRecordsReadMyCollectionRecordsResponseItem = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "record_no": zod.string().min(1).max(egoCollectionRecordsReadMyCollectionRecordsResponseRecordNoMax),
  "task_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "project_name": zod.string().max(egoCollectionRecordsReadMyCollectionRecordsResponseProjectNameMax).default(egoCollectionRecordsReadMyCollectionRecordsResponseProjectNameDefault),
  "task_name": zod.string().max(egoCollectionRecordsReadMyCollectionRecordsResponseTaskNameMax).default(egoCollectionRecordsReadMyCollectionRecordsResponseTaskNameDefault),
  "subtask_name": zod.string().max(egoCollectionRecordsReadMyCollectionRecordsResponseSubtaskNameMax).default(egoCollectionRecordsReadMyCollectionRecordsResponseSubtaskNameDefault),
  "kit_name": zod.string().max(egoCollectionRecordsReadMyCollectionRecordsResponseKitNameMax).default(egoCollectionRecordsReadMyCollectionRecordsResponseKitNameDefault),
  "capture_location": zod.string().max(egoCollectionRecordsReadMyCollectionRecordsResponseCaptureLocationMax).default(egoCollectionRecordsReadMyCollectionRecordsResponseCaptureLocationDefault),
  "device_serial": zod.string().max(egoCollectionRecordsReadMyCollectionRecordsResponseDeviceSerialMax).default(egoCollectionRecordsReadMyCollectionRecordsResponseDeviceSerialDefault),
  "operator_username": zod.string().max(egoCollectionRecordsReadMyCollectionRecordsResponseOperatorUsernameMax).default(egoCollectionRecordsReadMyCollectionRecordsResponseOperatorUsernameDefault),
  "file_name": zod.string().max(egoCollectionRecordsReadMyCollectionRecordsResponseFileNameMax).default(egoCollectionRecordsReadMyCollectionRecordsResponseFileNameDefault),
  "file_size_bytes": zod.number().min(egoCollectionRecordsReadMyCollectionRecordsResponseFileSizeBytesMin).default(egoCollectionRecordsReadMyCollectionRecordsResponseFileSizeBytesDefault),
  "duration_seconds": zod.number().min(egoCollectionRecordsReadMyCollectionRecordsResponseDurationSecondsMin).default(egoCollectionRecordsReadMyCollectionRecordsResponseDurationSecondsDefault),
  "status": zod.string().max(egoCollectionRecordsReadMyCollectionRecordsResponseStatusMax).default(egoCollectionRecordsReadMyCollectionRecordsResponseStatusDefault),
  "qa_status": zod.string().max(egoCollectionRecordsReadMyCollectionRecordsResponseQaStatusMax).default(egoCollectionRecordsReadMyCollectionRecordsResponseQaStatusDefault),
  "upload_status": zod.string().max(egoCollectionRecordsReadMyCollectionRecordsResponseUploadStatusMax).default(egoCollectionRecordsReadMyCollectionRecordsResponseUploadStatusDefault),
  "data_status": zod.string().max(egoCollectionRecordsReadMyCollectionRecordsResponseDataStatusMax).default(egoCollectionRecordsReadMyCollectionRecordsResponseDataStatusDefault),
  "captured_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "remark": zod.string().max(egoCollectionRecordsReadMyCollectionRecordsResponseRemarkMax).default(egoCollectionRecordsReadMyCollectionRecordsResponseRemarkDefault),
  "workspace_id": zod.uuid(),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})
export const EgoCollectionRecordsReadMyCollectionRecordsResponse = zod.array(EgoCollectionRecordsReadMyCollectionRecordsResponseItem)

/**
 * @summary Update Collection Record
 */
export const EgoCollectionRecordsUpdateCollectionRecordParams = zod.object({
  "resource_id": zod.uuid()
})

export const EgoCollectionRecordsUpdateCollectionRecordHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoCollectionRecordsUpdateCollectionRecordBodyRecordNoMax = 128;

export const egoCollectionRecordsUpdateCollectionRecordBodyProjectNameDefault = ``;
export const egoCollectionRecordsUpdateCollectionRecordBodyProjectNameMax = 128;

export const egoCollectionRecordsUpdateCollectionRecordBodyTaskNameDefault = ``;
export const egoCollectionRecordsUpdateCollectionRecordBodyTaskNameMax = 128;

export const egoCollectionRecordsUpdateCollectionRecordBodySubtaskNameDefault = ``;
export const egoCollectionRecordsUpdateCollectionRecordBodySubtaskNameMax = 128;

export const egoCollectionRecordsUpdateCollectionRecordBodyKitNameDefault = ``;
export const egoCollectionRecordsUpdateCollectionRecordBodyKitNameMax = 128;

export const egoCollectionRecordsUpdateCollectionRecordBodyCaptureLocationDefault = ``;
export const egoCollectionRecordsUpdateCollectionRecordBodyCaptureLocationMax = 256;

export const egoCollectionRecordsUpdateCollectionRecordBodyDeviceSerialDefault = ``;
export const egoCollectionRecordsUpdateCollectionRecordBodyDeviceSerialMax = 128;

export const egoCollectionRecordsUpdateCollectionRecordBodyOperatorUsernameDefault = ``;
export const egoCollectionRecordsUpdateCollectionRecordBodyOperatorUsernameMax = 128;

export const egoCollectionRecordsUpdateCollectionRecordBodyFileNameDefault = ``;
export const egoCollectionRecordsUpdateCollectionRecordBodyFileNameMax = 256;

export const egoCollectionRecordsUpdateCollectionRecordBodyFileSizeBytesDefault = 0;
export const egoCollectionRecordsUpdateCollectionRecordBodyFileSizeBytesMin = 0;

export const egoCollectionRecordsUpdateCollectionRecordBodyDurationSecondsDefault = 0;
export const egoCollectionRecordsUpdateCollectionRecordBodyDurationSecondsMin = 0;

export const egoCollectionRecordsUpdateCollectionRecordBodyStatusDefault = `COMPLETED`;
export const egoCollectionRecordsUpdateCollectionRecordBodyStatusMax = 32;

export const egoCollectionRecordsUpdateCollectionRecordBodyQaStatusDefault = `PENDING`;
export const egoCollectionRecordsUpdateCollectionRecordBodyQaStatusMax = 32;

export const egoCollectionRecordsUpdateCollectionRecordBodyUploadStatusDefault = `LOCAL`;
export const egoCollectionRecordsUpdateCollectionRecordBodyUploadStatusMax = 32;

export const egoCollectionRecordsUpdateCollectionRecordBodyDataStatusDefault = `ON_DISK`;
export const egoCollectionRecordsUpdateCollectionRecordBodyDataStatusMax = 32;

export const egoCollectionRecordsUpdateCollectionRecordBodyRemarkDefault = ``;
export const egoCollectionRecordsUpdateCollectionRecordBodyRemarkMax = 1000;



export const EgoCollectionRecordsUpdateCollectionRecordBody = zod.object({
  "record_no": zod.string().min(1).max(egoCollectionRecordsUpdateCollectionRecordBodyRecordNoMax),
  "task_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "project_name": zod.string().max(egoCollectionRecordsUpdateCollectionRecordBodyProjectNameMax).default(egoCollectionRecordsUpdateCollectionRecordBodyProjectNameDefault),
  "task_name": zod.string().max(egoCollectionRecordsUpdateCollectionRecordBodyTaskNameMax).default(egoCollectionRecordsUpdateCollectionRecordBodyTaskNameDefault),
  "subtask_name": zod.string().max(egoCollectionRecordsUpdateCollectionRecordBodySubtaskNameMax).default(egoCollectionRecordsUpdateCollectionRecordBodySubtaskNameDefault),
  "kit_name": zod.string().max(egoCollectionRecordsUpdateCollectionRecordBodyKitNameMax).default(egoCollectionRecordsUpdateCollectionRecordBodyKitNameDefault),
  "capture_location": zod.string().max(egoCollectionRecordsUpdateCollectionRecordBodyCaptureLocationMax).default(egoCollectionRecordsUpdateCollectionRecordBodyCaptureLocationDefault),
  "device_serial": zod.string().max(egoCollectionRecordsUpdateCollectionRecordBodyDeviceSerialMax).default(egoCollectionRecordsUpdateCollectionRecordBodyDeviceSerialDefault),
  "operator_username": zod.string().max(egoCollectionRecordsUpdateCollectionRecordBodyOperatorUsernameMax).default(egoCollectionRecordsUpdateCollectionRecordBodyOperatorUsernameDefault),
  "file_name": zod.string().max(egoCollectionRecordsUpdateCollectionRecordBodyFileNameMax).default(egoCollectionRecordsUpdateCollectionRecordBodyFileNameDefault),
  "file_size_bytes": zod.number().min(egoCollectionRecordsUpdateCollectionRecordBodyFileSizeBytesMin).default(egoCollectionRecordsUpdateCollectionRecordBodyFileSizeBytesDefault),
  "duration_seconds": zod.number().min(egoCollectionRecordsUpdateCollectionRecordBodyDurationSecondsMin).default(egoCollectionRecordsUpdateCollectionRecordBodyDurationSecondsDefault),
  "status": zod.string().max(egoCollectionRecordsUpdateCollectionRecordBodyStatusMax).default(egoCollectionRecordsUpdateCollectionRecordBodyStatusDefault),
  "qa_status": zod.string().max(egoCollectionRecordsUpdateCollectionRecordBodyQaStatusMax).default(egoCollectionRecordsUpdateCollectionRecordBodyQaStatusDefault),
  "upload_status": zod.string().max(egoCollectionRecordsUpdateCollectionRecordBodyUploadStatusMax).default(egoCollectionRecordsUpdateCollectionRecordBodyUploadStatusDefault),
  "data_status": zod.string().max(egoCollectionRecordsUpdateCollectionRecordBodyDataStatusMax).default(egoCollectionRecordsUpdateCollectionRecordBodyDataStatusDefault),
  "captured_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "remark": zod.string().max(egoCollectionRecordsUpdateCollectionRecordBodyRemarkMax).default(egoCollectionRecordsUpdateCollectionRecordBodyRemarkDefault)
})

export const egoCollectionRecordsUpdateCollectionRecordResponseRecordNoMax = 128;

export const egoCollectionRecordsUpdateCollectionRecordResponseProjectNameDefault = ``;
export const egoCollectionRecordsUpdateCollectionRecordResponseProjectNameMax = 128;

export const egoCollectionRecordsUpdateCollectionRecordResponseTaskNameDefault = ``;
export const egoCollectionRecordsUpdateCollectionRecordResponseTaskNameMax = 128;

export const egoCollectionRecordsUpdateCollectionRecordResponseSubtaskNameDefault = ``;
export const egoCollectionRecordsUpdateCollectionRecordResponseSubtaskNameMax = 128;

export const egoCollectionRecordsUpdateCollectionRecordResponseKitNameDefault = ``;
export const egoCollectionRecordsUpdateCollectionRecordResponseKitNameMax = 128;

export const egoCollectionRecordsUpdateCollectionRecordResponseCaptureLocationDefault = ``;
export const egoCollectionRecordsUpdateCollectionRecordResponseCaptureLocationMax = 256;

export const egoCollectionRecordsUpdateCollectionRecordResponseDeviceSerialDefault = ``;
export const egoCollectionRecordsUpdateCollectionRecordResponseDeviceSerialMax = 128;

export const egoCollectionRecordsUpdateCollectionRecordResponseOperatorUsernameDefault = ``;
export const egoCollectionRecordsUpdateCollectionRecordResponseOperatorUsernameMax = 128;

export const egoCollectionRecordsUpdateCollectionRecordResponseFileNameDefault = ``;
export const egoCollectionRecordsUpdateCollectionRecordResponseFileNameMax = 256;

export const egoCollectionRecordsUpdateCollectionRecordResponseFileSizeBytesDefault = 0;
export const egoCollectionRecordsUpdateCollectionRecordResponseFileSizeBytesMin = 0;

export const egoCollectionRecordsUpdateCollectionRecordResponseDurationSecondsDefault = 0;
export const egoCollectionRecordsUpdateCollectionRecordResponseDurationSecondsMin = 0;

export const egoCollectionRecordsUpdateCollectionRecordResponseStatusDefault = `COMPLETED`;
export const egoCollectionRecordsUpdateCollectionRecordResponseStatusMax = 32;

export const egoCollectionRecordsUpdateCollectionRecordResponseQaStatusDefault = `PENDING`;
export const egoCollectionRecordsUpdateCollectionRecordResponseQaStatusMax = 32;

export const egoCollectionRecordsUpdateCollectionRecordResponseUploadStatusDefault = `LOCAL`;
export const egoCollectionRecordsUpdateCollectionRecordResponseUploadStatusMax = 32;

export const egoCollectionRecordsUpdateCollectionRecordResponseDataStatusDefault = `ON_DISK`;
export const egoCollectionRecordsUpdateCollectionRecordResponseDataStatusMax = 32;

export const egoCollectionRecordsUpdateCollectionRecordResponseRemarkDefault = ``;
export const egoCollectionRecordsUpdateCollectionRecordResponseRemarkMax = 1000;



export const EgoCollectionRecordsUpdateCollectionRecordResponse = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "record_no": zod.string().min(1).max(egoCollectionRecordsUpdateCollectionRecordResponseRecordNoMax),
  "task_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "project_name": zod.string().max(egoCollectionRecordsUpdateCollectionRecordResponseProjectNameMax).default(egoCollectionRecordsUpdateCollectionRecordResponseProjectNameDefault),
  "task_name": zod.string().max(egoCollectionRecordsUpdateCollectionRecordResponseTaskNameMax).default(egoCollectionRecordsUpdateCollectionRecordResponseTaskNameDefault),
  "subtask_name": zod.string().max(egoCollectionRecordsUpdateCollectionRecordResponseSubtaskNameMax).default(egoCollectionRecordsUpdateCollectionRecordResponseSubtaskNameDefault),
  "kit_name": zod.string().max(egoCollectionRecordsUpdateCollectionRecordResponseKitNameMax).default(egoCollectionRecordsUpdateCollectionRecordResponseKitNameDefault),
  "capture_location": zod.string().max(egoCollectionRecordsUpdateCollectionRecordResponseCaptureLocationMax).default(egoCollectionRecordsUpdateCollectionRecordResponseCaptureLocationDefault),
  "device_serial": zod.string().max(egoCollectionRecordsUpdateCollectionRecordResponseDeviceSerialMax).default(egoCollectionRecordsUpdateCollectionRecordResponseDeviceSerialDefault),
  "operator_username": zod.string().max(egoCollectionRecordsUpdateCollectionRecordResponseOperatorUsernameMax).default(egoCollectionRecordsUpdateCollectionRecordResponseOperatorUsernameDefault),
  "file_name": zod.string().max(egoCollectionRecordsUpdateCollectionRecordResponseFileNameMax).default(egoCollectionRecordsUpdateCollectionRecordResponseFileNameDefault),
  "file_size_bytes": zod.number().min(egoCollectionRecordsUpdateCollectionRecordResponseFileSizeBytesMin).default(egoCollectionRecordsUpdateCollectionRecordResponseFileSizeBytesDefault),
  "duration_seconds": zod.number().min(egoCollectionRecordsUpdateCollectionRecordResponseDurationSecondsMin).default(egoCollectionRecordsUpdateCollectionRecordResponseDurationSecondsDefault),
  "status": zod.string().max(egoCollectionRecordsUpdateCollectionRecordResponseStatusMax).default(egoCollectionRecordsUpdateCollectionRecordResponseStatusDefault),
  "qa_status": zod.string().max(egoCollectionRecordsUpdateCollectionRecordResponseQaStatusMax).default(egoCollectionRecordsUpdateCollectionRecordResponseQaStatusDefault),
  "upload_status": zod.string().max(egoCollectionRecordsUpdateCollectionRecordResponseUploadStatusMax).default(egoCollectionRecordsUpdateCollectionRecordResponseUploadStatusDefault),
  "data_status": zod.string().max(egoCollectionRecordsUpdateCollectionRecordResponseDataStatusMax).default(egoCollectionRecordsUpdateCollectionRecordResponseDataStatusDefault),
  "captured_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "remark": zod.string().max(egoCollectionRecordsUpdateCollectionRecordResponseRemarkMax).default(egoCollectionRecordsUpdateCollectionRecordResponseRemarkDefault),
  "workspace_id": zod.uuid(),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * @summary Delete Collection Record
 */
export const EgoCollectionRecordsDeleteCollectionRecordParams = zod.object({
  "resource_id": zod.uuid()
})

export const EgoCollectionRecordsDeleteCollectionRecordHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const EgoCollectionRecordsDeleteCollectionRecordResponse = zod.object({
  "message": zod.string()
})
