/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Read Collection Scenes
 */
export const egoCollectionScenesReadCollectionScenesQuerySkipDefault = 0;
export const egoCollectionScenesReadCollectionScenesQuerySkipMin = 0;

export const egoCollectionScenesReadCollectionScenesQueryLimitDefault = 20;
export const egoCollectionScenesReadCollectionScenesQueryLimitMax = 500;

export const egoCollectionScenesReadCollectionScenesQueryQOneMax = 128;

export const egoCollectionScenesReadCollectionScenesQueryStatusOneMax = 32;



export const EgoCollectionScenesReadCollectionScenesQueryParams = zod.object({
  "skip": zod.number().min(egoCollectionScenesReadCollectionScenesQuerySkipMin).default(egoCollectionScenesReadCollectionScenesQuerySkipDefault),
  "limit": zod.number().min(1).max(egoCollectionScenesReadCollectionScenesQueryLimitMax).default(egoCollectionScenesReadCollectionScenesQueryLimitDefault),
  "q": zod.union([zod.string().max(egoCollectionScenesReadCollectionScenesQueryQOneMax),zod.null()]).optional(),
  "status": zod.union([zod.string().max(egoCollectionScenesReadCollectionScenesQueryStatusOneMax),zod.null()]).optional()
})

export const EgoCollectionScenesReadCollectionScenesHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoCollectionScenesReadCollectionScenesResponseDataItemNameMax = 64;

export const egoCollectionScenesReadCollectionScenesResponseDataItemDescriptionDefault = ``;
export const egoCollectionScenesReadCollectionScenesResponseDataItemDescriptionMax = 1000;

export const egoCollectionScenesReadCollectionScenesResponseDataItemStatusDefault = `ACTIVE`;
export const egoCollectionScenesReadCollectionScenesResponseDataItemStatusMax = 32;

export const egoCollectionScenesReadCollectionScenesResponseDataItemSortDefault = 1;

export const EgoCollectionScenesReadCollectionScenesResponse = zod.object({
  "count": zod.number(),
  "data": zod.array(zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "name": zod.string().min(1).max(egoCollectionScenesReadCollectionScenesResponseDataItemNameMax),
  "description": zod.string().max(egoCollectionScenesReadCollectionScenesResponseDataItemDescriptionMax).default(egoCollectionScenesReadCollectionScenesResponseDataItemDescriptionDefault),
  "status": zod.string().max(egoCollectionScenesReadCollectionScenesResponseDataItemStatusMax).default(egoCollectionScenesReadCollectionScenesResponseDataItemStatusDefault),
  "sort": zod.number().default(egoCollectionScenesReadCollectionScenesResponseDataItemSortDefault),
  "workspace_id": zod.uuid(),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
}))
})

/**
 * @summary Create Collection Scene
 */
export const EgoCollectionScenesCreateCollectionSceneHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoCollectionScenesCreateCollectionSceneBodyNameMax = 64;

export const egoCollectionScenesCreateCollectionSceneBodyDescriptionDefault = ``;
export const egoCollectionScenesCreateCollectionSceneBodyDescriptionMax = 1000;

export const egoCollectionScenesCreateCollectionSceneBodyStatusDefault = `ACTIVE`;
export const egoCollectionScenesCreateCollectionSceneBodyStatusMax = 32;

export const egoCollectionScenesCreateCollectionSceneBodySortDefault = 1;

export const EgoCollectionScenesCreateCollectionSceneBody = zod.object({
  "name": zod.string().min(1).max(egoCollectionScenesCreateCollectionSceneBodyNameMax),
  "description": zod.string().max(egoCollectionScenesCreateCollectionSceneBodyDescriptionMax).default(egoCollectionScenesCreateCollectionSceneBodyDescriptionDefault),
  "status": zod.string().max(egoCollectionScenesCreateCollectionSceneBodyStatusMax).default(egoCollectionScenesCreateCollectionSceneBodyStatusDefault),
  "sort": zod.number().default(egoCollectionScenesCreateCollectionSceneBodySortDefault)
})

export const egoCollectionScenesCreateCollectionSceneResponseNameMax = 64;

export const egoCollectionScenesCreateCollectionSceneResponseDescriptionDefault = ``;
export const egoCollectionScenesCreateCollectionSceneResponseDescriptionMax = 1000;

export const egoCollectionScenesCreateCollectionSceneResponseStatusDefault = `ACTIVE`;
export const egoCollectionScenesCreateCollectionSceneResponseStatusMax = 32;

export const egoCollectionScenesCreateCollectionSceneResponseSortDefault = 1;

export const EgoCollectionScenesCreateCollectionSceneResponse = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "name": zod.string().min(1).max(egoCollectionScenesCreateCollectionSceneResponseNameMax),
  "description": zod.string().max(egoCollectionScenesCreateCollectionSceneResponseDescriptionMax).default(egoCollectionScenesCreateCollectionSceneResponseDescriptionDefault),
  "status": zod.string().max(egoCollectionScenesCreateCollectionSceneResponseStatusMax).default(egoCollectionScenesCreateCollectionSceneResponseStatusDefault),
  "sort": zod.number().default(egoCollectionScenesCreateCollectionSceneResponseSortDefault),
  "workspace_id": zod.uuid(),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * @summary Update Collection Scene
 */
export const EgoCollectionScenesUpdateCollectionSceneParams = zod.object({
  "resource_id": zod.uuid()
})

export const EgoCollectionScenesUpdateCollectionSceneHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const egoCollectionScenesUpdateCollectionSceneBodyNameMax = 64;

export const egoCollectionScenesUpdateCollectionSceneBodyDescriptionDefault = ``;
export const egoCollectionScenesUpdateCollectionSceneBodyDescriptionMax = 1000;

export const egoCollectionScenesUpdateCollectionSceneBodyStatusDefault = `ACTIVE`;
export const egoCollectionScenesUpdateCollectionSceneBodyStatusMax = 32;

export const egoCollectionScenesUpdateCollectionSceneBodySortDefault = 1;

export const EgoCollectionScenesUpdateCollectionSceneBody = zod.object({
  "name": zod.string().min(1).max(egoCollectionScenesUpdateCollectionSceneBodyNameMax),
  "description": zod.string().max(egoCollectionScenesUpdateCollectionSceneBodyDescriptionMax).default(egoCollectionScenesUpdateCollectionSceneBodyDescriptionDefault),
  "status": zod.string().max(egoCollectionScenesUpdateCollectionSceneBodyStatusMax).default(egoCollectionScenesUpdateCollectionSceneBodyStatusDefault),
  "sort": zod.number().default(egoCollectionScenesUpdateCollectionSceneBodySortDefault)
})

export const egoCollectionScenesUpdateCollectionSceneResponseNameMax = 64;

export const egoCollectionScenesUpdateCollectionSceneResponseDescriptionDefault = ``;
export const egoCollectionScenesUpdateCollectionSceneResponseDescriptionMax = 1000;

export const egoCollectionScenesUpdateCollectionSceneResponseStatusDefault = `ACTIVE`;
export const egoCollectionScenesUpdateCollectionSceneResponseStatusMax = 32;

export const egoCollectionScenesUpdateCollectionSceneResponseSortDefault = 1;

export const EgoCollectionScenesUpdateCollectionSceneResponse = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "name": zod.string().min(1).max(egoCollectionScenesUpdateCollectionSceneResponseNameMax),
  "description": zod.string().max(egoCollectionScenesUpdateCollectionSceneResponseDescriptionMax).default(egoCollectionScenesUpdateCollectionSceneResponseDescriptionDefault),
  "status": zod.string().max(egoCollectionScenesUpdateCollectionSceneResponseStatusMax).default(egoCollectionScenesUpdateCollectionSceneResponseStatusDefault),
  "sort": zod.number().default(egoCollectionScenesUpdateCollectionSceneResponseSortDefault),
  "workspace_id": zod.uuid(),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * @summary Delete Collection Scene
 */
export const EgoCollectionScenesDeleteCollectionSceneParams = zod.object({
  "resource_id": zod.uuid()
})

export const EgoCollectionScenesDeleteCollectionSceneHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const EgoCollectionScenesDeleteCollectionSceneResponse = zod.object({
  "message": zod.string()
})
