/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * @summary Get user's async tasks
 */
export const infraAsyncTasksReadMyAsyncTasksQuerySkipDefault = 0;
export const infraAsyncTasksReadMyAsyncTasksQuerySkipMin = 0;

export const infraAsyncTasksReadMyAsyncTasksQueryLimitDefault = 20;
export const infraAsyncTasksReadMyAsyncTasksQueryLimitMax = 500;



export const InfraAsyncTasksReadMyAsyncTasksQueryParams = zod.object({
  "skip": zod.number().min(infraAsyncTasksReadMyAsyncTasksQuerySkipMin).default(infraAsyncTasksReadMyAsyncTasksQuerySkipDefault),
  "limit": zod.number().max(infraAsyncTasksReadMyAsyncTasksQueryLimitMax).default(infraAsyncTasksReadMyAsyncTasksQueryLimitDefault),
  "status": zod.union([zod.string(),zod.null()]).optional()
})

export const InfraAsyncTasksReadMyAsyncTasksHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const infraAsyncTasksReadMyAsyncTasksResponseDataItemNameOneMax = 100;

export const infraAsyncTasksReadMyAsyncTasksResponseDataItemTaskTypeMax = 50;

export const infraAsyncTasksReadMyAsyncTasksResponseDataItemStatusDefault = `pending`;
export const infraAsyncTasksReadMyAsyncTasksResponseDataItemStatusMax = 50;

export const infraAsyncTasksReadMyAsyncTasksResponseDataItemResultFileUrlOneMax = 1000;



export const InfraAsyncTasksReadMyAsyncTasksResponse = zod.object({
  "count": zod.number(),
  "data": zod.array(zod.object({
  "name": zod.union([zod.string().max(infraAsyncTasksReadMyAsyncTasksResponseDataItemNameOneMax),zod.null()]).optional().describe('Display name shown in task center'),
  "task_type": zod.string().max(infraAsyncTasksReadMyAsyncTasksResponseDataItemTaskTypeMax).describe('Task category, e.g. \'import_opportunity\''),
  "status": zod.string().max(infraAsyncTasksReadMyAsyncTasksResponseDataItemStatusMax).default(infraAsyncTasksReadMyAsyncTasksResponseDataItemStatusDefault).describe('pending|processing|completed|partial_failed|failed|cancelled'),
  "progress": zod.record(zod.string(), zod.unknown()).optional(),
  "result_file_url": zod.union([zod.string().max(infraAsyncTasksReadMyAsyncTasksResponseDataItemResultFileUrlOneMax),zod.null()]).optional(),
  "id": zod.uuid(),
  "created_at": zod.unknown()
}))
})

/**
 * @summary Get a specific async task
 */
export const InfraAsyncTasksReadAsyncTaskParams = zod.object({
  "id": zod.uuid()
})

export const InfraAsyncTasksReadAsyncTaskHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const infraAsyncTasksReadAsyncTaskResponseNameOneMax = 100;

export const infraAsyncTasksReadAsyncTaskResponseTaskTypeMax = 50;

export const infraAsyncTasksReadAsyncTaskResponseStatusDefault = `pending`;
export const infraAsyncTasksReadAsyncTaskResponseStatusMax = 50;

export const infraAsyncTasksReadAsyncTaskResponseResultFileUrlOneMax = 1000;



export const InfraAsyncTasksReadAsyncTaskResponse = zod.object({
  "name": zod.union([zod.string().max(infraAsyncTasksReadAsyncTaskResponseNameOneMax),zod.null()]).optional().describe('Display name shown in task center'),
  "task_type": zod.string().max(infraAsyncTasksReadAsyncTaskResponseTaskTypeMax).describe('Task category, e.g. \'import_opportunity\''),
  "status": zod.string().max(infraAsyncTasksReadAsyncTaskResponseStatusMax).default(infraAsyncTasksReadAsyncTaskResponseStatusDefault).describe('pending|processing|completed|partial_failed|failed|cancelled'),
  "progress": zod.record(zod.string(), zod.unknown()).optional(),
  "result_file_url": zod.union([zod.string().max(infraAsyncTasksReadAsyncTaskResponseResultFileUrlOneMax),zod.null()]).optional(),
  "id": zod.uuid(),
  "created_at": zod.unknown()
})

/**
 * @summary Cancel a specific async task
 */
export const InfraAsyncTasksCancelAsyncTaskParams = zod.object({
  "id": zod.uuid()
})

export const InfraAsyncTasksCancelAsyncTaskHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const infraAsyncTasksCancelAsyncTaskResponseNameOneMax = 100;

export const infraAsyncTasksCancelAsyncTaskResponseTaskTypeMax = 50;

export const infraAsyncTasksCancelAsyncTaskResponseStatusDefault = `pending`;
export const infraAsyncTasksCancelAsyncTaskResponseStatusMax = 50;

export const infraAsyncTasksCancelAsyncTaskResponseResultFileUrlOneMax = 1000;



export const InfraAsyncTasksCancelAsyncTaskResponse = zod.object({
  "name": zod.union([zod.string().max(infraAsyncTasksCancelAsyncTaskResponseNameOneMax),zod.null()]).optional().describe('Display name shown in task center'),
  "task_type": zod.string().max(infraAsyncTasksCancelAsyncTaskResponseTaskTypeMax).describe('Task category, e.g. \'import_opportunity\''),
  "status": zod.string().max(infraAsyncTasksCancelAsyncTaskResponseStatusMax).default(infraAsyncTasksCancelAsyncTaskResponseStatusDefault).describe('pending|processing|completed|partial_failed|failed|cancelled'),
  "progress": zod.record(zod.string(), zod.unknown()).optional(),
  "result_file_url": zod.union([zod.string().max(infraAsyncTasksCancelAsyncTaskResponseResultFileUrlOneMax),zod.null()]).optional(),
  "id": zod.uuid(),
  "created_at": zod.unknown()
})
