/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */

export interface CollectionTaskClaim {
  /** @maxLength 256 */
  location?: string;
  /** @maxLength 1000 */
  target_objects?: string;
  /** @minimum 0 */
  object_count?: number;
}
