/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */

export interface CollectionSceneUpdate {
  /**
     * @minLength 1
     * @maxLength 64
     */
  name: string;
  /** @maxLength 1000 */
  description?: string;
  /** @maxLength 32 */
  status?: string;
  sort?: number;
}
