/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */

export type EgoCollectionTasksReadMyAvailableTasksParams = {
/**
 * @minimum 1
 * @maximum 500
 */
limit?: number;
q?: string | null;
scene_type?: string | null;
task_no?: string | null;
};
