/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */

export interface FieldAuditLogOut {
  id: string;
  action: string;
  created_at: string;
  operator_id?: string | null;
  operator_name?: string | null;
  old_value?: unknown | null;
  new_value?: unknown | null;
}
