/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import type { WorkspaceMemberPublic } from './workspaceMemberPublic';

export interface GenericPageWorkspaceMemberPublic {
  count: number;
  data: WorkspaceMemberPublic[];
}
