/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import type { CloudStoragePublic } from './cloudStoragePublic';

export interface GenericPageCloudStoragePublic {
  count: number;
  data: CloudStoragePublic[];
}
