/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import type { CollectionTaskPublic } from './collectionTaskPublic';

export interface GenericPageCollectionTaskPublic {
  count: number;
  data: CollectionTaskPublic[];
}
