/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import type { ProductKitPublic } from './productKitPublic';

export interface GenericPageProductKitPublic {
  count: number;
  data: ProductKitPublic[];
}
