/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import type { CollectionSopPublic } from './collectionSopPublic';

export interface GenericPageCollectionSopPublic {
  count: number;
  data: CollectionSopPublic[];
}
