/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import type { PhysicalKitPublic } from './physicalKitPublic';

export interface GenericPagePhysicalKitPublic {
  count: number;
  data: PhysicalKitPublic[];
}
