/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */

export interface KitDeviceSlot {
  /**
     * @minLength 1
     * @maxLength 64
     */
  role: string;
  /**
     * @minLength 1
     * @maxLength 128
     */
  label: string;
  /**
     * @minLength 1
     * @maxLength 128
     */
  device_model: string;
  /**
     * @minimum 1
     * @maximum 32
     */
  quantity?: number;
  required?: boolean;
  /**
     * @minimum 0
     * @maximum 32
     */
  channel_count?: number;
  channel_labels?: string[];
  /** @maxLength 128 */
  service_key?: string;
  channel_keys?: string[];
  /** @minimum 0 */
  sort?: number;
}
