/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */

export interface MultipartInitRequest {
  file_name: string;
  file_size: number;
  folder?: string;
}
