/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import type { DeviceBindingPublic } from './deviceBindingPublic';
import type { PhysicalKitPublic } from './physicalKitPublic';
import type { ProductKitPublic } from './productKitPublic';

export interface OperatorTerminalConfig {
  physical_kit?: PhysicalKitPublic | null;
  devices?: DeviceBindingPublic[];
  template?: ProductKitPublic | null;
}
