/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import type { SystemAuditLogPublicDiffPayload } from './systemAuditLogPublicDiffPayload';

export interface SystemAuditLogPublic {
  id: string;
  entity_type: string;
  workspace_id?: string | null;
  operator_id?: string | null;
  operator_name?: string | null;
  entity_id: string;
  action: string;
  diff_payload?: SystemAuditLogPublicDiffPayload;
  created_at: string;
}
