/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */

export interface UpdatePassword {
  /**
     * @minLength 5
     * @maxLength 128
     */
  current_password: string;
  /**
     * @minLength 5
     * @maxLength 128
     */
  new_password: string;
}
