/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  BodyLoginLoginAccessToken,
  HTTPValidationError,
  Message,
  NewPassword,
  Token,
  UserPublic
} from '../schemas';

import { customFetch } from '../../lib/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * OAuth2 compatible token login, get an access token for future requests
 * @summary Login Access Token
 */
export type loginLoginAccessTokenResponse200 = {
  data: Token
  status: 200
}

export type loginLoginAccessTokenResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type loginLoginAccessTokenResponseSuccess = (loginLoginAccessTokenResponse200) & {
  headers: Headers;
};
export type loginLoginAccessTokenResponseError = (loginLoginAccessTokenResponse422) & {
  headers: Headers;
};

export type loginLoginAccessTokenResponse = (loginLoginAccessTokenResponseSuccess | loginLoginAccessTokenResponseError)

export const getLoginLoginAccessTokenUrl = () => {




  return `/api/v1/login/access-token`
}

export const loginLoginAccessToken = async (bodyLoginLoginAccessToken: BodyLoginLoginAccessToken, options?: RequestInit): Promise<loginLoginAccessTokenResponse> => {
    const formUrlEncoded = new URLSearchParams();
if(bodyLoginLoginAccessToken.grant_type !== undefined && bodyLoginLoginAccessToken.grant_type !== null) {
 formUrlEncoded.append(`grant_type`, bodyLoginLoginAccessToken.grant_type);
 }
formUrlEncoded.append(`username`, bodyLoginLoginAccessToken.username);
formUrlEncoded.append(`password`, bodyLoginLoginAccessToken.password);
if(bodyLoginLoginAccessToken.scope !== undefined) {
 formUrlEncoded.append(`scope`, bodyLoginLoginAccessToken.scope);
 }
if(bodyLoginLoginAccessToken.client_id !== undefined && bodyLoginLoginAccessToken.client_id !== null) {
 formUrlEncoded.append(`client_id`, bodyLoginLoginAccessToken.client_id);
 }
if(bodyLoginLoginAccessToken.client_secret !== undefined && bodyLoginLoginAccessToken.client_secret !== null) {
 formUrlEncoded.append(`client_secret`, bodyLoginLoginAccessToken.client_secret);
 }

  return customFetch<loginLoginAccessTokenResponse>(getLoginLoginAccessTokenUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body:
      formUrlEncoded,
  }
);}




export const getLoginLoginAccessTokenMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginLoginAccessToken>>, TError,{data: BodyLoginLoginAccessToken}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof loginLoginAccessToken>>, TError,{data: BodyLoginLoginAccessToken}, TContext> => {

const mutationKey = ['loginLoginAccessToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginLoginAccessToken>>, {data: BodyLoginLoginAccessToken}> = (props) => {
          const {data} = props ?? {};

          return  loginLoginAccessToken(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginLoginAccessTokenMutationResult = NonNullable<Awaited<ReturnType<typeof loginLoginAccessToken>>>
    export type LoginLoginAccessTokenMutationBody = BodyLoginLoginAccessToken
    export type LoginLoginAccessTokenMutationError = HTTPValidationError

    /**
 * @summary Login Access Token
 */
export const useLoginLoginAccessToken = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginLoginAccessToken>>, TError,{data: BodyLoginLoginAccessToken}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginLoginAccessToken>>,
        TError,
        {data: BodyLoginLoginAccessToken},
        TContext
      > => {
      return useMutation(getLoginLoginAccessTokenMutationOptions(options), queryClient);
    }
    /**
 * Test access token
 * @summary Test Token
 */
export type loginTestTokenResponse200 = {
  data: UserPublic
  status: 200
}

export type loginTestTokenResponseSuccess = (loginTestTokenResponse200) & {
  headers: Headers;
};
;

export type loginTestTokenResponse = (loginTestTokenResponseSuccess)

export const getLoginTestTokenUrl = () => {




  return `/api/v1/login/test-token`
}

export const loginTestToken = async ( options?: RequestInit): Promise<loginTestTokenResponse> => {

  return customFetch<loginTestTokenResponse>(getLoginTestTokenUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getLoginTestTokenMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginTestToken>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof loginTestToken>>, TError,void, TContext> => {

const mutationKey = ['loginTestToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginTestToken>>, void> = () => {


          return  loginTestToken(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginTestTokenMutationResult = NonNullable<Awaited<ReturnType<typeof loginTestToken>>>

    export type LoginTestTokenMutationError = unknown

    /**
 * @summary Test Token
 */
export const useLoginTestToken = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginTestToken>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginTestToken>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getLoginTestTokenMutationOptions(options), queryClient);
    }
    /**
 * Password Recovery — generates a reset token.
Token delivery (email / SMS) is handled externally.
 * @summary Recover Password
 */
export type loginRecoverPasswordResponse200 = {
  data: Message
  status: 200
}

export type loginRecoverPasswordResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type loginRecoverPasswordResponseSuccess = (loginRecoverPasswordResponse200) & {
  headers: Headers;
};
export type loginRecoverPasswordResponseError = (loginRecoverPasswordResponse422) & {
  headers: Headers;
};

export type loginRecoverPasswordResponse = (loginRecoverPasswordResponseSuccess | loginRecoverPasswordResponseError)

export const getLoginRecoverPasswordUrl = (username: string,) => {




  return `/api/v1/password-recovery/${username}`
}

export const loginRecoverPassword = async (username: string, options?: RequestInit): Promise<loginRecoverPasswordResponse> => {

  return customFetch<loginRecoverPasswordResponse>(getLoginRecoverPasswordUrl(username),
  {
    ...options,
    method: 'POST'


  }
);}




export const getLoginRecoverPasswordMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginRecoverPassword>>, TError,{username: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof loginRecoverPassword>>, TError,{username: string}, TContext> => {

const mutationKey = ['loginRecoverPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginRecoverPassword>>, {username: string}> = (props) => {
          const {username} = props ?? {};

          return  loginRecoverPassword(username,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginRecoverPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof loginRecoverPassword>>>

    export type LoginRecoverPasswordMutationError = HTTPValidationError

    /**
 * @summary Recover Password
 */
export const useLoginRecoverPassword = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginRecoverPassword>>, TError,{username: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginRecoverPassword>>,
        TError,
        {username: string},
        TContext
      > => {
      return useMutation(getLoginRecoverPasswordMutationOptions(options), queryClient);
    }
    /**
 * Reset password
 * @summary Reset Password
 */
export type loginResetPasswordResponse200 = {
  data: Message
  status: 200
}

export type loginResetPasswordResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type loginResetPasswordResponseSuccess = (loginResetPasswordResponse200) & {
  headers: Headers;
};
export type loginResetPasswordResponseError = (loginResetPasswordResponse422) & {
  headers: Headers;
};

export type loginResetPasswordResponse = (loginResetPasswordResponseSuccess | loginResetPasswordResponseError)

export const getLoginResetPasswordUrl = () => {




  return `/api/v1/reset-password/`
}

export const loginResetPassword = async (newPassword: NewPassword, options?: RequestInit): Promise<loginResetPasswordResponse> => {

  return customFetch<loginResetPasswordResponse>(getLoginResetPasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      newPassword,)
  }
);}




export const getLoginResetPasswordMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginResetPassword>>, TError,{data: NewPassword}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof loginResetPassword>>, TError,{data: NewPassword}, TContext> => {

const mutationKey = ['loginResetPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginResetPassword>>, {data: NewPassword}> = (props) => {
          const {data} = props ?? {};

          return  loginResetPassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof loginResetPassword>>>
    export type LoginResetPasswordMutationBody = NewPassword
    export type LoginResetPasswordMutationError = HTTPValidationError

    /**
 * @summary Reset Password
 */
export const useLoginResetPassword = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginResetPassword>>, TError,{data: NewPassword}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginResetPassword>>,
        TError,
        {data: NewPassword},
        TContext
      > => {
      return useMutation(getLoginResetPasswordMutationOptions(options), queryClient);
    }
