/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EgoProductKitsReadProductKitsParams,
  GenericPageProductKitPublic,
  HTTPValidationError,
  Message,
  ProductKitCreate,
  ProductKitPublic,
  ProductKitUpdate
} from '../schemas';

import { customFetch } from '../../lib/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Read Product Kits
 */
export type egoProductKitsReadProductKitsResponse200 = {
  data: GenericPageProductKitPublic
  status: 200
}

export type egoProductKitsReadProductKitsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoProductKitsReadProductKitsResponseSuccess = (egoProductKitsReadProductKitsResponse200) & {
  headers: Headers;
};
export type egoProductKitsReadProductKitsResponseError = (egoProductKitsReadProductKitsResponse422) & {
  headers: Headers;
};

export type egoProductKitsReadProductKitsResponse = (egoProductKitsReadProductKitsResponseSuccess | egoProductKitsReadProductKitsResponseError)

export const getEgoProductKitsReadProductKitsUrl = (params?: EgoProductKitsReadProductKitsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/ego/product-kits/?${stringifiedParams}` : `/api/v1/ego/product-kits/`
}

export const egoProductKitsReadProductKits = async (params?: EgoProductKitsReadProductKitsParams, options?: RequestInit): Promise<egoProductKitsReadProductKitsResponse> => {

  return customFetch<egoProductKitsReadProductKitsResponse>(getEgoProductKitsReadProductKitsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getEgoProductKitsReadProductKitsQueryKey = (params?: EgoProductKitsReadProductKitsParams,) => {
    return [
    `/api/v1/ego/product-kits/`, ...(params ? [params] : [])
    ] as const;
    }


export const getEgoProductKitsReadProductKitsQueryOptions = <TData = Awaited<ReturnType<typeof egoProductKitsReadProductKits>>, TError = HTTPValidationError>(params?: EgoProductKitsReadProductKitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoProductKitsReadProductKits>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEgoProductKitsReadProductKitsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof egoProductKitsReadProductKits>>> = ({ signal }) => egoProductKitsReadProductKits(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof egoProductKitsReadProductKits>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EgoProductKitsReadProductKitsQueryResult = NonNullable<Awaited<ReturnType<typeof egoProductKitsReadProductKits>>>
export type EgoProductKitsReadProductKitsQueryError = HTTPValidationError


export function useEgoProductKitsReadProductKits<TData = Awaited<ReturnType<typeof egoProductKitsReadProductKits>>, TError = HTTPValidationError>(
 params: undefined |  EgoProductKitsReadProductKitsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoProductKitsReadProductKits>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof egoProductKitsReadProductKits>>,
          TError,
          Awaited<ReturnType<typeof egoProductKitsReadProductKits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEgoProductKitsReadProductKits<TData = Awaited<ReturnType<typeof egoProductKitsReadProductKits>>, TError = HTTPValidationError>(
 params?: EgoProductKitsReadProductKitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoProductKitsReadProductKits>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof egoProductKitsReadProductKits>>,
          TError,
          Awaited<ReturnType<typeof egoProductKitsReadProductKits>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEgoProductKitsReadProductKits<TData = Awaited<ReturnType<typeof egoProductKitsReadProductKits>>, TError = HTTPValidationError>(
 params?: EgoProductKitsReadProductKitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoProductKitsReadProductKits>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Product Kits
 */

export function useEgoProductKitsReadProductKits<TData = Awaited<ReturnType<typeof egoProductKitsReadProductKits>>, TError = HTTPValidationError>(
 params?: EgoProductKitsReadProductKitsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoProductKitsReadProductKits>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEgoProductKitsReadProductKitsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Product Kit
 */
export type egoProductKitsCreateProductKitResponse200 = {
  data: ProductKitPublic
  status: 200
}

export type egoProductKitsCreateProductKitResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoProductKitsCreateProductKitResponseSuccess = (egoProductKitsCreateProductKitResponse200) & {
  headers: Headers;
};
export type egoProductKitsCreateProductKitResponseError = (egoProductKitsCreateProductKitResponse422) & {
  headers: Headers;
};

export type egoProductKitsCreateProductKitResponse = (egoProductKitsCreateProductKitResponseSuccess | egoProductKitsCreateProductKitResponseError)

export const getEgoProductKitsCreateProductKitUrl = () => {




  return `/api/v1/ego/product-kits/`
}

export const egoProductKitsCreateProductKit = async (productKitCreate: ProductKitCreate, options?: RequestInit): Promise<egoProductKitsCreateProductKitResponse> => {

  return customFetch<egoProductKitsCreateProductKitResponse>(getEgoProductKitsCreateProductKitUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      productKitCreate,)
  }
);}




export const getEgoProductKitsCreateProductKitMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoProductKitsCreateProductKit>>, TError,{data: ProductKitCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoProductKitsCreateProductKit>>, TError,{data: ProductKitCreate}, TContext> => {

const mutationKey = ['egoProductKitsCreateProductKit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoProductKitsCreateProductKit>>, {data: ProductKitCreate}> = (props) => {
          const {data} = props ?? {};

          return  egoProductKitsCreateProductKit(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoProductKitsCreateProductKitMutationResult = NonNullable<Awaited<ReturnType<typeof egoProductKitsCreateProductKit>>>
    export type EgoProductKitsCreateProductKitMutationBody = ProductKitCreate
    export type EgoProductKitsCreateProductKitMutationError = HTTPValidationError

    /**
 * @summary Create Product Kit
 */
export const useEgoProductKitsCreateProductKit = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoProductKitsCreateProductKit>>, TError,{data: ProductKitCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoProductKitsCreateProductKit>>,
        TError,
        {data: ProductKitCreate},
        TContext
      > => {
      return useMutation(getEgoProductKitsCreateProductKitMutationOptions(options), queryClient);
    }
    /**
 * @summary Update Product Kit
 */
export type egoProductKitsUpdateProductKitResponse200 = {
  data: ProductKitPublic
  status: 200
}

export type egoProductKitsUpdateProductKitResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoProductKitsUpdateProductKitResponseSuccess = (egoProductKitsUpdateProductKitResponse200) & {
  headers: Headers;
};
export type egoProductKitsUpdateProductKitResponseError = (egoProductKitsUpdateProductKitResponse422) & {
  headers: Headers;
};

export type egoProductKitsUpdateProductKitResponse = (egoProductKitsUpdateProductKitResponseSuccess | egoProductKitsUpdateProductKitResponseError)

export const getEgoProductKitsUpdateProductKitUrl = (resourceId: string,) => {




  return `/api/v1/ego/product-kits/${resourceId}`
}

export const egoProductKitsUpdateProductKit = async (resourceId: string,
    productKitUpdate: ProductKitUpdate, options?: RequestInit): Promise<egoProductKitsUpdateProductKitResponse> => {

  return customFetch<egoProductKitsUpdateProductKitResponse>(getEgoProductKitsUpdateProductKitUrl(resourceId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      productKitUpdate,)
  }
);}




export const getEgoProductKitsUpdateProductKitMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoProductKitsUpdateProductKit>>, TError,{resourceId: string;data: ProductKitUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoProductKitsUpdateProductKit>>, TError,{resourceId: string;data: ProductKitUpdate}, TContext> => {

const mutationKey = ['egoProductKitsUpdateProductKit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoProductKitsUpdateProductKit>>, {resourceId: string;data: ProductKitUpdate}> = (props) => {
          const {resourceId,data} = props ?? {};

          return  egoProductKitsUpdateProductKit(resourceId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoProductKitsUpdateProductKitMutationResult = NonNullable<Awaited<ReturnType<typeof egoProductKitsUpdateProductKit>>>
    export type EgoProductKitsUpdateProductKitMutationBody = ProductKitUpdate
    export type EgoProductKitsUpdateProductKitMutationError = HTTPValidationError

    /**
 * @summary Update Product Kit
 */
export const useEgoProductKitsUpdateProductKit = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoProductKitsUpdateProductKit>>, TError,{resourceId: string;data: ProductKitUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoProductKitsUpdateProductKit>>,
        TError,
        {resourceId: string;data: ProductKitUpdate},
        TContext
      > => {
      return useMutation(getEgoProductKitsUpdateProductKitMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Product Kit
 */
export type egoProductKitsDeleteProductKitResponse200 = {
  data: Message
  status: 200
}

export type egoProductKitsDeleteProductKitResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoProductKitsDeleteProductKitResponseSuccess = (egoProductKitsDeleteProductKitResponse200) & {
  headers: Headers;
};
export type egoProductKitsDeleteProductKitResponseError = (egoProductKitsDeleteProductKitResponse422) & {
  headers: Headers;
};

export type egoProductKitsDeleteProductKitResponse = (egoProductKitsDeleteProductKitResponseSuccess | egoProductKitsDeleteProductKitResponseError)

export const getEgoProductKitsDeleteProductKitUrl = (resourceId: string,) => {




  return `/api/v1/ego/product-kits/${resourceId}`
}

export const egoProductKitsDeleteProductKit = async (resourceId: string, options?: RequestInit): Promise<egoProductKitsDeleteProductKitResponse> => {

  return customFetch<egoProductKitsDeleteProductKitResponse>(getEgoProductKitsDeleteProductKitUrl(resourceId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getEgoProductKitsDeleteProductKitMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoProductKitsDeleteProductKit>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoProductKitsDeleteProductKit>>, TError,{resourceId: string}, TContext> => {

const mutationKey = ['egoProductKitsDeleteProductKit'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoProductKitsDeleteProductKit>>, {resourceId: string}> = (props) => {
          const {resourceId} = props ?? {};

          return  egoProductKitsDeleteProductKit(resourceId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoProductKitsDeleteProductKitMutationResult = NonNullable<Awaited<ReturnType<typeof egoProductKitsDeleteProductKit>>>

    export type EgoProductKitsDeleteProductKitMutationError = HTTPValidationError

    /**
 * @summary Delete Product Kit
 */
export const useEgoProductKitsDeleteProductKit = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoProductKitsDeleteProductKit>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoProductKitsDeleteProductKit>>,
        TError,
        {resourceId: string},
        TContext
      > => {
      return useMutation(getEgoProductKitsDeleteProductKitMutationOptions(options), queryClient);
    }
