/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BusinessLineCreate,
  BusinessLinePublic,
  BusinessLineTreeNode,
  BusinessLineUpdate,
  GenericPageBusinessLinePublic,
  HTTPValidationError,
  Message,
  WorkspaceBusinessLinesReadBusinessLinesParams,
  WorkspaceBusinessLinesReadBusinessLinesTreeParams
} from '../schemas';

import { customFetch } from '../../lib/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Get a paginated flat list of business lines.
Supports filtering by name and status.
 * @summary Read Business Lines
 */
export type workspaceBusinessLinesReadBusinessLinesResponse200 = {
  data: GenericPageBusinessLinePublic
  status: 200
}

export type workspaceBusinessLinesReadBusinessLinesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type workspaceBusinessLinesReadBusinessLinesResponseSuccess = (workspaceBusinessLinesReadBusinessLinesResponse200) & {
  headers: Headers;
};
export type workspaceBusinessLinesReadBusinessLinesResponseError = (workspaceBusinessLinesReadBusinessLinesResponse422) & {
  headers: Headers;
};

export type workspaceBusinessLinesReadBusinessLinesResponse = (workspaceBusinessLinesReadBusinessLinesResponseSuccess | workspaceBusinessLinesReadBusinessLinesResponseError)

export const getWorkspaceBusinessLinesReadBusinessLinesUrl = (params?: WorkspaceBusinessLinesReadBusinessLinesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/workspace/business-lines/?${stringifiedParams}` : `/api/v1/workspace/business-lines/`
}

export const workspaceBusinessLinesReadBusinessLines = async (params?: WorkspaceBusinessLinesReadBusinessLinesParams, options?: RequestInit): Promise<workspaceBusinessLinesReadBusinessLinesResponse> => {

  return customFetch<workspaceBusinessLinesReadBusinessLinesResponse>(getWorkspaceBusinessLinesReadBusinessLinesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getWorkspaceBusinessLinesReadBusinessLinesQueryKey = (params?: WorkspaceBusinessLinesReadBusinessLinesParams,) => {
    return [
    `/api/v1/workspace/business-lines/`, ...(params ? [params] : [])
    ] as const;
    }


export const getWorkspaceBusinessLinesReadBusinessLinesQueryOptions = <TData = Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLines>>, TError = HTTPValidationError>(params?: WorkspaceBusinessLinesReadBusinessLinesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLines>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWorkspaceBusinessLinesReadBusinessLinesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLines>>> = ({ signal }) => workspaceBusinessLinesReadBusinessLines(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLines>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WorkspaceBusinessLinesReadBusinessLinesQueryResult = NonNullable<Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLines>>>
export type WorkspaceBusinessLinesReadBusinessLinesQueryError = HTTPValidationError


export function useWorkspaceBusinessLinesReadBusinessLines<TData = Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLines>>, TError = HTTPValidationError>(
 params: undefined |  WorkspaceBusinessLinesReadBusinessLinesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLines>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLines>>,
          TError,
          Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLines>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspaceBusinessLinesReadBusinessLines<TData = Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLines>>, TError = HTTPValidationError>(
 params?: WorkspaceBusinessLinesReadBusinessLinesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLines>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLines>>,
          TError,
          Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLines>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspaceBusinessLinesReadBusinessLines<TData = Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLines>>, TError = HTTPValidationError>(
 params?: WorkspaceBusinessLinesReadBusinessLinesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLines>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Business Lines
 */

export function useWorkspaceBusinessLinesReadBusinessLines<TData = Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLines>>, TError = HTTPValidationError>(
 params?: WorkspaceBusinessLinesReadBusinessLinesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLines>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWorkspaceBusinessLinesReadBusinessLinesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create new business line. Superuser only since it is usually synced.
 * @summary Create Business Line
 */
export type workspaceBusinessLinesCreateBusinessLineResponse200 = {
  data: BusinessLinePublic
  status: 200
}

export type workspaceBusinessLinesCreateBusinessLineResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type workspaceBusinessLinesCreateBusinessLineResponseSuccess = (workspaceBusinessLinesCreateBusinessLineResponse200) & {
  headers: Headers;
};
export type workspaceBusinessLinesCreateBusinessLineResponseError = (workspaceBusinessLinesCreateBusinessLineResponse422) & {
  headers: Headers;
};

export type workspaceBusinessLinesCreateBusinessLineResponse = (workspaceBusinessLinesCreateBusinessLineResponseSuccess | workspaceBusinessLinesCreateBusinessLineResponseError)

export const getWorkspaceBusinessLinesCreateBusinessLineUrl = () => {




  return `/api/v1/workspace/business-lines/`
}

export const workspaceBusinessLinesCreateBusinessLine = async (businessLineCreate: BusinessLineCreate, options?: RequestInit): Promise<workspaceBusinessLinesCreateBusinessLineResponse> => {

  return customFetch<workspaceBusinessLinesCreateBusinessLineResponse>(getWorkspaceBusinessLinesCreateBusinessLineUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      businessLineCreate,)
  }
);}




export const getWorkspaceBusinessLinesCreateBusinessLineMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspaceBusinessLinesCreateBusinessLine>>, TError,{data: BusinessLineCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof workspaceBusinessLinesCreateBusinessLine>>, TError,{data: BusinessLineCreate}, TContext> => {

const mutationKey = ['workspaceBusinessLinesCreateBusinessLine'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof workspaceBusinessLinesCreateBusinessLine>>, {data: BusinessLineCreate}> = (props) => {
          const {data} = props ?? {};

          return  workspaceBusinessLinesCreateBusinessLine(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WorkspaceBusinessLinesCreateBusinessLineMutationResult = NonNullable<Awaited<ReturnType<typeof workspaceBusinessLinesCreateBusinessLine>>>
    export type WorkspaceBusinessLinesCreateBusinessLineMutationBody = BusinessLineCreate
    export type WorkspaceBusinessLinesCreateBusinessLineMutationError = HTTPValidationError

    /**
 * @summary Create Business Line
 */
export const useWorkspaceBusinessLinesCreateBusinessLine = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspaceBusinessLinesCreateBusinessLine>>, TError,{data: BusinessLineCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof workspaceBusinessLinesCreateBusinessLine>>,
        TError,
        {data: BusinessLineCreate},
        TContext
      > => {
      return useMutation(getWorkspaceBusinessLinesCreateBusinessLineMutationOptions(options), queryClient);
    }
    /**
 * Get completely unpaginated business line tree.
 * @summary Read Business Lines Tree
 */
export type workspaceBusinessLinesReadBusinessLinesTreeResponse200 = {
  data: BusinessLineTreeNode[]
  status: 200
}

export type workspaceBusinessLinesReadBusinessLinesTreeResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type workspaceBusinessLinesReadBusinessLinesTreeResponseSuccess = (workspaceBusinessLinesReadBusinessLinesTreeResponse200) & {
  headers: Headers;
};
export type workspaceBusinessLinesReadBusinessLinesTreeResponseError = (workspaceBusinessLinesReadBusinessLinesTreeResponse422) & {
  headers: Headers;
};

export type workspaceBusinessLinesReadBusinessLinesTreeResponse = (workspaceBusinessLinesReadBusinessLinesTreeResponseSuccess | workspaceBusinessLinesReadBusinessLinesTreeResponseError)

export const getWorkspaceBusinessLinesReadBusinessLinesTreeUrl = (params?: WorkspaceBusinessLinesReadBusinessLinesTreeParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/workspace/business-lines/tree?${stringifiedParams}` : `/api/v1/workspace/business-lines/tree`
}

export const workspaceBusinessLinesReadBusinessLinesTree = async (params?: WorkspaceBusinessLinesReadBusinessLinesTreeParams, options?: RequestInit): Promise<workspaceBusinessLinesReadBusinessLinesTreeResponse> => {

  return customFetch<workspaceBusinessLinesReadBusinessLinesTreeResponse>(getWorkspaceBusinessLinesReadBusinessLinesTreeUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getWorkspaceBusinessLinesReadBusinessLinesTreeQueryKey = (params?: WorkspaceBusinessLinesReadBusinessLinesTreeParams,) => {
    return [
    `/api/v1/workspace/business-lines/tree`, ...(params ? [params] : [])
    ] as const;
    }


export const getWorkspaceBusinessLinesReadBusinessLinesTreeQueryOptions = <TData = Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLinesTree>>, TError = HTTPValidationError>(params?: WorkspaceBusinessLinesReadBusinessLinesTreeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLinesTree>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getWorkspaceBusinessLinesReadBusinessLinesTreeQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLinesTree>>> = ({ signal }) => workspaceBusinessLinesReadBusinessLinesTree(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLinesTree>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type WorkspaceBusinessLinesReadBusinessLinesTreeQueryResult = NonNullable<Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLinesTree>>>
export type WorkspaceBusinessLinesReadBusinessLinesTreeQueryError = HTTPValidationError


export function useWorkspaceBusinessLinesReadBusinessLinesTree<TData = Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLinesTree>>, TError = HTTPValidationError>(
 params: undefined |  WorkspaceBusinessLinesReadBusinessLinesTreeParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLinesTree>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLinesTree>>,
          TError,
          Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLinesTree>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspaceBusinessLinesReadBusinessLinesTree<TData = Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLinesTree>>, TError = HTTPValidationError>(
 params?: WorkspaceBusinessLinesReadBusinessLinesTreeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLinesTree>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLinesTree>>,
          TError,
          Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLinesTree>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useWorkspaceBusinessLinesReadBusinessLinesTree<TData = Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLinesTree>>, TError = HTTPValidationError>(
 params?: WorkspaceBusinessLinesReadBusinessLinesTreeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLinesTree>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Business Lines Tree
 */

export function useWorkspaceBusinessLinesReadBusinessLinesTree<TData = Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLinesTree>>, TError = HTTPValidationError>(
 params?: WorkspaceBusinessLinesReadBusinessLinesTreeParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof workspaceBusinessLinesReadBusinessLinesTree>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getWorkspaceBusinessLinesReadBusinessLinesTreeQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Update a business line. Superuser only.
 * @summary Update Business Line
 */
export type workspaceBusinessLinesUpdateBusinessLineResponse200 = {
  data: BusinessLinePublic
  status: 200
}

export type workspaceBusinessLinesUpdateBusinessLineResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type workspaceBusinessLinesUpdateBusinessLineResponseSuccess = (workspaceBusinessLinesUpdateBusinessLineResponse200) & {
  headers: Headers;
};
export type workspaceBusinessLinesUpdateBusinessLineResponseError = (workspaceBusinessLinesUpdateBusinessLineResponse422) & {
  headers: Headers;
};

export type workspaceBusinessLinesUpdateBusinessLineResponse = (workspaceBusinessLinesUpdateBusinessLineResponseSuccess | workspaceBusinessLinesUpdateBusinessLineResponseError)

export const getWorkspaceBusinessLinesUpdateBusinessLineUrl = (businessLineId: string,) => {




  return `/api/v1/workspace/business-lines/${businessLineId}`
}

export const workspaceBusinessLinesUpdateBusinessLine = async (businessLineId: string,
    businessLineUpdate: BusinessLineUpdate, options?: RequestInit): Promise<workspaceBusinessLinesUpdateBusinessLineResponse> => {

  return customFetch<workspaceBusinessLinesUpdateBusinessLineResponse>(getWorkspaceBusinessLinesUpdateBusinessLineUrl(businessLineId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      businessLineUpdate,)
  }
);}




export const getWorkspaceBusinessLinesUpdateBusinessLineMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspaceBusinessLinesUpdateBusinessLine>>, TError,{businessLineId: string;data: BusinessLineUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof workspaceBusinessLinesUpdateBusinessLine>>, TError,{businessLineId: string;data: BusinessLineUpdate}, TContext> => {

const mutationKey = ['workspaceBusinessLinesUpdateBusinessLine'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof workspaceBusinessLinesUpdateBusinessLine>>, {businessLineId: string;data: BusinessLineUpdate}> = (props) => {
          const {businessLineId,data} = props ?? {};

          return  workspaceBusinessLinesUpdateBusinessLine(businessLineId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WorkspaceBusinessLinesUpdateBusinessLineMutationResult = NonNullable<Awaited<ReturnType<typeof workspaceBusinessLinesUpdateBusinessLine>>>
    export type WorkspaceBusinessLinesUpdateBusinessLineMutationBody = BusinessLineUpdate
    export type WorkspaceBusinessLinesUpdateBusinessLineMutationError = HTTPValidationError

    /**
 * @summary Update Business Line
 */
export const useWorkspaceBusinessLinesUpdateBusinessLine = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspaceBusinessLinesUpdateBusinessLine>>, TError,{businessLineId: string;data: BusinessLineUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof workspaceBusinessLinesUpdateBusinessLine>>,
        TError,
        {businessLineId: string;data: BusinessLineUpdate},
        TContext
      > => {
      return useMutation(getWorkspaceBusinessLinesUpdateBusinessLineMutationOptions(options), queryClient);
    }
    /**
 * Delete a business line. Rejects if children exist.
 * @summary Delete Business Line
 */
export type workspaceBusinessLinesDeleteBusinessLineResponse200 = {
  data: Message
  status: 200
}

export type workspaceBusinessLinesDeleteBusinessLineResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type workspaceBusinessLinesDeleteBusinessLineResponseSuccess = (workspaceBusinessLinesDeleteBusinessLineResponse200) & {
  headers: Headers;
};
export type workspaceBusinessLinesDeleteBusinessLineResponseError = (workspaceBusinessLinesDeleteBusinessLineResponse422) & {
  headers: Headers;
};

export type workspaceBusinessLinesDeleteBusinessLineResponse = (workspaceBusinessLinesDeleteBusinessLineResponseSuccess | workspaceBusinessLinesDeleteBusinessLineResponseError)

export const getWorkspaceBusinessLinesDeleteBusinessLineUrl = (businessLineId: string,) => {




  return `/api/v1/workspace/business-lines/${businessLineId}`
}

export const workspaceBusinessLinesDeleteBusinessLine = async (businessLineId: string, options?: RequestInit): Promise<workspaceBusinessLinesDeleteBusinessLineResponse> => {

  return customFetch<workspaceBusinessLinesDeleteBusinessLineResponse>(getWorkspaceBusinessLinesDeleteBusinessLineUrl(businessLineId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getWorkspaceBusinessLinesDeleteBusinessLineMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspaceBusinessLinesDeleteBusinessLine>>, TError,{businessLineId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof workspaceBusinessLinesDeleteBusinessLine>>, TError,{businessLineId: string}, TContext> => {

const mutationKey = ['workspaceBusinessLinesDeleteBusinessLine'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof workspaceBusinessLinesDeleteBusinessLine>>, {businessLineId: string}> = (props) => {
          const {businessLineId} = props ?? {};

          return  workspaceBusinessLinesDeleteBusinessLine(businessLineId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type WorkspaceBusinessLinesDeleteBusinessLineMutationResult = NonNullable<Awaited<ReturnType<typeof workspaceBusinessLinesDeleteBusinessLine>>>

    export type WorkspaceBusinessLinesDeleteBusinessLineMutationError = HTTPValidationError

    /**
 * @summary Delete Business Line
 */
export const useWorkspaceBusinessLinesDeleteBusinessLine = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof workspaceBusinessLinesDeleteBusinessLine>>, TError,{businessLineId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof workspaceBusinessLinesDeleteBusinessLine>>,
        TError,
        {businessLineId: string},
        TContext
      > => {
      return useMutation(getWorkspaceBusinessLinesDeleteBusinessLineMutationOptions(options), queryClient);
    }
