import { Check, ChevronRight } from 'lucide-react'
import type { SelectableProduct } from '../../../app/product'
import { cn } from '../../../shared/lib/cn'
import { Button } from '@/components/ui/button'
import { PageHeader } from '../../../shared/ui/DevicePrimitives'
import { Badge } from '@/components/ui/badge'
import { Card } from '@/components/ui/card'
import { deviceTone, PRODUCTS, PRODUCT_TONES, type DeviceCard } from '../homeModel'

export function MobileProductSelection({ onSelectProduct }: { onSelectProduct: (product: SelectableProduct) => void }) {
  return <div className="page flex min-h-full flex-col gap-4 pb-6"><PageHeader title="选择产品" /><div className="px-1"><span className="text-xs font-bold text-sky-500">开始采集</span><h2 className="mt-1 text-2xl font-extrabold">选择本次使用的套件</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">不同套件对应不同的相机和传感器组合，进入后可查看连接状态。</p></div><section className="grid gap-3 md:grid-cols-2">{PRODUCTS.map(product => <button key={product.name} className={cn('grid min-h-32 grid-cols-[auto_1fr_auto] items-center gap-3 rounded-xl border bg-card p-4 text-left text-foreground shadow-sm transition-colors', PRODUCT_TONES[product.name].card, product.disabled && 'opacity-45')} disabled={product.disabled} onClick={() => !product.disabled && onSelectProduct(product.name as SelectableProduct)}><span className={cn('grid size-12 place-items-center rounded-lg [&>svg]:size-6', PRODUCT_TONES[product.name].icon)}>{product.icon}</span><span className="grid min-w-0 gap-1"><strong className="text-lg">{product.name}</strong><small className="text-xs leading-5 text-muted-foreground">{product.note}</small></span>{product.disabled ? <Badge>未开发</Badge> : <ChevronRight className={cn('size-5', PRODUCT_TONES[product.name].accent)} />}</button>)}</section></div>
}

export function MobileProductKit({ product, devices, back, enter }: { product: SelectableProduct; devices: DeviceCard[]; back: () => void; enter: () => void }) {
  return <div className="page detail-page flex min-h-full flex-col gap-4 pb-[calc(5rem+env(safe-area-inset-bottom))]"><PageHeader title="设备与套件" back={back} /><Card className={cn('p-5', PRODUCT_TONES[product].card)}><span className={cn('text-xs font-bold', PRODUCT_TONES[product].accent)}>当前产品</span><div className="mt-1 flex items-end justify-between gap-3"><div><h2 className="text-2xl font-extrabold">{product}</h2><p className="mt-1 text-sm text-muted-foreground">包含 {devices.length} 个设备</p></div><Badge variant="default"><Check className="size-3.5" />已选择</Badge></div></Card><section className="grid gap-2.5 md:grid-cols-2">{devices.map(device => <Card key={device.id} className={cn('grid min-h-24 grid-cols-[auto_1fr_auto] items-center gap-3 rounded-[1.15rem] p-3.5 shadow-none', device.disabled && 'opacity-50')} data-testid={`device-${device.id}`} role="listitem" aria-disabled={device.disabled ? 'true' : 'false'}><span className={cn('grid size-11 place-items-center rounded-[.9rem] [&>svg]:size-5', deviceTone(device.id))}>{device.icon}</span><span className="grid min-w-0 gap-0.5"><strong className="truncate">{device.name}</strong><small className="truncate text-xs text-muted-foreground">{device.id}</small><em className="truncate text-xs not-italic text-muted-foreground">{device.summary}</em></span><Badge variant={device.disabled ? 'secondary' : 'default'}>{device.disabled ? '未开发' : '可用'}</Badge></Card>)}</section><Button className="fixed bottom-[calc(4.75rem+env(safe-area-inset-bottom))] left-3 right-3 z-30 min-h-12" variant="default" onClick={enter}>进入数据页<ChevronRight className="size-4" /></Button></div>
}
