/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CollectionRecordCreate,
  CollectionRecordPublic,
  CollectionRecordUpdate,
  EgoCollectionRecordsReadCollectionRecordsParams,
  EgoCollectionRecordsReadMyCollectionRecordsParams,
  GenericPageCollectionRecordPublic,
  HTTPValidationError,
  Message
} from '../schemas';

import { customFetch } from '../../lib/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Read Collection Records
 */
export type egoCollectionRecordsReadCollectionRecordsResponse200 = {
  data: GenericPageCollectionRecordPublic
  status: 200
}

export type egoCollectionRecordsReadCollectionRecordsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionRecordsReadCollectionRecordsResponseSuccess = (egoCollectionRecordsReadCollectionRecordsResponse200) & {
  headers: Headers;
};
export type egoCollectionRecordsReadCollectionRecordsResponseError = (egoCollectionRecordsReadCollectionRecordsResponse422) & {
  headers: Headers;
};

export type egoCollectionRecordsReadCollectionRecordsResponse = (egoCollectionRecordsReadCollectionRecordsResponseSuccess | egoCollectionRecordsReadCollectionRecordsResponseError)

export const getEgoCollectionRecordsReadCollectionRecordsUrl = (params?: EgoCollectionRecordsReadCollectionRecordsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/ego/collection-records/?${stringifiedParams}` : `/api/v1/ego/collection-records/`
}

export const egoCollectionRecordsReadCollectionRecords = async (params?: EgoCollectionRecordsReadCollectionRecordsParams, options?: RequestInit): Promise<egoCollectionRecordsReadCollectionRecordsResponse> => {

  return customFetch<egoCollectionRecordsReadCollectionRecordsResponse>(getEgoCollectionRecordsReadCollectionRecordsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getEgoCollectionRecordsReadCollectionRecordsQueryKey = (params?: EgoCollectionRecordsReadCollectionRecordsParams,) => {
    return [
    `/api/v1/ego/collection-records/`, ...(params ? [params] : [])
    ] as const;
    }


export const getEgoCollectionRecordsReadCollectionRecordsQueryOptions = <TData = Awaited<ReturnType<typeof egoCollectionRecordsReadCollectionRecords>>, TError = HTTPValidationError>(params?: EgoCollectionRecordsReadCollectionRecordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionRecordsReadCollectionRecords>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEgoCollectionRecordsReadCollectionRecordsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof egoCollectionRecordsReadCollectionRecords>>> = ({ signal }) => egoCollectionRecordsReadCollectionRecords(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof egoCollectionRecordsReadCollectionRecords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EgoCollectionRecordsReadCollectionRecordsQueryResult = NonNullable<Awaited<ReturnType<typeof egoCollectionRecordsReadCollectionRecords>>>
export type EgoCollectionRecordsReadCollectionRecordsQueryError = HTTPValidationError


export function useEgoCollectionRecordsReadCollectionRecords<TData = Awaited<ReturnType<typeof egoCollectionRecordsReadCollectionRecords>>, TError = HTTPValidationError>(
 params: undefined |  EgoCollectionRecordsReadCollectionRecordsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionRecordsReadCollectionRecords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof egoCollectionRecordsReadCollectionRecords>>,
          TError,
          Awaited<ReturnType<typeof egoCollectionRecordsReadCollectionRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEgoCollectionRecordsReadCollectionRecords<TData = Awaited<ReturnType<typeof egoCollectionRecordsReadCollectionRecords>>, TError = HTTPValidationError>(
 params?: EgoCollectionRecordsReadCollectionRecordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionRecordsReadCollectionRecords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof egoCollectionRecordsReadCollectionRecords>>,
          TError,
          Awaited<ReturnType<typeof egoCollectionRecordsReadCollectionRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEgoCollectionRecordsReadCollectionRecords<TData = Awaited<ReturnType<typeof egoCollectionRecordsReadCollectionRecords>>, TError = HTTPValidationError>(
 params?: EgoCollectionRecordsReadCollectionRecordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionRecordsReadCollectionRecords>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Collection Records
 */

export function useEgoCollectionRecordsReadCollectionRecords<TData = Awaited<ReturnType<typeof egoCollectionRecordsReadCollectionRecords>>, TError = HTTPValidationError>(
 params?: EgoCollectionRecordsReadCollectionRecordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionRecordsReadCollectionRecords>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEgoCollectionRecordsReadCollectionRecordsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Collection Record
 */
export type egoCollectionRecordsCreateCollectionRecordResponse200 = {
  data: CollectionRecordPublic
  status: 200
}

export type egoCollectionRecordsCreateCollectionRecordResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionRecordsCreateCollectionRecordResponseSuccess = (egoCollectionRecordsCreateCollectionRecordResponse200) & {
  headers: Headers;
};
export type egoCollectionRecordsCreateCollectionRecordResponseError = (egoCollectionRecordsCreateCollectionRecordResponse422) & {
  headers: Headers;
};

export type egoCollectionRecordsCreateCollectionRecordResponse = (egoCollectionRecordsCreateCollectionRecordResponseSuccess | egoCollectionRecordsCreateCollectionRecordResponseError)

export const getEgoCollectionRecordsCreateCollectionRecordUrl = () => {




  return `/api/v1/ego/collection-records/`
}

export const egoCollectionRecordsCreateCollectionRecord = async (collectionRecordCreate: CollectionRecordCreate, options?: RequestInit): Promise<egoCollectionRecordsCreateCollectionRecordResponse> => {

  return customFetch<egoCollectionRecordsCreateCollectionRecordResponse>(getEgoCollectionRecordsCreateCollectionRecordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      collectionRecordCreate,)
  }
);}




export const getEgoCollectionRecordsCreateCollectionRecordMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionRecordsCreateCollectionRecord>>, TError,{data: CollectionRecordCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoCollectionRecordsCreateCollectionRecord>>, TError,{data: CollectionRecordCreate}, TContext> => {

const mutationKey = ['egoCollectionRecordsCreateCollectionRecord'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoCollectionRecordsCreateCollectionRecord>>, {data: CollectionRecordCreate}> = (props) => {
          const {data} = props ?? {};

          return  egoCollectionRecordsCreateCollectionRecord(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoCollectionRecordsCreateCollectionRecordMutationResult = NonNullable<Awaited<ReturnType<typeof egoCollectionRecordsCreateCollectionRecord>>>
    export type EgoCollectionRecordsCreateCollectionRecordMutationBody = CollectionRecordCreate
    export type EgoCollectionRecordsCreateCollectionRecordMutationError = HTTPValidationError

    /**
 * @summary Create Collection Record
 */
export const useEgoCollectionRecordsCreateCollectionRecord = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionRecordsCreateCollectionRecord>>, TError,{data: CollectionRecordCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoCollectionRecordsCreateCollectionRecord>>,
        TError,
        {data: CollectionRecordCreate},
        TContext
      > => {
      return useMutation(getEgoCollectionRecordsCreateCollectionRecordMutationOptions(options), queryClient);
    }
    /**
 * @summary Read My Collection Records
 */
export type egoCollectionRecordsReadMyCollectionRecordsResponse200 = {
  data: CollectionRecordPublic[]
  status: 200
}

export type egoCollectionRecordsReadMyCollectionRecordsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionRecordsReadMyCollectionRecordsResponseSuccess = (egoCollectionRecordsReadMyCollectionRecordsResponse200) & {
  headers: Headers;
};
export type egoCollectionRecordsReadMyCollectionRecordsResponseError = (egoCollectionRecordsReadMyCollectionRecordsResponse422) & {
  headers: Headers;
};

export type egoCollectionRecordsReadMyCollectionRecordsResponse = (egoCollectionRecordsReadMyCollectionRecordsResponseSuccess | egoCollectionRecordsReadMyCollectionRecordsResponseError)

export const getEgoCollectionRecordsReadMyCollectionRecordsUrl = (params?: EgoCollectionRecordsReadMyCollectionRecordsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/ego/collection-records/mine?${stringifiedParams}` : `/api/v1/ego/collection-records/mine`
}

export const egoCollectionRecordsReadMyCollectionRecords = async (params?: EgoCollectionRecordsReadMyCollectionRecordsParams, options?: RequestInit): Promise<egoCollectionRecordsReadMyCollectionRecordsResponse> => {

  return customFetch<egoCollectionRecordsReadMyCollectionRecordsResponse>(getEgoCollectionRecordsReadMyCollectionRecordsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getEgoCollectionRecordsReadMyCollectionRecordsQueryKey = (params?: EgoCollectionRecordsReadMyCollectionRecordsParams,) => {
    return [
    `/api/v1/ego/collection-records/mine`, ...(params ? [params] : [])
    ] as const;
    }


export const getEgoCollectionRecordsReadMyCollectionRecordsQueryOptions = <TData = Awaited<ReturnType<typeof egoCollectionRecordsReadMyCollectionRecords>>, TError = HTTPValidationError>(params?: EgoCollectionRecordsReadMyCollectionRecordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionRecordsReadMyCollectionRecords>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEgoCollectionRecordsReadMyCollectionRecordsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof egoCollectionRecordsReadMyCollectionRecords>>> = ({ signal }) => egoCollectionRecordsReadMyCollectionRecords(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof egoCollectionRecordsReadMyCollectionRecords>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EgoCollectionRecordsReadMyCollectionRecordsQueryResult = NonNullable<Awaited<ReturnType<typeof egoCollectionRecordsReadMyCollectionRecords>>>
export type EgoCollectionRecordsReadMyCollectionRecordsQueryError = HTTPValidationError


export function useEgoCollectionRecordsReadMyCollectionRecords<TData = Awaited<ReturnType<typeof egoCollectionRecordsReadMyCollectionRecords>>, TError = HTTPValidationError>(
 params: undefined |  EgoCollectionRecordsReadMyCollectionRecordsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionRecordsReadMyCollectionRecords>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof egoCollectionRecordsReadMyCollectionRecords>>,
          TError,
          Awaited<ReturnType<typeof egoCollectionRecordsReadMyCollectionRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEgoCollectionRecordsReadMyCollectionRecords<TData = Awaited<ReturnType<typeof egoCollectionRecordsReadMyCollectionRecords>>, TError = HTTPValidationError>(
 params?: EgoCollectionRecordsReadMyCollectionRecordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionRecordsReadMyCollectionRecords>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof egoCollectionRecordsReadMyCollectionRecords>>,
          TError,
          Awaited<ReturnType<typeof egoCollectionRecordsReadMyCollectionRecords>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEgoCollectionRecordsReadMyCollectionRecords<TData = Awaited<ReturnType<typeof egoCollectionRecordsReadMyCollectionRecords>>, TError = HTTPValidationError>(
 params?: EgoCollectionRecordsReadMyCollectionRecordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionRecordsReadMyCollectionRecords>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read My Collection Records
 */

export function useEgoCollectionRecordsReadMyCollectionRecords<TData = Awaited<ReturnType<typeof egoCollectionRecordsReadMyCollectionRecords>>, TError = HTTPValidationError>(
 params?: EgoCollectionRecordsReadMyCollectionRecordsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionRecordsReadMyCollectionRecords>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEgoCollectionRecordsReadMyCollectionRecordsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Update Collection Record
 */
export type egoCollectionRecordsUpdateCollectionRecordResponse200 = {
  data: CollectionRecordPublic
  status: 200
}

export type egoCollectionRecordsUpdateCollectionRecordResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionRecordsUpdateCollectionRecordResponseSuccess = (egoCollectionRecordsUpdateCollectionRecordResponse200) & {
  headers: Headers;
};
export type egoCollectionRecordsUpdateCollectionRecordResponseError = (egoCollectionRecordsUpdateCollectionRecordResponse422) & {
  headers: Headers;
};

export type egoCollectionRecordsUpdateCollectionRecordResponse = (egoCollectionRecordsUpdateCollectionRecordResponseSuccess | egoCollectionRecordsUpdateCollectionRecordResponseError)

export const getEgoCollectionRecordsUpdateCollectionRecordUrl = (resourceId: string,) => {




  return `/api/v1/ego/collection-records/${resourceId}`
}

export const egoCollectionRecordsUpdateCollectionRecord = async (resourceId: string,
    collectionRecordUpdate: CollectionRecordUpdate, options?: RequestInit): Promise<egoCollectionRecordsUpdateCollectionRecordResponse> => {

  return customFetch<egoCollectionRecordsUpdateCollectionRecordResponse>(getEgoCollectionRecordsUpdateCollectionRecordUrl(resourceId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      collectionRecordUpdate,)
  }
);}




export const getEgoCollectionRecordsUpdateCollectionRecordMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionRecordsUpdateCollectionRecord>>, TError,{resourceId: string;data: CollectionRecordUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoCollectionRecordsUpdateCollectionRecord>>, TError,{resourceId: string;data: CollectionRecordUpdate}, TContext> => {

const mutationKey = ['egoCollectionRecordsUpdateCollectionRecord'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoCollectionRecordsUpdateCollectionRecord>>, {resourceId: string;data: CollectionRecordUpdate}> = (props) => {
          const {resourceId,data} = props ?? {};

          return  egoCollectionRecordsUpdateCollectionRecord(resourceId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoCollectionRecordsUpdateCollectionRecordMutationResult = NonNullable<Awaited<ReturnType<typeof egoCollectionRecordsUpdateCollectionRecord>>>
    export type EgoCollectionRecordsUpdateCollectionRecordMutationBody = CollectionRecordUpdate
    export type EgoCollectionRecordsUpdateCollectionRecordMutationError = HTTPValidationError

    /**
 * @summary Update Collection Record
 */
export const useEgoCollectionRecordsUpdateCollectionRecord = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionRecordsUpdateCollectionRecord>>, TError,{resourceId: string;data: CollectionRecordUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoCollectionRecordsUpdateCollectionRecord>>,
        TError,
        {resourceId: string;data: CollectionRecordUpdate},
        TContext
      > => {
      return useMutation(getEgoCollectionRecordsUpdateCollectionRecordMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Collection Record
 */
export type egoCollectionRecordsDeleteCollectionRecordResponse200 = {
  data: Message
  status: 200
}

export type egoCollectionRecordsDeleteCollectionRecordResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionRecordsDeleteCollectionRecordResponseSuccess = (egoCollectionRecordsDeleteCollectionRecordResponse200) & {
  headers: Headers;
};
export type egoCollectionRecordsDeleteCollectionRecordResponseError = (egoCollectionRecordsDeleteCollectionRecordResponse422) & {
  headers: Headers;
};

export type egoCollectionRecordsDeleteCollectionRecordResponse = (egoCollectionRecordsDeleteCollectionRecordResponseSuccess | egoCollectionRecordsDeleteCollectionRecordResponseError)

export const getEgoCollectionRecordsDeleteCollectionRecordUrl = (resourceId: string,) => {




  return `/api/v1/ego/collection-records/${resourceId}`
}

export const egoCollectionRecordsDeleteCollectionRecord = async (resourceId: string, options?: RequestInit): Promise<egoCollectionRecordsDeleteCollectionRecordResponse> => {

  return customFetch<egoCollectionRecordsDeleteCollectionRecordResponse>(getEgoCollectionRecordsDeleteCollectionRecordUrl(resourceId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getEgoCollectionRecordsDeleteCollectionRecordMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionRecordsDeleteCollectionRecord>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoCollectionRecordsDeleteCollectionRecord>>, TError,{resourceId: string}, TContext> => {

const mutationKey = ['egoCollectionRecordsDeleteCollectionRecord'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoCollectionRecordsDeleteCollectionRecord>>, {resourceId: string}> = (props) => {
          const {resourceId} = props ?? {};

          return  egoCollectionRecordsDeleteCollectionRecord(resourceId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoCollectionRecordsDeleteCollectionRecordMutationResult = NonNullable<Awaited<ReturnType<typeof egoCollectionRecordsDeleteCollectionRecord>>>

    export type EgoCollectionRecordsDeleteCollectionRecordMutationError = HTTPValidationError

    /**
 * @summary Delete Collection Record
 */
export const useEgoCollectionRecordsDeleteCollectionRecord = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionRecordsDeleteCollectionRecord>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoCollectionRecordsDeleteCollectionRecord>>,
        TError,
        {resourceId: string},
        TContext
      > => {
      return useMutation(getEgoCollectionRecordsDeleteCollectionRecordMutationOptions(options), queryClient);
    }
