/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CollectionSceneCreate,
  CollectionScenePublic,
  CollectionSceneUpdate,
  EgoCollectionScenesReadCollectionScenesParams,
  GenericPageCollectionScenePublic,
  HTTPValidationError,
  Message
} from '../schemas';

import { customFetch } from '../../lib/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Read Collection Scenes
 */
export type egoCollectionScenesReadCollectionScenesResponse200 = {
  data: GenericPageCollectionScenePublic
  status: 200
}

export type egoCollectionScenesReadCollectionScenesResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionScenesReadCollectionScenesResponseSuccess = (egoCollectionScenesReadCollectionScenesResponse200) & {
  headers: Headers;
};
export type egoCollectionScenesReadCollectionScenesResponseError = (egoCollectionScenesReadCollectionScenesResponse422) & {
  headers: Headers;
};

export type egoCollectionScenesReadCollectionScenesResponse = (egoCollectionScenesReadCollectionScenesResponseSuccess | egoCollectionScenesReadCollectionScenesResponseError)

export const getEgoCollectionScenesReadCollectionScenesUrl = (params?: EgoCollectionScenesReadCollectionScenesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/ego/collection-scenes/?${stringifiedParams}` : `/api/v1/ego/collection-scenes/`
}

export const egoCollectionScenesReadCollectionScenes = async (params?: EgoCollectionScenesReadCollectionScenesParams, options?: RequestInit): Promise<egoCollectionScenesReadCollectionScenesResponse> => {

  return customFetch<egoCollectionScenesReadCollectionScenesResponse>(getEgoCollectionScenesReadCollectionScenesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getEgoCollectionScenesReadCollectionScenesQueryKey = (params?: EgoCollectionScenesReadCollectionScenesParams,) => {
    return [
    `/api/v1/ego/collection-scenes/`, ...(params ? [params] : [])
    ] as const;
    }


export const getEgoCollectionScenesReadCollectionScenesQueryOptions = <TData = Awaited<ReturnType<typeof egoCollectionScenesReadCollectionScenes>>, TError = HTTPValidationError>(params?: EgoCollectionScenesReadCollectionScenesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionScenesReadCollectionScenes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEgoCollectionScenesReadCollectionScenesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof egoCollectionScenesReadCollectionScenes>>> = ({ signal }) => egoCollectionScenesReadCollectionScenes(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof egoCollectionScenesReadCollectionScenes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EgoCollectionScenesReadCollectionScenesQueryResult = NonNullable<Awaited<ReturnType<typeof egoCollectionScenesReadCollectionScenes>>>
export type EgoCollectionScenesReadCollectionScenesQueryError = HTTPValidationError


export function useEgoCollectionScenesReadCollectionScenes<TData = Awaited<ReturnType<typeof egoCollectionScenesReadCollectionScenes>>, TError = HTTPValidationError>(
 params: undefined |  EgoCollectionScenesReadCollectionScenesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionScenesReadCollectionScenes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof egoCollectionScenesReadCollectionScenes>>,
          TError,
          Awaited<ReturnType<typeof egoCollectionScenesReadCollectionScenes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEgoCollectionScenesReadCollectionScenes<TData = Awaited<ReturnType<typeof egoCollectionScenesReadCollectionScenes>>, TError = HTTPValidationError>(
 params?: EgoCollectionScenesReadCollectionScenesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionScenesReadCollectionScenes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof egoCollectionScenesReadCollectionScenes>>,
          TError,
          Awaited<ReturnType<typeof egoCollectionScenesReadCollectionScenes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEgoCollectionScenesReadCollectionScenes<TData = Awaited<ReturnType<typeof egoCollectionScenesReadCollectionScenes>>, TError = HTTPValidationError>(
 params?: EgoCollectionScenesReadCollectionScenesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionScenesReadCollectionScenes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Collection Scenes
 */

export function useEgoCollectionScenesReadCollectionScenes<TData = Awaited<ReturnType<typeof egoCollectionScenesReadCollectionScenes>>, TError = HTTPValidationError>(
 params?: EgoCollectionScenesReadCollectionScenesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionScenesReadCollectionScenes>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEgoCollectionScenesReadCollectionScenesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Collection Scene
 */
export type egoCollectionScenesCreateCollectionSceneResponse200 = {
  data: CollectionScenePublic
  status: 200
}

export type egoCollectionScenesCreateCollectionSceneResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionScenesCreateCollectionSceneResponseSuccess = (egoCollectionScenesCreateCollectionSceneResponse200) & {
  headers: Headers;
};
export type egoCollectionScenesCreateCollectionSceneResponseError = (egoCollectionScenesCreateCollectionSceneResponse422) & {
  headers: Headers;
};

export type egoCollectionScenesCreateCollectionSceneResponse = (egoCollectionScenesCreateCollectionSceneResponseSuccess | egoCollectionScenesCreateCollectionSceneResponseError)

export const getEgoCollectionScenesCreateCollectionSceneUrl = () => {




  return `/api/v1/ego/collection-scenes/`
}

export const egoCollectionScenesCreateCollectionScene = async (collectionSceneCreate: CollectionSceneCreate, options?: RequestInit): Promise<egoCollectionScenesCreateCollectionSceneResponse> => {

  return customFetch<egoCollectionScenesCreateCollectionSceneResponse>(getEgoCollectionScenesCreateCollectionSceneUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      collectionSceneCreate,)
  }
);}




export const getEgoCollectionScenesCreateCollectionSceneMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionScenesCreateCollectionScene>>, TError,{data: CollectionSceneCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoCollectionScenesCreateCollectionScene>>, TError,{data: CollectionSceneCreate}, TContext> => {

const mutationKey = ['egoCollectionScenesCreateCollectionScene'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoCollectionScenesCreateCollectionScene>>, {data: CollectionSceneCreate}> = (props) => {
          const {data} = props ?? {};

          return  egoCollectionScenesCreateCollectionScene(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoCollectionScenesCreateCollectionSceneMutationResult = NonNullable<Awaited<ReturnType<typeof egoCollectionScenesCreateCollectionScene>>>
    export type EgoCollectionScenesCreateCollectionSceneMutationBody = CollectionSceneCreate
    export type EgoCollectionScenesCreateCollectionSceneMutationError = HTTPValidationError

    /**
 * @summary Create Collection Scene
 */
export const useEgoCollectionScenesCreateCollectionScene = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionScenesCreateCollectionScene>>, TError,{data: CollectionSceneCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoCollectionScenesCreateCollectionScene>>,
        TError,
        {data: CollectionSceneCreate},
        TContext
      > => {
      return useMutation(getEgoCollectionScenesCreateCollectionSceneMutationOptions(options), queryClient);
    }
    /**
 * @summary Update Collection Scene
 */
export type egoCollectionScenesUpdateCollectionSceneResponse200 = {
  data: CollectionScenePublic
  status: 200
}

export type egoCollectionScenesUpdateCollectionSceneResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionScenesUpdateCollectionSceneResponseSuccess = (egoCollectionScenesUpdateCollectionSceneResponse200) & {
  headers: Headers;
};
export type egoCollectionScenesUpdateCollectionSceneResponseError = (egoCollectionScenesUpdateCollectionSceneResponse422) & {
  headers: Headers;
};

export type egoCollectionScenesUpdateCollectionSceneResponse = (egoCollectionScenesUpdateCollectionSceneResponseSuccess | egoCollectionScenesUpdateCollectionSceneResponseError)

export const getEgoCollectionScenesUpdateCollectionSceneUrl = (resourceId: string,) => {




  return `/api/v1/ego/collection-scenes/${resourceId}`
}

export const egoCollectionScenesUpdateCollectionScene = async (resourceId: string,
    collectionSceneUpdate: CollectionSceneUpdate, options?: RequestInit): Promise<egoCollectionScenesUpdateCollectionSceneResponse> => {

  return customFetch<egoCollectionScenesUpdateCollectionSceneResponse>(getEgoCollectionScenesUpdateCollectionSceneUrl(resourceId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      collectionSceneUpdate,)
  }
);}




export const getEgoCollectionScenesUpdateCollectionSceneMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionScenesUpdateCollectionScene>>, TError,{resourceId: string;data: CollectionSceneUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoCollectionScenesUpdateCollectionScene>>, TError,{resourceId: string;data: CollectionSceneUpdate}, TContext> => {

const mutationKey = ['egoCollectionScenesUpdateCollectionScene'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoCollectionScenesUpdateCollectionScene>>, {resourceId: string;data: CollectionSceneUpdate}> = (props) => {
          const {resourceId,data} = props ?? {};

          return  egoCollectionScenesUpdateCollectionScene(resourceId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoCollectionScenesUpdateCollectionSceneMutationResult = NonNullable<Awaited<ReturnType<typeof egoCollectionScenesUpdateCollectionScene>>>
    export type EgoCollectionScenesUpdateCollectionSceneMutationBody = CollectionSceneUpdate
    export type EgoCollectionScenesUpdateCollectionSceneMutationError = HTTPValidationError

    /**
 * @summary Update Collection Scene
 */
export const useEgoCollectionScenesUpdateCollectionScene = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionScenesUpdateCollectionScene>>, TError,{resourceId: string;data: CollectionSceneUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoCollectionScenesUpdateCollectionScene>>,
        TError,
        {resourceId: string;data: CollectionSceneUpdate},
        TContext
      > => {
      return useMutation(getEgoCollectionScenesUpdateCollectionSceneMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Collection Scene
 */
export type egoCollectionScenesDeleteCollectionSceneResponse200 = {
  data: Message
  status: 200
}

export type egoCollectionScenesDeleteCollectionSceneResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionScenesDeleteCollectionSceneResponseSuccess = (egoCollectionScenesDeleteCollectionSceneResponse200) & {
  headers: Headers;
};
export type egoCollectionScenesDeleteCollectionSceneResponseError = (egoCollectionScenesDeleteCollectionSceneResponse422) & {
  headers: Headers;
};

export type egoCollectionScenesDeleteCollectionSceneResponse = (egoCollectionScenesDeleteCollectionSceneResponseSuccess | egoCollectionScenesDeleteCollectionSceneResponseError)

export const getEgoCollectionScenesDeleteCollectionSceneUrl = (resourceId: string,) => {




  return `/api/v1/ego/collection-scenes/${resourceId}`
}

export const egoCollectionScenesDeleteCollectionScene = async (resourceId: string, options?: RequestInit): Promise<egoCollectionScenesDeleteCollectionSceneResponse> => {

  return customFetch<egoCollectionScenesDeleteCollectionSceneResponse>(getEgoCollectionScenesDeleteCollectionSceneUrl(resourceId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getEgoCollectionScenesDeleteCollectionSceneMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionScenesDeleteCollectionScene>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoCollectionScenesDeleteCollectionScene>>, TError,{resourceId: string}, TContext> => {

const mutationKey = ['egoCollectionScenesDeleteCollectionScene'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoCollectionScenesDeleteCollectionScene>>, {resourceId: string}> = (props) => {
          const {resourceId} = props ?? {};

          return  egoCollectionScenesDeleteCollectionScene(resourceId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoCollectionScenesDeleteCollectionSceneMutationResult = NonNullable<Awaited<ReturnType<typeof egoCollectionScenesDeleteCollectionScene>>>

    export type EgoCollectionScenesDeleteCollectionSceneMutationError = HTTPValidationError

    /**
 * @summary Delete Collection Scene
 */
export const useEgoCollectionScenesDeleteCollectionScene = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionScenesDeleteCollectionScene>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoCollectionScenesDeleteCollectionScene>>,
        TError,
        {resourceId: string},
        TContext
      > => {
      return useMutation(getEgoCollectionScenesDeleteCollectionSceneMutationOptions(options), queryClient);
    }
