/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AsyncTaskPublic,
  GenericPageAsyncTaskPublic,
  HTTPValidationError,
  InfraAsyncTasksReadMyAsyncTasksParams
} from '../schemas';

import { customFetch } from '../../lib/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get user's async tasks
 */
export type infraAsyncTasksReadMyAsyncTasksResponse200 = {
  data: GenericPageAsyncTaskPublic
  status: 200
}

export type infraAsyncTasksReadMyAsyncTasksResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type infraAsyncTasksReadMyAsyncTasksResponseSuccess = (infraAsyncTasksReadMyAsyncTasksResponse200) & {
  headers: Headers;
};
export type infraAsyncTasksReadMyAsyncTasksResponseError = (infraAsyncTasksReadMyAsyncTasksResponse422) & {
  headers: Headers;
};

export type infraAsyncTasksReadMyAsyncTasksResponse = (infraAsyncTasksReadMyAsyncTasksResponseSuccess | infraAsyncTasksReadMyAsyncTasksResponseError)

export const getInfraAsyncTasksReadMyAsyncTasksUrl = (params?: InfraAsyncTasksReadMyAsyncTasksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/async-tasks/my_tasks?${stringifiedParams}` : `/api/v1/async-tasks/my_tasks`
}

export const infraAsyncTasksReadMyAsyncTasks = async (params?: InfraAsyncTasksReadMyAsyncTasksParams, options?: RequestInit): Promise<infraAsyncTasksReadMyAsyncTasksResponse> => {

  return customFetch<infraAsyncTasksReadMyAsyncTasksResponse>(getInfraAsyncTasksReadMyAsyncTasksUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getInfraAsyncTasksReadMyAsyncTasksQueryKey = (params?: InfraAsyncTasksReadMyAsyncTasksParams,) => {
    return [
    `/api/v1/async-tasks/my_tasks`, ...(params ? [params] : [])
    ] as const;
    }


export const getInfraAsyncTasksReadMyAsyncTasksQueryOptions = <TData = Awaited<ReturnType<typeof infraAsyncTasksReadMyAsyncTasks>>, TError = HTTPValidationError>(params?: InfraAsyncTasksReadMyAsyncTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAsyncTasksReadMyAsyncTasks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInfraAsyncTasksReadMyAsyncTasksQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof infraAsyncTasksReadMyAsyncTasks>>> = ({ signal }) => infraAsyncTasksReadMyAsyncTasks(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof infraAsyncTasksReadMyAsyncTasks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InfraAsyncTasksReadMyAsyncTasksQueryResult = NonNullable<Awaited<ReturnType<typeof infraAsyncTasksReadMyAsyncTasks>>>
export type InfraAsyncTasksReadMyAsyncTasksQueryError = HTTPValidationError


export function useInfraAsyncTasksReadMyAsyncTasks<TData = Awaited<ReturnType<typeof infraAsyncTasksReadMyAsyncTasks>>, TError = HTTPValidationError>(
 params: undefined |  InfraAsyncTasksReadMyAsyncTasksParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAsyncTasksReadMyAsyncTasks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof infraAsyncTasksReadMyAsyncTasks>>,
          TError,
          Awaited<ReturnType<typeof infraAsyncTasksReadMyAsyncTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInfraAsyncTasksReadMyAsyncTasks<TData = Awaited<ReturnType<typeof infraAsyncTasksReadMyAsyncTasks>>, TError = HTTPValidationError>(
 params?: InfraAsyncTasksReadMyAsyncTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAsyncTasksReadMyAsyncTasks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof infraAsyncTasksReadMyAsyncTasks>>,
          TError,
          Awaited<ReturnType<typeof infraAsyncTasksReadMyAsyncTasks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInfraAsyncTasksReadMyAsyncTasks<TData = Awaited<ReturnType<typeof infraAsyncTasksReadMyAsyncTasks>>, TError = HTTPValidationError>(
 params?: InfraAsyncTasksReadMyAsyncTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAsyncTasksReadMyAsyncTasks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user's async tasks
 */

export function useInfraAsyncTasksReadMyAsyncTasks<TData = Awaited<ReturnType<typeof infraAsyncTasksReadMyAsyncTasks>>, TError = HTTPValidationError>(
 params?: InfraAsyncTasksReadMyAsyncTasksParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAsyncTasksReadMyAsyncTasks>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInfraAsyncTasksReadMyAsyncTasksQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Get a specific async task
 */
export type infraAsyncTasksReadAsyncTaskResponse200 = {
  data: AsyncTaskPublic
  status: 200
}

export type infraAsyncTasksReadAsyncTaskResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type infraAsyncTasksReadAsyncTaskResponseSuccess = (infraAsyncTasksReadAsyncTaskResponse200) & {
  headers: Headers;
};
export type infraAsyncTasksReadAsyncTaskResponseError = (infraAsyncTasksReadAsyncTaskResponse422) & {
  headers: Headers;
};

export type infraAsyncTasksReadAsyncTaskResponse = (infraAsyncTasksReadAsyncTaskResponseSuccess | infraAsyncTasksReadAsyncTaskResponseError)

export const getInfraAsyncTasksReadAsyncTaskUrl = (id: string,) => {




  return `/api/v1/async-tasks/${id}`
}

export const infraAsyncTasksReadAsyncTask = async (id: string, options?: RequestInit): Promise<infraAsyncTasksReadAsyncTaskResponse> => {

  return customFetch<infraAsyncTasksReadAsyncTaskResponse>(getInfraAsyncTasksReadAsyncTaskUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getInfraAsyncTasksReadAsyncTaskQueryKey = (id: string,) => {
    return [
    `/api/v1/async-tasks/${id}`
    ] as const;
    }


export const getInfraAsyncTasksReadAsyncTaskQueryOptions = <TData = Awaited<ReturnType<typeof infraAsyncTasksReadAsyncTask>>, TError = HTTPValidationError>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAsyncTasksReadAsyncTask>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInfraAsyncTasksReadAsyncTaskQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof infraAsyncTasksReadAsyncTask>>> = ({ signal }) => infraAsyncTasksReadAsyncTask(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof infraAsyncTasksReadAsyncTask>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InfraAsyncTasksReadAsyncTaskQueryResult = NonNullable<Awaited<ReturnType<typeof infraAsyncTasksReadAsyncTask>>>
export type InfraAsyncTasksReadAsyncTaskQueryError = HTTPValidationError


export function useInfraAsyncTasksReadAsyncTask<TData = Awaited<ReturnType<typeof infraAsyncTasksReadAsyncTask>>, TError = HTTPValidationError>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAsyncTasksReadAsyncTask>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof infraAsyncTasksReadAsyncTask>>,
          TError,
          Awaited<ReturnType<typeof infraAsyncTasksReadAsyncTask>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInfraAsyncTasksReadAsyncTask<TData = Awaited<ReturnType<typeof infraAsyncTasksReadAsyncTask>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAsyncTasksReadAsyncTask>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof infraAsyncTasksReadAsyncTask>>,
          TError,
          Awaited<ReturnType<typeof infraAsyncTasksReadAsyncTask>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInfraAsyncTasksReadAsyncTask<TData = Awaited<ReturnType<typeof infraAsyncTasksReadAsyncTask>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAsyncTasksReadAsyncTask>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get a specific async task
 */

export function useInfraAsyncTasksReadAsyncTask<TData = Awaited<ReturnType<typeof infraAsyncTasksReadAsyncTask>>, TError = HTTPValidationError>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAsyncTasksReadAsyncTask>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInfraAsyncTasksReadAsyncTaskQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Cancel a specific async task
 */
export type infraAsyncTasksCancelAsyncTaskResponse200 = {
  data: AsyncTaskPublic
  status: 200
}

export type infraAsyncTasksCancelAsyncTaskResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type infraAsyncTasksCancelAsyncTaskResponseSuccess = (infraAsyncTasksCancelAsyncTaskResponse200) & {
  headers: Headers;
};
export type infraAsyncTasksCancelAsyncTaskResponseError = (infraAsyncTasksCancelAsyncTaskResponse422) & {
  headers: Headers;
};

export type infraAsyncTasksCancelAsyncTaskResponse = (infraAsyncTasksCancelAsyncTaskResponseSuccess | infraAsyncTasksCancelAsyncTaskResponseError)

export const getInfraAsyncTasksCancelAsyncTaskUrl = (id: string,) => {




  return `/api/v1/async-tasks/${id}/cancel`
}

export const infraAsyncTasksCancelAsyncTask = async (id: string, options?: RequestInit): Promise<infraAsyncTasksCancelAsyncTaskResponse> => {

  return customFetch<infraAsyncTasksCancelAsyncTaskResponse>(getInfraAsyncTasksCancelAsyncTaskUrl(id),
  {
    ...options,
    method: 'POST'


  }
);}




export const getInfraAsyncTasksCancelAsyncTaskMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof infraAsyncTasksCancelAsyncTask>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof infraAsyncTasksCancelAsyncTask>>, TError,{id: string}, TContext> => {

const mutationKey = ['infraAsyncTasksCancelAsyncTask'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof infraAsyncTasksCancelAsyncTask>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  infraAsyncTasksCancelAsyncTask(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type InfraAsyncTasksCancelAsyncTaskMutationResult = NonNullable<Awaited<ReturnType<typeof infraAsyncTasksCancelAsyncTask>>>

    export type InfraAsyncTasksCancelAsyncTaskMutationError = HTTPValidationError

    /**
 * @summary Cancel a specific async task
 */
export const useInfraAsyncTasksCancelAsyncTask = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof infraAsyncTasksCancelAsyncTask>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof infraAsyncTasksCancelAsyncTask>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getInfraAsyncTasksCancelAsyncTaskMutationOptions(options), queryClient);
    }
