/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Retrieve roles.
 * @summary Read Roles
 */
export const workspaceRolesReadRolesQuerySkipDefault = 0;
export const workspaceRolesReadRolesQuerySkipMin = 0;

export const workspaceRolesReadRolesQueryLimitDefault = 20;
export const workspaceRolesReadRolesQueryLimitMax = 500;



export const WorkspaceRolesReadRolesQueryParams = zod.object({
  "skip": zod.number().min(workspaceRolesReadRolesQuerySkipMin).default(workspaceRolesReadRolesQuerySkipDefault),
  "limit": zod.number().max(workspaceRolesReadRolesQueryLimitMax).default(workspaceRolesReadRolesQueryLimitDefault),
  "role_name": zod.union([zod.string(),zod.null()]).optional(),
  "business_line_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "is_active": zod.union([zod.boolean(),zod.null()]).optional()
})

export const WorkspaceRolesReadRolesHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const workspaceRolesReadRolesResponseDataItemRoleNameMax = 64;

export const workspaceRolesReadRolesResponseDataItemSortDefault = 1;
export const workspaceRolesReadRolesResponseDataItemIsActiveDefault = true;

export const WorkspaceRolesReadRolesResponse = zod.object({
  "count": zod.number(),
  "data": zod.array(zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "role_name": zod.string().min(1).max(workspaceRolesReadRolesResponseDataItemRoleNameMax),
  "business_line_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "sort": zod.number().default(workspaceRolesReadRolesResponseDataItemSortDefault),
  "is_active": zod.boolean().default(workspaceRolesReadRolesResponseDataItemIsActiveDefault),
  "remark": zod.union([zod.string(),zod.null()]).optional(),
  "workspace_id": zod.uuid(),
  "business_line_name": zod.union([zod.string(),zod.null()]).optional(),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
}))
})

/**
 * Create new role.
 * @summary Create Role
 */
export const WorkspaceRolesCreateRoleHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const workspaceRolesCreateRoleBodyRoleNameMax = 64;

export const workspaceRolesCreateRoleBodySortDefault = 1;
export const workspaceRolesCreateRoleBodyIsActiveDefault = true;

export const WorkspaceRolesCreateRoleBody = zod.object({
  "role_name": zod.string().min(1).max(workspaceRolesCreateRoleBodyRoleNameMax),
  "business_line_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "sort": zod.number().default(workspaceRolesCreateRoleBodySortDefault),
  "is_active": zod.boolean().default(workspaceRolesCreateRoleBodyIsActiveDefault),
  "remark": zod.union([zod.string(),zod.null()]).optional()
})

export const workspaceRolesCreateRoleResponseRoleNameMax = 64;

export const workspaceRolesCreateRoleResponseSortDefault = 1;
export const workspaceRolesCreateRoleResponseIsActiveDefault = true;

export const WorkspaceRolesCreateRoleResponse = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "role_name": zod.string().min(1).max(workspaceRolesCreateRoleResponseRoleNameMax),
  "business_line_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "sort": zod.number().default(workspaceRolesCreateRoleResponseSortDefault),
  "is_active": zod.boolean().default(workspaceRolesCreateRoleResponseIsActiveDefault),
  "remark": zod.union([zod.string(),zod.null()]).optional(),
  "workspace_id": zod.uuid(),
  "business_line_name": zod.union([zod.string(),zod.null()]).optional(),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * Retrieve role options for dropdowns. Only active roles, unpaginated.
 * @summary Read Role Options
 */
export const WorkspaceRolesReadRoleOptionsHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const workspaceRolesReadRoleOptionsResponseRoleNameMax = 64;

export const workspaceRolesReadRoleOptionsResponseSortDefault = 1;
export const workspaceRolesReadRoleOptionsResponseIsActiveDefault = true;

export const WorkspaceRolesReadRoleOptionsResponseItem = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "role_name": zod.string().min(1).max(workspaceRolesReadRoleOptionsResponseRoleNameMax),
  "business_line_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "sort": zod.number().default(workspaceRolesReadRoleOptionsResponseSortDefault),
  "is_active": zod.boolean().default(workspaceRolesReadRoleOptionsResponseIsActiveDefault),
  "remark": zod.union([zod.string(),zod.null()]).optional(),
  "workspace_id": zod.uuid(),
  "business_line_name": zod.union([zod.string(),zod.null()]).optional(),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})
export const WorkspaceRolesReadRoleOptionsResponse = zod.array(WorkspaceRolesReadRoleOptionsResponseItem)

/**
 * Update a role.
 * @summary Update Role
 */
export const WorkspaceRolesUpdateRoleParams = zod.object({
  "role_id": zod.uuid()
})

export const WorkspaceRolesUpdateRoleHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const workspaceRolesUpdateRoleBodyRoleNameMax = 64;

export const workspaceRolesUpdateRoleBodySortDefault = 1;
export const workspaceRolesUpdateRoleBodyIsActiveDefault = true;

export const WorkspaceRolesUpdateRoleBody = zod.object({
  "role_name": zod.string().min(1).max(workspaceRolesUpdateRoleBodyRoleNameMax),
  "business_line_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "sort": zod.number().default(workspaceRolesUpdateRoleBodySortDefault),
  "is_active": zod.boolean().default(workspaceRolesUpdateRoleBodyIsActiveDefault),
  "remark": zod.union([zod.string(),zod.null()]).optional()
})

export const workspaceRolesUpdateRoleResponseRoleNameMax = 64;

export const workspaceRolesUpdateRoleResponseSortDefault = 1;
export const workspaceRolesUpdateRoleResponseIsActiveDefault = true;

export const WorkspaceRolesUpdateRoleResponse = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "role_name": zod.string().min(1).max(workspaceRolesUpdateRoleResponseRoleNameMax),
  "business_line_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "sort": zod.number().default(workspaceRolesUpdateRoleResponseSortDefault),
  "is_active": zod.boolean().default(workspaceRolesUpdateRoleResponseIsActiveDefault),
  "remark": zod.union([zod.string(),zod.null()]).optional(),
  "workspace_id": zod.uuid(),
  "business_line_name": zod.union([zod.string(),zod.null()]).optional(),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * Delete a role.
 * @summary Delete Role
 */
export const WorkspaceRolesDeleteRoleParams = zod.object({
  "role_id": zod.uuid()
})

export const WorkspaceRolesDeleteRoleHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const WorkspaceRolesDeleteRoleResponse = zod.object({
  "message": zod.string()
})

/**
 * Assign menus to a role.
 * @summary Set Role Menus
 */
export const WorkspaceRolesSetRoleMenusParams = zod.object({
  "role_id": zod.uuid()
})

export const WorkspaceRolesSetRoleMenusHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const WorkspaceRolesSetRoleMenusBody = zod.object({
  "menu_ids": zod.array(zod.uuid())
})

export const workspaceRolesSetRoleMenusResponseRoleNameMax = 64;

export const workspaceRolesSetRoleMenusResponseSortDefault = 1;
export const workspaceRolesSetRoleMenusResponseIsActiveDefault = true;

export const WorkspaceRolesSetRoleMenusResponse = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "role_name": zod.string().min(1).max(workspaceRolesSetRoleMenusResponseRoleNameMax),
  "business_line_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "sort": zod.number().default(workspaceRolesSetRoleMenusResponseSortDefault),
  "is_active": zod.boolean().default(workspaceRolesSetRoleMenusResponseIsActiveDefault),
  "remark": zod.union([zod.string(),zod.null()]).optional(),
  "workspace_id": zod.uuid(),
  "business_line_name": zod.union([zod.string(),zod.null()]).optional(),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})

/**
 * Get menus assigned to a role.
 * @summary Read Role Menus
 */
export const WorkspaceRolesReadRoleMenusParams = zod.object({
  "role_id": zod.uuid()
})

export const WorkspaceRolesReadRoleMenusHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const WorkspaceRolesReadRoleMenusResponseItem = zod.uuid()
export const WorkspaceRolesReadRoleMenusResponse = zod.array(WorkspaceRolesReadRoleMenusResponseItem)

/**
 * Get workspace members currently assigned to a role.
 * @summary Read Role Members
 */
export const WorkspaceRolesReadRoleMembersParams = zod.object({
  "role_id": zod.uuid()
})

export const WorkspaceRolesReadRoleMembersHeader = zod.object({
  "X-Workspace-Id": zod.string()
})

export const workspaceRolesReadRoleMembersResponseUserIdOneMax = 255;

export const workspaceRolesReadRoleMembersResponseJobNumberOneMax = 255;

export const workspaceRolesReadRoleMembersResponseEmployeeNameOneMax = 255;

export const workspaceRolesReadRoleMembersResponseSexOneMax = 255;

export const workspaceRolesReadRoleMembersResponseMobileOneMax = 255;

export const workspaceRolesReadRoleMembersResponseEmailOneMax = 255;

export const workspaceRolesReadRoleMembersResponseTelephoneOneMax = 255;

export const workspaceRolesReadRoleMembersResponseEmployeeStatusOneMax = 255;

export const workspaceRolesReadRoleMembersResponseReportManagerOneMax = 255;

export const workspaceRolesReadRoleMembersResponseEmployeeTypeOneMax = 255;

export const workspaceRolesReadRoleMembersResponseWorkRegionOneMax = 255;

export const workspaceRolesReadRoleMembersResponseCompanyOneMax = 255;

export const workspaceRolesReadRoleMembersResponseCooperationModeOneMax = 64;

export const workspaceRolesReadRoleMembersResponseWorkSerialNumberOneMax = 128;

export const workspaceRolesReadRoleMembersResponseHeightCmOneMin = 0;
export const workspaceRolesReadRoleMembersResponseHeightCmOneMax = 300;

export const workspaceRolesReadRoleMembersResponsePositionOneMax = 255;

export const workspaceRolesReadRoleMembersResponseMainDeptOneMax = 255;

export const workspaceRolesReadRoleMembersResponseMainDeptIdOneMax = 255;

export const workspaceRolesReadRoleMembersResponseFirstDeptOneMax = 255;

export const workspaceRolesReadRoleMembersResponseSecondDeptOneMax = 255;

export const workspaceRolesReadRoleMembersResponseThirdDeptOneMax = 255;

export const workspaceRolesReadRoleMembersResponseFourthDeptOneMax = 255;

export const workspaceRolesReadRoleMembersResponseFifthDeptOneMax = 255;

export const workspaceRolesReadRoleMembersResponseSixthDeptOneMax = 255;

export const workspaceRolesReadRoleMembersResponseIsActiveDefault = true;

export const WorkspaceRolesReadRoleMembersResponseItem = zod.object({
  "id": zod.uuid().optional(),
  "created_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "updated_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "deleted_at": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "creator_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "updater_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "deleter_id": zod.union([zod.uuid(),zod.null()]).optional(),
  "user_id": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseUserIdOneMax),zod.null()]).optional(),
  "job_number": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseJobNumberOneMax),zod.null()]).optional(),
  "employee_name": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseEmployeeNameOneMax),zod.null()]).optional(),
  "sex": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseSexOneMax),zod.null()]).optional(),
  "mobile": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseMobileOneMax),zod.null()]).optional(),
  "email": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseEmailOneMax),zod.null()]).optional(),
  "telephone": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseTelephoneOneMax),zod.null()]).optional(),
  "employee_status": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseEmployeeStatusOneMax),zod.null()]).optional(),
  "report_manager": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseReportManagerOneMax),zod.null()]).optional(),
  "employee_type": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseEmployeeTypeOneMax),zod.null()]).optional(),
  "work_region": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseWorkRegionOneMax),zod.null()]).optional(),
  "company": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseCompanyOneMax),zod.null()]).optional(),
  "cooperation_mode": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseCooperationModeOneMax),zod.null()]).optional(),
  "work_serial_number": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseWorkSerialNumberOneMax),zod.null()]).optional(),
  "height_cm": zod.union([zod.number().min(workspaceRolesReadRoleMembersResponseHeightCmOneMin).max(workspaceRolesReadRoleMembersResponseHeightCmOneMax),zod.null()]).optional(),
  "position": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponsePositionOneMax),zod.null()]).optional(),
  "entry_date": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "exit_date": zod.union([zod.iso.datetime({}),zod.null()]).optional(),
  "main_dept": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseMainDeptOneMax),zod.null()]).optional(),
  "main_dept_id": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseMainDeptIdOneMax),zod.null()]).optional(),
  "first_dept": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseFirstDeptOneMax),zod.null()]).optional(),
  "second_dept": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseSecondDeptOneMax),zod.null()]).optional(),
  "third_dept": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseThirdDeptOneMax),zod.null()]).optional(),
  "fourth_dept": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseFourthDeptOneMax),zod.null()]).optional(),
  "fifth_dept": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseFifthDeptOneMax),zod.null()]).optional(),
  "sixth_dept": zod.union([zod.string().max(workspaceRolesReadRoleMembersResponseSixthDeptOneMax),zod.null()]).optional(),
  "is_active": zod.boolean().default(workspaceRolesReadRoleMembersResponseIsActiveDefault),
  "account_id": zod.uuid(),
  "workspace_id": zod.uuid(),
  "creator_name": zod.union([zod.string(),zod.null()]).optional(),
  "updater_name": zod.union([zod.string(),zod.null()]).optional()
})
export const WorkspaceRolesReadRoleMembersResponse = zod.array(WorkspaceRolesReadRoleMembersResponseItem)
