/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FieldAuditLogOut,
  HTTPValidationError,
  SystemAuditLogPublic
} from '../schemas';

import { customFetch } from '../../lib/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Retrieve all audit/history logs for a specific entity type and ID.
This routes the query correctly through Postgres partitioning, ensuring high performance.
 * @summary Get Audit Logs
 */
export type infraAuditsGetAuditLogsResponse200 = {
  data: SystemAuditLogPublic[]
  status: 200
}

export type infraAuditsGetAuditLogsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type infraAuditsGetAuditLogsResponseSuccess = (infraAuditsGetAuditLogsResponse200) & {
  headers: Headers;
};
export type infraAuditsGetAuditLogsResponseError = (infraAuditsGetAuditLogsResponse422) & {
  headers: Headers;
};

export type infraAuditsGetAuditLogsResponse = (infraAuditsGetAuditLogsResponseSuccess | infraAuditsGetAuditLogsResponseError)

export const getInfraAuditsGetAuditLogsUrl = (entityType: string,
    entityId: string,) => {




  return `/api/v1/audits/${entityType}/${entityId}`
}

export const infraAuditsGetAuditLogs = async (entityType: string,
    entityId: string, options?: RequestInit): Promise<infraAuditsGetAuditLogsResponse> => {

  return customFetch<infraAuditsGetAuditLogsResponse>(getInfraAuditsGetAuditLogsUrl(entityType,entityId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getInfraAuditsGetAuditLogsQueryKey = (entityType: string,
    entityId: string,) => {
    return [
    `/api/v1/audits/${entityType}/${entityId}`
    ] as const;
    }


export const getInfraAuditsGetAuditLogsQueryOptions = <TData = Awaited<ReturnType<typeof infraAuditsGetAuditLogs>>, TError = HTTPValidationError>(entityType: string,
    entityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAuditsGetAuditLogs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInfraAuditsGetAuditLogsQueryKey(entityType,entityId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof infraAuditsGetAuditLogs>>> = ({ signal }) => infraAuditsGetAuditLogs(entityType,entityId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(entityType && entityId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof infraAuditsGetAuditLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InfraAuditsGetAuditLogsQueryResult = NonNullable<Awaited<ReturnType<typeof infraAuditsGetAuditLogs>>>
export type InfraAuditsGetAuditLogsQueryError = HTTPValidationError


export function useInfraAuditsGetAuditLogs<TData = Awaited<ReturnType<typeof infraAuditsGetAuditLogs>>, TError = HTTPValidationError>(
 entityType: string,
    entityId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAuditsGetAuditLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof infraAuditsGetAuditLogs>>,
          TError,
          Awaited<ReturnType<typeof infraAuditsGetAuditLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInfraAuditsGetAuditLogs<TData = Awaited<ReturnType<typeof infraAuditsGetAuditLogs>>, TError = HTTPValidationError>(
 entityType: string,
    entityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAuditsGetAuditLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof infraAuditsGetAuditLogs>>,
          TError,
          Awaited<ReturnType<typeof infraAuditsGetAuditLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInfraAuditsGetAuditLogs<TData = Awaited<ReturnType<typeof infraAuditsGetAuditLogs>>, TError = HTTPValidationError>(
 entityType: string,
    entityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAuditsGetAuditLogs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Audit Logs
 */

export function useInfraAuditsGetAuditLogs<TData = Awaited<ReturnType<typeof infraAuditsGetAuditLogs>>, TError = HTTPValidationError>(
 entityType: string,
    entityId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAuditsGetAuditLogs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInfraAuditsGetAuditLogsQueryOptions(entityType,entityId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Retrieve audit logs for a specific field of an entity, including operator name.
 * @summary Get Field Audit Logs
 */
export type infraAuditsGetFieldAuditLogsResponse200 = {
  data: FieldAuditLogOut[]
  status: 200
}

export type infraAuditsGetFieldAuditLogsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type infraAuditsGetFieldAuditLogsResponseSuccess = (infraAuditsGetFieldAuditLogsResponse200) & {
  headers: Headers;
};
export type infraAuditsGetFieldAuditLogsResponseError = (infraAuditsGetFieldAuditLogsResponse422) & {
  headers: Headers;
};

export type infraAuditsGetFieldAuditLogsResponse = (infraAuditsGetFieldAuditLogsResponseSuccess | infraAuditsGetFieldAuditLogsResponseError)

export const getInfraAuditsGetFieldAuditLogsUrl = (entityType: string,
    entityId: string,
    fieldName: string,) => {




  return `/api/v1/audits/${entityType}/${entityId}/fields/${fieldName}`
}

export const infraAuditsGetFieldAuditLogs = async (entityType: string,
    entityId: string,
    fieldName: string, options?: RequestInit): Promise<infraAuditsGetFieldAuditLogsResponse> => {

  return customFetch<infraAuditsGetFieldAuditLogsResponse>(getInfraAuditsGetFieldAuditLogsUrl(entityType,entityId,fieldName),
  {
    ...options,
    method: 'GET'


  }
);}





export const getInfraAuditsGetFieldAuditLogsQueryKey = (entityType: string,
    entityId: string,
    fieldName: string,) => {
    return [
    `/api/v1/audits/${entityType}/${entityId}/fields/${fieldName}`
    ] as const;
    }


export const getInfraAuditsGetFieldAuditLogsQueryOptions = <TData = Awaited<ReturnType<typeof infraAuditsGetFieldAuditLogs>>, TError = HTTPValidationError>(entityType: string,
    entityId: string,
    fieldName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAuditsGetFieldAuditLogs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInfraAuditsGetFieldAuditLogsQueryKey(entityType,entityId,fieldName);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof infraAuditsGetFieldAuditLogs>>> = ({ signal }) => infraAuditsGetFieldAuditLogs(entityType,entityId,fieldName, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(entityType && entityId && fieldName), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof infraAuditsGetFieldAuditLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InfraAuditsGetFieldAuditLogsQueryResult = NonNullable<Awaited<ReturnType<typeof infraAuditsGetFieldAuditLogs>>>
export type InfraAuditsGetFieldAuditLogsQueryError = HTTPValidationError


export function useInfraAuditsGetFieldAuditLogs<TData = Awaited<ReturnType<typeof infraAuditsGetFieldAuditLogs>>, TError = HTTPValidationError>(
 entityType: string,
    entityId: string,
    fieldName: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAuditsGetFieldAuditLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof infraAuditsGetFieldAuditLogs>>,
          TError,
          Awaited<ReturnType<typeof infraAuditsGetFieldAuditLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInfraAuditsGetFieldAuditLogs<TData = Awaited<ReturnType<typeof infraAuditsGetFieldAuditLogs>>, TError = HTTPValidationError>(
 entityType: string,
    entityId: string,
    fieldName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAuditsGetFieldAuditLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof infraAuditsGetFieldAuditLogs>>,
          TError,
          Awaited<ReturnType<typeof infraAuditsGetFieldAuditLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInfraAuditsGetFieldAuditLogs<TData = Awaited<ReturnType<typeof infraAuditsGetFieldAuditLogs>>, TError = HTTPValidationError>(
 entityType: string,
    entityId: string,
    fieldName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAuditsGetFieldAuditLogs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Field Audit Logs
 */

export function useInfraAuditsGetFieldAuditLogs<TData = Awaited<ReturnType<typeof infraAuditsGetFieldAuditLogs>>, TError = HTTPValidationError>(
 entityType: string,
    entityId: string,
    fieldName: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof infraAuditsGetFieldAuditLogs>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInfraAuditsGetFieldAuditLogsQueryOptions(entityType,entityId,fieldName,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
