/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EgoReleaseVersionsReadReleaseVersionsParams,
  GenericPageReleaseVersionPublic,
  HTTPValidationError,
  Message,
  ReleaseVersionCreate,
  ReleaseVersionPublic,
  ReleaseVersionUpdate
} from '../schemas';

import { customFetch } from '../../lib/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Read Release Versions
 */
export type egoReleaseVersionsReadReleaseVersionsResponse200 = {
  data: GenericPageReleaseVersionPublic
  status: 200
}

export type egoReleaseVersionsReadReleaseVersionsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoReleaseVersionsReadReleaseVersionsResponseSuccess = (egoReleaseVersionsReadReleaseVersionsResponse200) & {
  headers: Headers;
};
export type egoReleaseVersionsReadReleaseVersionsResponseError = (egoReleaseVersionsReadReleaseVersionsResponse422) & {
  headers: Headers;
};

export type egoReleaseVersionsReadReleaseVersionsResponse = (egoReleaseVersionsReadReleaseVersionsResponseSuccess | egoReleaseVersionsReadReleaseVersionsResponseError)

export const getEgoReleaseVersionsReadReleaseVersionsUrl = (params?: EgoReleaseVersionsReadReleaseVersionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/ego/release-versions/?${stringifiedParams}` : `/api/v1/ego/release-versions/`
}

export const egoReleaseVersionsReadReleaseVersions = async (params?: EgoReleaseVersionsReadReleaseVersionsParams, options?: RequestInit): Promise<egoReleaseVersionsReadReleaseVersionsResponse> => {

  return customFetch<egoReleaseVersionsReadReleaseVersionsResponse>(getEgoReleaseVersionsReadReleaseVersionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getEgoReleaseVersionsReadReleaseVersionsQueryKey = (params?: EgoReleaseVersionsReadReleaseVersionsParams,) => {
    return [
    `/api/v1/ego/release-versions/`, ...(params ? [params] : [])
    ] as const;
    }


export const getEgoReleaseVersionsReadReleaseVersionsQueryOptions = <TData = Awaited<ReturnType<typeof egoReleaseVersionsReadReleaseVersions>>, TError = HTTPValidationError>(params?: EgoReleaseVersionsReadReleaseVersionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoReleaseVersionsReadReleaseVersions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEgoReleaseVersionsReadReleaseVersionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof egoReleaseVersionsReadReleaseVersions>>> = ({ signal }) => egoReleaseVersionsReadReleaseVersions(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof egoReleaseVersionsReadReleaseVersions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EgoReleaseVersionsReadReleaseVersionsQueryResult = NonNullable<Awaited<ReturnType<typeof egoReleaseVersionsReadReleaseVersions>>>
export type EgoReleaseVersionsReadReleaseVersionsQueryError = HTTPValidationError


export function useEgoReleaseVersionsReadReleaseVersions<TData = Awaited<ReturnType<typeof egoReleaseVersionsReadReleaseVersions>>, TError = HTTPValidationError>(
 params: undefined |  EgoReleaseVersionsReadReleaseVersionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoReleaseVersionsReadReleaseVersions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof egoReleaseVersionsReadReleaseVersions>>,
          TError,
          Awaited<ReturnType<typeof egoReleaseVersionsReadReleaseVersions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEgoReleaseVersionsReadReleaseVersions<TData = Awaited<ReturnType<typeof egoReleaseVersionsReadReleaseVersions>>, TError = HTTPValidationError>(
 params?: EgoReleaseVersionsReadReleaseVersionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoReleaseVersionsReadReleaseVersions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof egoReleaseVersionsReadReleaseVersions>>,
          TError,
          Awaited<ReturnType<typeof egoReleaseVersionsReadReleaseVersions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEgoReleaseVersionsReadReleaseVersions<TData = Awaited<ReturnType<typeof egoReleaseVersionsReadReleaseVersions>>, TError = HTTPValidationError>(
 params?: EgoReleaseVersionsReadReleaseVersionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoReleaseVersionsReadReleaseVersions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Release Versions
 */

export function useEgoReleaseVersionsReadReleaseVersions<TData = Awaited<ReturnType<typeof egoReleaseVersionsReadReleaseVersions>>, TError = HTTPValidationError>(
 params?: EgoReleaseVersionsReadReleaseVersionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoReleaseVersionsReadReleaseVersions>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEgoReleaseVersionsReadReleaseVersionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Release Version
 */
export type egoReleaseVersionsCreateReleaseVersionResponse200 = {
  data: ReleaseVersionPublic
  status: 200
}

export type egoReleaseVersionsCreateReleaseVersionResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoReleaseVersionsCreateReleaseVersionResponseSuccess = (egoReleaseVersionsCreateReleaseVersionResponse200) & {
  headers: Headers;
};
export type egoReleaseVersionsCreateReleaseVersionResponseError = (egoReleaseVersionsCreateReleaseVersionResponse422) & {
  headers: Headers;
};

export type egoReleaseVersionsCreateReleaseVersionResponse = (egoReleaseVersionsCreateReleaseVersionResponseSuccess | egoReleaseVersionsCreateReleaseVersionResponseError)

export const getEgoReleaseVersionsCreateReleaseVersionUrl = () => {




  return `/api/v1/ego/release-versions/`
}

export const egoReleaseVersionsCreateReleaseVersion = async (releaseVersionCreate: ReleaseVersionCreate, options?: RequestInit): Promise<egoReleaseVersionsCreateReleaseVersionResponse> => {

  return customFetch<egoReleaseVersionsCreateReleaseVersionResponse>(getEgoReleaseVersionsCreateReleaseVersionUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      releaseVersionCreate,)
  }
);}




export const getEgoReleaseVersionsCreateReleaseVersionMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoReleaseVersionsCreateReleaseVersion>>, TError,{data: ReleaseVersionCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoReleaseVersionsCreateReleaseVersion>>, TError,{data: ReleaseVersionCreate}, TContext> => {

const mutationKey = ['egoReleaseVersionsCreateReleaseVersion'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoReleaseVersionsCreateReleaseVersion>>, {data: ReleaseVersionCreate}> = (props) => {
          const {data} = props ?? {};

          return  egoReleaseVersionsCreateReleaseVersion(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoReleaseVersionsCreateReleaseVersionMutationResult = NonNullable<Awaited<ReturnType<typeof egoReleaseVersionsCreateReleaseVersion>>>
    export type EgoReleaseVersionsCreateReleaseVersionMutationBody = ReleaseVersionCreate
    export type EgoReleaseVersionsCreateReleaseVersionMutationError = HTTPValidationError

    /**
 * @summary Create Release Version
 */
export const useEgoReleaseVersionsCreateReleaseVersion = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoReleaseVersionsCreateReleaseVersion>>, TError,{data: ReleaseVersionCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoReleaseVersionsCreateReleaseVersion>>,
        TError,
        {data: ReleaseVersionCreate},
        TContext
      > => {
      return useMutation(getEgoReleaseVersionsCreateReleaseVersionMutationOptions(options), queryClient);
    }
    /**
 * @summary Update Release Version
 */
export type egoReleaseVersionsUpdateReleaseVersionResponse200 = {
  data: ReleaseVersionPublic
  status: 200
}

export type egoReleaseVersionsUpdateReleaseVersionResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoReleaseVersionsUpdateReleaseVersionResponseSuccess = (egoReleaseVersionsUpdateReleaseVersionResponse200) & {
  headers: Headers;
};
export type egoReleaseVersionsUpdateReleaseVersionResponseError = (egoReleaseVersionsUpdateReleaseVersionResponse422) & {
  headers: Headers;
};

export type egoReleaseVersionsUpdateReleaseVersionResponse = (egoReleaseVersionsUpdateReleaseVersionResponseSuccess | egoReleaseVersionsUpdateReleaseVersionResponseError)

export const getEgoReleaseVersionsUpdateReleaseVersionUrl = (resourceId: string,) => {




  return `/api/v1/ego/release-versions/${resourceId}`
}

export const egoReleaseVersionsUpdateReleaseVersion = async (resourceId: string,
    releaseVersionUpdate: ReleaseVersionUpdate, options?: RequestInit): Promise<egoReleaseVersionsUpdateReleaseVersionResponse> => {

  return customFetch<egoReleaseVersionsUpdateReleaseVersionResponse>(getEgoReleaseVersionsUpdateReleaseVersionUrl(resourceId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      releaseVersionUpdate,)
  }
);}




export const getEgoReleaseVersionsUpdateReleaseVersionMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoReleaseVersionsUpdateReleaseVersion>>, TError,{resourceId: string;data: ReleaseVersionUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoReleaseVersionsUpdateReleaseVersion>>, TError,{resourceId: string;data: ReleaseVersionUpdate}, TContext> => {

const mutationKey = ['egoReleaseVersionsUpdateReleaseVersion'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoReleaseVersionsUpdateReleaseVersion>>, {resourceId: string;data: ReleaseVersionUpdate}> = (props) => {
          const {resourceId,data} = props ?? {};

          return  egoReleaseVersionsUpdateReleaseVersion(resourceId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoReleaseVersionsUpdateReleaseVersionMutationResult = NonNullable<Awaited<ReturnType<typeof egoReleaseVersionsUpdateReleaseVersion>>>
    export type EgoReleaseVersionsUpdateReleaseVersionMutationBody = ReleaseVersionUpdate
    export type EgoReleaseVersionsUpdateReleaseVersionMutationError = HTTPValidationError

    /**
 * @summary Update Release Version
 */
export const useEgoReleaseVersionsUpdateReleaseVersion = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoReleaseVersionsUpdateReleaseVersion>>, TError,{resourceId: string;data: ReleaseVersionUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoReleaseVersionsUpdateReleaseVersion>>,
        TError,
        {resourceId: string;data: ReleaseVersionUpdate},
        TContext
      > => {
      return useMutation(getEgoReleaseVersionsUpdateReleaseVersionMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Release Version
 */
export type egoReleaseVersionsDeleteReleaseVersionResponse200 = {
  data: Message
  status: 200
}

export type egoReleaseVersionsDeleteReleaseVersionResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoReleaseVersionsDeleteReleaseVersionResponseSuccess = (egoReleaseVersionsDeleteReleaseVersionResponse200) & {
  headers: Headers;
};
export type egoReleaseVersionsDeleteReleaseVersionResponseError = (egoReleaseVersionsDeleteReleaseVersionResponse422) & {
  headers: Headers;
};

export type egoReleaseVersionsDeleteReleaseVersionResponse = (egoReleaseVersionsDeleteReleaseVersionResponseSuccess | egoReleaseVersionsDeleteReleaseVersionResponseError)

export const getEgoReleaseVersionsDeleteReleaseVersionUrl = (resourceId: string,) => {




  return `/api/v1/ego/release-versions/${resourceId}`
}

export const egoReleaseVersionsDeleteReleaseVersion = async (resourceId: string, options?: RequestInit): Promise<egoReleaseVersionsDeleteReleaseVersionResponse> => {

  return customFetch<egoReleaseVersionsDeleteReleaseVersionResponse>(getEgoReleaseVersionsDeleteReleaseVersionUrl(resourceId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getEgoReleaseVersionsDeleteReleaseVersionMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoReleaseVersionsDeleteReleaseVersion>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoReleaseVersionsDeleteReleaseVersion>>, TError,{resourceId: string}, TContext> => {

const mutationKey = ['egoReleaseVersionsDeleteReleaseVersion'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoReleaseVersionsDeleteReleaseVersion>>, {resourceId: string}> = (props) => {
          const {resourceId} = props ?? {};

          return  egoReleaseVersionsDeleteReleaseVersion(resourceId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoReleaseVersionsDeleteReleaseVersionMutationResult = NonNullable<Awaited<ReturnType<typeof egoReleaseVersionsDeleteReleaseVersion>>>

    export type EgoReleaseVersionsDeleteReleaseVersionMutationError = HTTPValidationError

    /**
 * @summary Delete Release Version
 */
export const useEgoReleaseVersionsDeleteReleaseVersion = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoReleaseVersionsDeleteReleaseVersion>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoReleaseVersionsDeleteReleaseVersion>>,
        TError,
        {resourceId: string},
        TContext
      > => {
      return useMutation(getEgoReleaseVersionsDeleteReleaseVersionMutationOptions(options), queryClient);
    }
