/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CollectionSopCreate,
  CollectionSopPublic,
  CollectionSopUpdate,
  EgoCollectionSopsReadCollectionSopsParams,
  GenericPageCollectionSopPublic,
  HTTPValidationError,
  Message
} from '../schemas';

import { customFetch } from '../../lib/mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Read Collection Sops
 */
export type egoCollectionSopsReadCollectionSopsResponse200 = {
  data: GenericPageCollectionSopPublic
  status: 200
}

export type egoCollectionSopsReadCollectionSopsResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionSopsReadCollectionSopsResponseSuccess = (egoCollectionSopsReadCollectionSopsResponse200) & {
  headers: Headers;
};
export type egoCollectionSopsReadCollectionSopsResponseError = (egoCollectionSopsReadCollectionSopsResponse422) & {
  headers: Headers;
};

export type egoCollectionSopsReadCollectionSopsResponse = (egoCollectionSopsReadCollectionSopsResponseSuccess | egoCollectionSopsReadCollectionSopsResponseError)

export const getEgoCollectionSopsReadCollectionSopsUrl = (params?: EgoCollectionSopsReadCollectionSopsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/ego/collection-sops/?${stringifiedParams}` : `/api/v1/ego/collection-sops/`
}

export const egoCollectionSopsReadCollectionSops = async (params?: EgoCollectionSopsReadCollectionSopsParams, options?: RequestInit): Promise<egoCollectionSopsReadCollectionSopsResponse> => {

  return customFetch<egoCollectionSopsReadCollectionSopsResponse>(getEgoCollectionSopsReadCollectionSopsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getEgoCollectionSopsReadCollectionSopsQueryKey = (params?: EgoCollectionSopsReadCollectionSopsParams,) => {
    return [
    `/api/v1/ego/collection-sops/`, ...(params ? [params] : [])
    ] as const;
    }


export const getEgoCollectionSopsReadCollectionSopsQueryOptions = <TData = Awaited<ReturnType<typeof egoCollectionSopsReadCollectionSops>>, TError = HTTPValidationError>(params?: EgoCollectionSopsReadCollectionSopsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionSopsReadCollectionSops>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEgoCollectionSopsReadCollectionSopsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof egoCollectionSopsReadCollectionSops>>> = ({ signal }) => egoCollectionSopsReadCollectionSops(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof egoCollectionSopsReadCollectionSops>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EgoCollectionSopsReadCollectionSopsQueryResult = NonNullable<Awaited<ReturnType<typeof egoCollectionSopsReadCollectionSops>>>
export type EgoCollectionSopsReadCollectionSopsQueryError = HTTPValidationError


export function useEgoCollectionSopsReadCollectionSops<TData = Awaited<ReturnType<typeof egoCollectionSopsReadCollectionSops>>, TError = HTTPValidationError>(
 params: undefined |  EgoCollectionSopsReadCollectionSopsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionSopsReadCollectionSops>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof egoCollectionSopsReadCollectionSops>>,
          TError,
          Awaited<ReturnType<typeof egoCollectionSopsReadCollectionSops>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEgoCollectionSopsReadCollectionSops<TData = Awaited<ReturnType<typeof egoCollectionSopsReadCollectionSops>>, TError = HTTPValidationError>(
 params?: EgoCollectionSopsReadCollectionSopsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionSopsReadCollectionSops>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof egoCollectionSopsReadCollectionSops>>,
          TError,
          Awaited<ReturnType<typeof egoCollectionSopsReadCollectionSops>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEgoCollectionSopsReadCollectionSops<TData = Awaited<ReturnType<typeof egoCollectionSopsReadCollectionSops>>, TError = HTTPValidationError>(
 params?: EgoCollectionSopsReadCollectionSopsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionSopsReadCollectionSops>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Read Collection Sops
 */

export function useEgoCollectionSopsReadCollectionSops<TData = Awaited<ReturnType<typeof egoCollectionSopsReadCollectionSops>>, TError = HTTPValidationError>(
 params?: EgoCollectionSopsReadCollectionSopsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof egoCollectionSopsReadCollectionSops>>, TError, TData>>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEgoCollectionSopsReadCollectionSopsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * @summary Create Collection Sop
 */
export type egoCollectionSopsCreateCollectionSopResponse200 = {
  data: CollectionSopPublic
  status: 200
}

export type egoCollectionSopsCreateCollectionSopResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionSopsCreateCollectionSopResponseSuccess = (egoCollectionSopsCreateCollectionSopResponse200) & {
  headers: Headers;
};
export type egoCollectionSopsCreateCollectionSopResponseError = (egoCollectionSopsCreateCollectionSopResponse422) & {
  headers: Headers;
};

export type egoCollectionSopsCreateCollectionSopResponse = (egoCollectionSopsCreateCollectionSopResponseSuccess | egoCollectionSopsCreateCollectionSopResponseError)

export const getEgoCollectionSopsCreateCollectionSopUrl = () => {




  return `/api/v1/ego/collection-sops/`
}

export const egoCollectionSopsCreateCollectionSop = async (collectionSopCreate: CollectionSopCreate, options?: RequestInit): Promise<egoCollectionSopsCreateCollectionSopResponse> => {

  return customFetch<egoCollectionSopsCreateCollectionSopResponse>(getEgoCollectionSopsCreateCollectionSopUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      collectionSopCreate,)
  }
);}




export const getEgoCollectionSopsCreateCollectionSopMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionSopsCreateCollectionSop>>, TError,{data: CollectionSopCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoCollectionSopsCreateCollectionSop>>, TError,{data: CollectionSopCreate}, TContext> => {

const mutationKey = ['egoCollectionSopsCreateCollectionSop'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoCollectionSopsCreateCollectionSop>>, {data: CollectionSopCreate}> = (props) => {
          const {data} = props ?? {};

          return  egoCollectionSopsCreateCollectionSop(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoCollectionSopsCreateCollectionSopMutationResult = NonNullable<Awaited<ReturnType<typeof egoCollectionSopsCreateCollectionSop>>>
    export type EgoCollectionSopsCreateCollectionSopMutationBody = CollectionSopCreate
    export type EgoCollectionSopsCreateCollectionSopMutationError = HTTPValidationError

    /**
 * @summary Create Collection Sop
 */
export const useEgoCollectionSopsCreateCollectionSop = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionSopsCreateCollectionSop>>, TError,{data: CollectionSopCreate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoCollectionSopsCreateCollectionSop>>,
        TError,
        {data: CollectionSopCreate},
        TContext
      > => {
      return useMutation(getEgoCollectionSopsCreateCollectionSopMutationOptions(options), queryClient);
    }
    /**
 * @summary Update Collection Sop
 */
export type egoCollectionSopsUpdateCollectionSopResponse200 = {
  data: CollectionSopPublic
  status: 200
}

export type egoCollectionSopsUpdateCollectionSopResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionSopsUpdateCollectionSopResponseSuccess = (egoCollectionSopsUpdateCollectionSopResponse200) & {
  headers: Headers;
};
export type egoCollectionSopsUpdateCollectionSopResponseError = (egoCollectionSopsUpdateCollectionSopResponse422) & {
  headers: Headers;
};

export type egoCollectionSopsUpdateCollectionSopResponse = (egoCollectionSopsUpdateCollectionSopResponseSuccess | egoCollectionSopsUpdateCollectionSopResponseError)

export const getEgoCollectionSopsUpdateCollectionSopUrl = (resourceId: string,) => {




  return `/api/v1/ego/collection-sops/${resourceId}`
}

export const egoCollectionSopsUpdateCollectionSop = async (resourceId: string,
    collectionSopUpdate: CollectionSopUpdate, options?: RequestInit): Promise<egoCollectionSopsUpdateCollectionSopResponse> => {

  return customFetch<egoCollectionSopsUpdateCollectionSopResponse>(getEgoCollectionSopsUpdateCollectionSopUrl(resourceId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      collectionSopUpdate,)
  }
);}




export const getEgoCollectionSopsUpdateCollectionSopMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionSopsUpdateCollectionSop>>, TError,{resourceId: string;data: CollectionSopUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoCollectionSopsUpdateCollectionSop>>, TError,{resourceId: string;data: CollectionSopUpdate}, TContext> => {

const mutationKey = ['egoCollectionSopsUpdateCollectionSop'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoCollectionSopsUpdateCollectionSop>>, {resourceId: string;data: CollectionSopUpdate}> = (props) => {
          const {resourceId,data} = props ?? {};

          return  egoCollectionSopsUpdateCollectionSop(resourceId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoCollectionSopsUpdateCollectionSopMutationResult = NonNullable<Awaited<ReturnType<typeof egoCollectionSopsUpdateCollectionSop>>>
    export type EgoCollectionSopsUpdateCollectionSopMutationBody = CollectionSopUpdate
    export type EgoCollectionSopsUpdateCollectionSopMutationError = HTTPValidationError

    /**
 * @summary Update Collection Sop
 */
export const useEgoCollectionSopsUpdateCollectionSop = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionSopsUpdateCollectionSop>>, TError,{resourceId: string;data: CollectionSopUpdate}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoCollectionSopsUpdateCollectionSop>>,
        TError,
        {resourceId: string;data: CollectionSopUpdate},
        TContext
      > => {
      return useMutation(getEgoCollectionSopsUpdateCollectionSopMutationOptions(options), queryClient);
    }
    /**
 * @summary Delete Collection Sop
 */
export type egoCollectionSopsDeleteCollectionSopResponse200 = {
  data: Message
  status: 200
}

export type egoCollectionSopsDeleteCollectionSopResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type egoCollectionSopsDeleteCollectionSopResponseSuccess = (egoCollectionSopsDeleteCollectionSopResponse200) & {
  headers: Headers;
};
export type egoCollectionSopsDeleteCollectionSopResponseError = (egoCollectionSopsDeleteCollectionSopResponse422) & {
  headers: Headers;
};

export type egoCollectionSopsDeleteCollectionSopResponse = (egoCollectionSopsDeleteCollectionSopResponseSuccess | egoCollectionSopsDeleteCollectionSopResponseError)

export const getEgoCollectionSopsDeleteCollectionSopUrl = (resourceId: string,) => {




  return `/api/v1/ego/collection-sops/${resourceId}`
}

export const egoCollectionSopsDeleteCollectionSop = async (resourceId: string, options?: RequestInit): Promise<egoCollectionSopsDeleteCollectionSopResponse> => {

  return customFetch<egoCollectionSopsDeleteCollectionSopResponse>(getEgoCollectionSopsDeleteCollectionSopUrl(resourceId),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getEgoCollectionSopsDeleteCollectionSopMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionSopsDeleteCollectionSop>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof egoCollectionSopsDeleteCollectionSop>>, TError,{resourceId: string}, TContext> => {

const mutationKey = ['egoCollectionSopsDeleteCollectionSop'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof egoCollectionSopsDeleteCollectionSop>>, {resourceId: string}> = (props) => {
          const {resourceId} = props ?? {};

          return  egoCollectionSopsDeleteCollectionSop(resourceId,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EgoCollectionSopsDeleteCollectionSopMutationResult = NonNullable<Awaited<ReturnType<typeof egoCollectionSopsDeleteCollectionSop>>>

    export type EgoCollectionSopsDeleteCollectionSopMutationError = HTTPValidationError

    /**
 * @summary Delete Collection Sop
 */
export const useEgoCollectionSopsDeleteCollectionSop = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof egoCollectionSopsDeleteCollectionSop>>, TError,{resourceId: string}, TContext>, request?: SecondParameter<typeof customFetch>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof egoCollectionSopsDeleteCollectionSop>>,
        TError,
        {resourceId: string},
        TContext
      > => {
      return useMutation(getEgoCollectionSopsDeleteCollectionSopMutationOptions(options), queryClient);
    }
