/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Ego Collection Management
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Return upload thresholds so the frontend can auto-select strategy.
 * @summary Read Upload Config
 */
export const FilesReadUploadConfigResponse = zod.object({
  "chunk_threshold": zod.number(),
  "chunk_size": zod.number(),
  "max_file_size": zod.number()
})

/**
 * Proxy-upload a small file (≤ chunk_threshold) via backend to MinIO.
 * @summary Upload File
 */
export const filesUploadFileBodyFolderDefault = `omega/`;

export const FilesUploadFileBody = zod.object({
  "file": zod.instanceof(File),
  "folder": zod.string().default(filesUploadFileBodyFolderDefault)
})

export const FilesUploadFileResponse = zod.object({
  "file_path": zod.string(),
  "file_name": zod.string(),
  "file_size": zod.number()
})

/**
 * Initialize an S3 multipart upload.
Returns an upload_id and presigned PUT URLs for each part.
 * @summary Init Multipart Upload
 */
export const filesInitMultipartUploadBodyFolderDefault = `omega/`;

export const FilesInitMultipartUploadBody = zod.object({
  "file_name": zod.string(),
  "file_size": zod.number(),
  "folder": zod.string().default(filesInitMultipartUploadBodyFolderDefault)
})

export const FilesInitMultipartUploadResponse = zod.object({
  "upload_id": zod.string(),
  "file_path": zod.string(),
  "file_name": zod.string(),
  "parts": zod.array(zod.object({
  "part_number": zod.number(),
  "upload_url": zod.string()
}))
})

/**
 * Complete a multipart upload — instructs MinIO to assemble all parts.
 * @summary Complete Multipart Upload
 */
export const filesCompleteMultipartUploadBodyFileNameDefault = ``;

export const FilesCompleteMultipartUploadBody = zod.object({
  "upload_id": zod.string(),
  "file_path": zod.string(),
  "file_name": zod.string().default(filesCompleteMultipartUploadBodyFileNameDefault),
  "parts": zod.array(zod.object({
  "part_number": zod.number(),
  "etag": zod.string()
}))
})

export const FilesCompleteMultipartUploadResponse = zod.object({
  "file_path": zod.string(),
  "file_name": zod.string(),
  "file_size": zod.number()
})

/**
 * Abort a multipart upload — cleans up already-uploaded parts.
 * @summary Abort Multipart Upload
 */
export const FilesAbortMultipartUploadBody = zod.object({
  "upload_id": zod.string(),
  "file_path": zod.string()
})

export const FilesAbortMultipartUploadResponse = zod.unknown()

/**
 * Stream a file from MinIO through the backend (authenticated).
 * @summary Proxy File
 */
export const FilesProxyFileParams = zod.object({
  "file_path": zod.string()
})

export const FilesProxyFileResponse = zod.unknown()

/**
 * Stream a file from MinIO without authentication.
For external services (AI, etc.) that need file access.
 * @summary Public Proxy File
 */
export const FilesPublicProxyFileParams = zod.object({
  "file_path": zod.string()
})

export const FilesPublicProxyFileResponse = zod.unknown()
